### PR TITLE
Visualization of the advance dependency graph

### PR DESCRIPTION
**Pull request by LynxAbraxas**
PR in conjuction to #130, creating a visualization of the advance dependency graph.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Current result , still needs a bit of work concerning some inappropirate nodes and the lay-out.

**Comment by MartinGuehmann** [comment]
> Current result , still needs a bit of work concerning some inappropirate nodes and the lay-out.

Already, very nice. But true, where is that null node and the feat nodes are coming from? I guess stretching it a bit would make it nice.

**Comment by LynxAbraxas** [comment]
> where is that null node and the feat nodes are coming from?

The conversion of 7494948 is not ideal. The tuning of the lay-out is still due and it might be possible to put the icons in and even the info what each advance brings.

**Comment by MartinGuehmann** [comment]
> The conversion of [7494948](https://github.com/civctp2/civctp2/commit/7494948da45c760df95b552f18b383ad8996c437) is not ideal.

Unfortunately, I cannot really help with that.

> The tuning of the lay-out is still due and it might be possible to put the icons in and even the info what each advance brings.

I am really looking forward to this. But for that we have to extract the rim files from the zfs archive.

**Comment by LynxAbraxas** [comment]
> Unfortunately, I cannot really help with that.

No problem, I just need to find some time for tuning that (won't happen in the next 2 week though).

> we have to extract the rim files from the zfs archive.

Would be great if you could help with that, ideally for Linux;-)

**Comment by MartinGuehmann** [comment]
> Would be great if you could help with that, ideally for Linux;-)

Well, if you just need to extract them once, you should be fine with ReadZFS in #185. It should run on Wine.

**Comment by LynxAbraxas** [comment]
Thanks @MartinGuehmann, seems to work fine for `ctp2_data/default/graphics/pictures/pic555.zfs`. Now what to do with the extracted images? Should they be made part of this PR, i.e. of the repo?

**Comment by LynxAbraxas** [comment]
So here the auto-generated [PDF](https://github.com/civctp2/civctp2/blob/0b15a4027c1b095fa4ee446c034391fd4fdac26b/Advance-Graph/Advance.pdf) of the advance graph. 
It should be possible to have all root-nodes on the same rank and it should also be possible to group each age in a subgraph-box, but this is beond my current `gvpr` abilities.

@MartinGuehmann what do you think, can you help or can this go in as is?

**Comment by LynxAbraxas** [comment]
> It should be possible to have all root-nodes on the same rank and it should also be possible to group each age in a subgraph-box, but this is beond my current gvpr abilities.

Opened #187 for this.

**Comment by MartinGuehmann** [comment]
> So here the auto-generated [PDF](https://github.com/civctp2/civctp2/blob/0b15a4027c1b095fa4ee446c034391fd4fdac26b/Advance-Graph/Advance.pdf) of the advance graph.
> It should be possible to have all root-nodes on the same rank and it should also be possible to group each age in a subgraph-box, but this is beond my current `gvpr` abilities.

Well, I guess that is also beyond my `gvpr` abilities. Probably your `gvpr` abilities are also beyond mine.

> @MartinGuehmann what do you think, can you help or can this go in as is?

As far as I can see it uses the pictures from Activision's default set, but not those from CityMod, which are the ones that are used in the Great Library.

I don't know how you associated the icons, but I would guess that you haven't taken it from the icon database. The icon definitions are in uniticon.txt. advanceicon.txt is a leftover from CTP1.

> Thanks @MartinGuehmann, seems to work fine for `ctp2_data/default/graphics/pictures/pic555.zfs`. Now what to do with the extracted images? Should they be made part of this PR, i.e. of the repo?

Let's say as long as that are the tech images it is fine, but not the whole zfs file, first because that is some space and second then you could play the game without the retail version.

**Comment by LynxAbraxas** [comment]
> The icon definitions are in uniticon.txt. advanceicon.txt is a leftover from CTP1.

They are taken from `uniticon.txt`: https://github.com/civctp2/civctp2/pull/184/files#diff-6248a2b71ae14a0bad0fc4564620675eR11
However I only used images from `ctp2_data/default/graphics/pictures/pic555.zfs`, is CityMod providing replacements?

**Comment by MartinGuehmann** [comment]
> > The icon definitions are in uniticon.txt. advanceicon.txt is a leftover from CTP1.
> 
> They are taken from `uniticon.txt`: https://github.com/civctp2/civctp2/pull/184/files#diff-6248a2b71ae14a0bad0fc4564620675eR11
> However I only used images from `ctp2_data/default/graphics/pictures/pic555.zfs`, is CityMod providing replacements?

That are the files with the CM2_ prefix. They are also in the picture folder. I don't get it if you use the data from uniticon.txt then you must drop these prefixes.

**Comment by LynxAbraxas** [comment]
> That are the files with the CM2_ prefix. They are also in the picture folder. I don't get it if you use the data from uniticon.txt then you must drop these prefixes.

I was only using those from the ZFS, so made and extra effort of dropping the CM2_ prefix (https://github.com/civctp2/civctp2/commit/f371d2649fe273b19bd7fbdce2e9f33455d9ec48). Now reverted and working with the CM2-images as PNGs.
Are those from the community? How did they replace the background?

**Comment by MartinGuehmann** [comment]
> > That are the files with the CM2_ prefix. They are also in the picture folder. I don't get it if you use the data from uniticon.txt then you must drop these prefixes.
> 
> I was only using those from the ZFS, so made and extra effort of dropping the CM2_ prefix ([f371d26](https://github.com/civctp2/civctp2/commit/f371d2649fe273b19bd7fbdce2e9f33455d9ec48)). Now reverted and working with the CM2-images as PNGs.
> Are those from the community? How did they replace the background?

I made those. There were some, I could use from CTP1, where you have them without background. And the others I cut out. Put on, blurred the edges and added a shadow, like in the original.

Then you need the backgrounds, each age has a background, from the existing ages you have them in the zfs file, for the new ages I took the background of the buildings. Here I just put them together from the different images, the parts that weren't covered. These are now in the folder too.

**Comment by LynxAbraxas** [comment]
Cool, thanks. That sounds like a lof of effort. The stitching isn't noticeable at all. 
So CM2 stands for CityMod the 2nd? So did CM2 introduce some more ages in the game logic as well?

**Comment by MartinGuehmann** [comment]
> Cool, thanks. That sounds like a lof of effort. The stitching isn't noticeable at all.

Thanks. :D That was actually the point, to make it look like it game with the game. Sure it was quite some effort. Actually, I had no ReadZFS that means I took screen shots from the Great Library and cut those out. 

> So CM2 stands for CityMod the 2nd? So did CM2 introduce some more ages in the game logic as well?

For the original CityMod, I just took the city sprites from Harlan Tompson's CityMod from CTP1. Basically, the thing that made me becoming a modder and learn speaking English on Apolyton.

CM2 is CityMod2, I simply had to make an Egyptian city style, on Apolyton somebody posted some palace city style, which also went into that mod, and than I created the new images, so that it fits in with the original.

Harlan's mod added an industrial age, I added a few more, basically they add some mile stones and some variety in city style, however not every age has its own style. Simply, I had ten backgrounds, so that are ten ages.

Comparing the two PDFs, it looks that my age choice could be a bit fine tuned. But of course, I never had such a poster to look at, so that I could judge it.

I guess, we can merge. And whatever is to come goes into the next PR.

**Comment by LynxAbraxas** [comment]
> CM2 is CityMod2, I simply had to make an Egyptian city style

Really cool, so the pyramid in Egyptian cities comes from that?

> some palace city style, which also went into that mod

Hm, what/where are those?

> I guess, we can merge. And whatever is to come goes into the next PR.

Yes, please go ahead. When I have some better `gvpr` knowledge, I'll try to do some fine tuning in #187.

**Comment by MartinGuehmann** [comment]
> > CM2 is CityMod2, I simply had to make an Egyptian city style
> 
> Really cool, so the pyramid in Egyptian cities comes from that?

Yes.

> > some palace city style, which also went into that mod
> 
> Hm, what/where are those?

Check out Miami in your test game, as you can see it on the screenshots in #159.
 
> > I guess, we can merge. And whatever is to come goes into the next PR.
> 
> Yes, please go ahead. When I have some better `gvpr` knowledge, I'll try to do some fine tuning in #187.

So then I'll go ahead, I already removed the WIP label.

**Comment by LynxAbraxas** [comment]
> So then I'll go ahead, I already removed the WIP label.

That's great, thanks, had forgotten  that.

**Pull request merged**
