### PR TITLE
Let GlobeSat only reveal some units 

### PR DESCRIPTION
**Pull request by LynxAbraxas**
PR to realize #238, with the basic idea that civilian units cannot be distinguished from ordinary civilians, so the Global Sat wonder cannot reveal these.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
So far this leads to a segfault on `IsCivilian` of 
https://github.com/civctp2/civctp2/blob/00ac5f37dcf022919b2dddc14bf8db32e52c7a89/ctp2_code/gs/gameobj/UnitData.cpp#L2559
Any idea why?

**Comment by MartinGuehmann** [comment]
So GlobeSat does not reveal settlers, but nuke-planting spies? I thought it was about hiding stealth units. Anyway, I would add a new flag InvisibleForGlobeSat, so that it can be fine tuned.

Actually, what is an ordinary civilian.

**Comment by LynxAbraxas** [comment]
> So GlobeSat does not reveal settlers, but nuke-planting spies? 

Good point, so far civilians are:

```
awk '/{/ {a=$1}; /Civilian/ {print a}' ./ctp2_data/default/gamedata/Units.txt 
UNIT_ABOLITIONIST
UNIT_CLERIC
UNIT_CORPORATE_BRANCH
UNIT_DIPLOMAT
UNIT_EMPATHIC_DIPLOMAT
UNIT_LAWYER
UNIT_SEA_ENGINEER
UNIT_SETTLER
UNIT_TELEVANGELIST
UNIT_URBAN_PLANNER
```

So we could either make Spies civilians as well or "add a new flag InvisibleForGlobeSat". Does a new flag need many changes?

> Actually, what is an ordinary civilian.

With that I meant those that have no tactical meaning, i.e. non-units like the common population or traders. 
NB: GlobeSat does not reveal the current state of trade routes (#256), i.e. you still have to explore their status with units (which is intentional) to avoid that GlobeSat gives a too big advantage and to avoid that it would give info the AI would not be able to consider.

**Comment by LynxAbraxas** [comment]
> Any idea why?

Lead to a segfault because armies might already be gone.

**Comment by MartinGuehmann** [comment]
> So we could either make Spies civilians as well or "add a new flag InvisibleForGlobeSat". Does a new flag need many changes?

I do not consider anybody who plants nukes as a civilian. As a modder you might want to hide other things from GlobeSat, so it should be a new flag.

About the changes, you already have added new flags to const.txt, it is the same for unit.txt. And then you have to duplicate the code for IsCivilian.

**Comment by LynxAbraxas** [comment]
> About the changes, you already have added new flags to const.txt, it is the same for unit.txt. And then you have to duplicate the code for IsCivilian.

I'll give it a try, but it will have to wait a bit, I've very little spare time at the moment.

**Comment by LynxAbraxas** [comment]
While this seems to work in gerneral, Settlers, Urban Planners, Diplomats and Emphatic Diplomats are still visible even if outside any normal vision. Any ideas why that is the case?

**Comment by LynxAbraxas** [comment]
Not sure why this was closed, at least it was unintentionally.

**Comment by MartinGuehmann** [comment]
> While this seems to work in gerneral, Settlers, Urban Planners, Diplomats and Emphatic Diplomats are still visible even if outside any normal vision. Any ideas why that is the case?

I don't know why. But why should Settlers, Urban Planners, Diplomats, and Emphatic Diplomats be hidden from GlobeSat. They are not stealth units.

**Comment by LynxAbraxas** [comment]
> But why should Settlers, Urban Planners, Diplomats, and Emphatic Diplomats be hidden from GlobeSat. They are not stealth units.

2 reasons:
1. They are not stealth but also do not appear militaristic, i.e. in a high-res sat image they would look like normal people. That's why I decided to take out the sea-engineer. 
2. In the scope of the game GlobeSat before this PR is giving so much advantage to the owning civ, that it is hardly possible to still challenge that civ, in addition many advantages seem not usable for the AI (e.g. fly lawyers to every corporate branch popping up on the map to sue it before it can do any attack at all), so in turn it can be seen as a too big advantage for a human player. So all modifications here are meant to balance the game a bit more.

Any way I'm happy to adjust this as you see fits best, but before I'd like it to work in general, i.e. also for Settlers, Urban Planners, Diplomats, and Emphatic Diplomats.

**Comment by LynxAbraxas** [comment]
Found another ref
https://github.com/civctp2/civctp2/blob/24d98c14ed163e80a1789ab0892a478f284d7133/ctp2_code/gs/gameobj/Player.cpp#L5767-L5784
that eventually seems to lead to the GlobSat flags and might have an effect on the visibility of units, which I tried to adjust accordingly in e760bf17cb5b299f4bf559b6f0beb1091d5f7cd0 but the game segfaults that way during the evaluation towards the new turn.

**Comment by MartinGuehmann** [comment]
> Any way I'm happy to adjust this as you see fits best, but before I'd like it to work in general, i.e. also for Settlers, Urban Planners, Diplomats, and Emphatic Diplomats.

Well, you could argue that you could see 10000 or 30000 people from space. In any way, I would treat Settlers, Urban Planners, and Sea Engineers the same.

Diplomats are very visible to foreign states, more visible than citizens. However, it should be more related to the game concepts, like small stealth units. That's a bit easier to grasp as a player, I think.

**Comment by MartinGuehmann** [comment]
> that eventually seems to lead to the GlobSat flags and might have an effect on the visibility of units, which I tried to adjust accordingly in [e760bf1](https://github.com/civctp2/civctp2/commit/e760bf17cb5b299f4bf559b6f0beb1091d5f7cd0) but the game segfaults that way during the evaluation towards the new turn.

Actually, in this case you should use `m_army.IsValid()`. `m_army.m_id` can be anything, either because it is uninitialized or it is an ID of an army that does not exist anymore.

**Comment by LynxAbraxas** [comment]
Yes, true, thanks @MartinGuehmann for that hint, changed accordingly.

> but the game segfaults that way during the evaluation towards the new turn.

Was not due to that change but due to https://github.com/civctp2/civctp2/pull/311#issuecomment-651999928

**Comment by MartinGuehmann** [comment]
Then let's merge this, too.

**Pull request merged**
