### PR TITLE
Make the Linux version load Windows save games if messages are stored

### PR DESCRIPTION
**Pull request by MartinGuehmann**
The Linux version still could not load save games created on Windows if the message list contained some messages. Probably, only a few messages caused this problem, so that deleting all the messages before switching to this version may already convert old Linux save games.
..\ctp2_code\gs\slic\SlicArray.cpp

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Did not observe this with the provided save-games from https://github.com/civctp2/civctp2/pull/70/commits/43443d09f856e861433d227aee192088dd2342e1. Do those contain messages?

As https://github.com/civctp2/civctp2/pull/70/commits/43443d09f856e861433d227aee192088dd2342e1 was part of #70 (which was closed in favor of #77), how about cherry-picking https://github.com/civctp2/civctp2/pull/70/commits/43443d09f856e861433d227aee192088dd2342e1 for this PR?

**Comment by MartinGuehmann** [comment]
> Did not observe this with the provided save-games from [43443d0](https://github.com/civctp2/civctp2/commit/43443d09f856e861433d227aee192088dd2342e1). Do those contain messages?

No, that are save games with an AI as the visible player. If the visible player is an AI you don't get messages. Only the diplomanger pops up. Of course, everything is than already negotiated.

> As [43443d0](https://github.com/civctp2/civctp2/commit/43443d09f856e861433d227aee192088dd2342e1) was part of #70 (which was closed in favor of #77), how about cherry-picking [43443d0](https://github.com/civctp2/civctp2/commit/43443d09f856e861433d227aee192088dd2342e1) for this PR?

Well, I am rather thinking about other savegames. The thing is that we always could miss more. The save games you game me loaded on Windows fine. I am just not sure whether they contained any messages. But even if only some messages cause trouble.

**Comment by LynxAbraxas** [comment]
> I am just not sure whether they contained any messages.

The game was manually played, i.e. not only by the AI.

**Comment by MartinGuehmann** [comment]
Then this can go in, since the save game converter has been updated.

**Pull request merged**
