### PR TITLE
Improve listbox and dropdown-list look

### PR DESCRIPTION
**Pull request by williamd67**
This PR improves the look and representation of all listboxes and dropdown-lists.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
#371 might fit in this scope.

**Comment by MartinGuehmann** [comment]
I could resolve one of the conflict, but the others I would prefer to leave to you, @williamd67.

**Comment by williamd67** [comment]
This branch improves the drawing of #365:
Screenshot from 2021-08-20 13-11-25

**Comment by LynxAbraxas** [comment]
Looks great now! Many thanks @williamd67 for tuning this.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann ready for merge?

**Comment by MartinGuehmann** [comment]
It still has conflicts, and I am more comfortable with @williamd67 resolving them.

**Comment by williamd67** [comment]
Thanks @LynxAbraxas.
@MartinGuehmann, I fixed the merge conflicts.

Next to the regular merge-conflicts there was one build issue, that I fixed as well. GetBorderOffset was introduced in an already merged PR, while in this PR the type of m_borderOffset changed from POINT to RECT.

**Comment by LynxAbraxas** [comment]
Tested for a while now and works as expected, however does not fix #371 (800x600 screen size for testing):

screenshot

@williamd67 do yo see a chance to include a fix for that in this PR?

**Comment by williamd67** [comment]
@LynxAbraxas, I will investigate it.

**Comment by williamd67** [comment]
@LynxAbraxas, I expect that this fixes #371.

**Comment by LynxAbraxas** [comment]
@williamd67 yes this is great and fixes #371:
screenshot

**Comment by LynxAbraxas** [comment]
May I suggest to cherry-pick https://github.com/LynxAbraxas/civctp2/commit/a4f13cf448c718655b74daf34c2f9a446b8f6e00 which seems needed due to the changed graphics (or you could allow pushes from others for this PR).

**Comment by williamd67** [comment]
@LynxAbraxas cherry-picked your changes.

**Comment by MartinGuehmann** [comment]
@williamd67 could you resolve the merge conflict. If then everything is fine, I assume that it can then be merged.

**Comment by LynxAbraxas** [comment]
Thanks @williamd67.
I think the conflicts arose from the merge of #368.
Otherwise ready to be merged in my opinion.

**Comment by MartinGuehmann** [comment]
Of course, they come from some merge, but I must merge them in some order. And I would assume if I had done it the other way around it would also have produced conflicts.

Anyway, I recommend to rebase it onto the current master, this way all the commits should be compilable on Windows with VS.

**Comment by williamd67** [comment]
@MartinGuehmann I resolved the merge conflicts and rebased with master.

**Comment by MartinGuehmann** [comment]
Then we can merge.

**Pull request merged**
