### PR TITLE
WIP: Incorrect unit animations

### PR DESCRIPTION
**Pull request by williamd67**
I expect that this fixes issue #307 'Jumping unit animations'.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Yeah, I have observed that too sometimes (not sure under which conditions it happens for me) and it is very obvious in a screen cast of @Askmewho: https://github.com/civctp2/civctp2/issues/262#issuecomment-592913847.
Will try to test this.

**Comment by LynxAbraxas** [comment]
Only very rarely observed this effect on my PC (even though it is quite old) so cannot really say if it got resolved but tested the game together with this PR and could not observe any unintended side effects, so I've no objections concerning a merge.

**Comment by williamd67** [comment]
The Director as interface (abstract class) has been introduced to get grip on the animation-issues. I kept the changes to other classes than Director as minimal as possible. I prefer to hide implementation details and decouple as much as possible. This will allow local changes without impacting other classes. 

@MartinGuehmann, @LynxAbraxas what do you think of this change?

**Comment by williamd67** [comment]
I expect that the latest commit fixes the (dis-)appearing units when enemy moves are shown.

I still see one (or more) units where only the **shield** is animated/moved. Is this expected behavior, per example for stealth units or is this another glitch I can look into? When stealth units are hidden, do you see something like the shield/flag or are they really unknown for the viewer?

This does not fix the issue that UnitData and UnitActor are misaligned. I will create a separate pull-request for that.

**Comment by LynxAbraxas** [comment]
Will test this new commits. I noticed with the old one that the enemy moves were only giving sound for the move from the first tile but not from following ones.

**Comment by williamd67** [comment]
I noticed after slowing down the animations that there is a clear glitch where the facing of the unit is incorrect. I will look into that.

**Comment by LynxAbraxas** [comment]
> Will test this new commits. I noticed with the old one that the enemy moves were only giving sound for the move from the first tile but not from following ones.

This is still present with the new commits. Every odd unit move seems to have sound and every even seems to have none.

> I noticed after slowing down the animations that there is a clear glitch where the facing of the unit is incorrect.

I can remember @MartinGuehmann mentioning that the sprites seem to not keep their facing direction, cannot remember in which context that was though.

**Comment by williamd67** [comment]
Found the following issues with unit-animations:
* no sound played for units that ends in transporter
* unit sound does not stop and plays through other unit sounds
* televangelist not facing city when executing special attack
* unit animation jumping

**Comment by LynxAbraxas** [comment]
Will test the new commits. There was one before you force pushed where units were returning to their default position after every move, which is now gone (which is good).

**Comment by williamd67** [comment]
I am currently refactoring Director and friends. The aim is to make the code more straight-forward and make dependencies one-way.

**Comment by LynxAbraxas** [comment]
> I am currently refactoring Director and friends. The aim is to make the code more straight-forward and make dependencies one-way.

That's great. I guess you mean your williamd67/refactor-director branch, which has no PR (yet), since it is based on #298 and this PR, which need to be merged first. When it becomes a PR I would recommend a rebase before its final merge to avoid the multiple merge commits of williamd67/sdl2-master.

**Comment by williamd67** [comment]
> When it becomes a PR I would recommend a rebase before its final merge...

I will definitely do that and will rebase with the master at that moment in time.

I have a general request, do any of you have some save files that are far in the game which I will use to run a turn and save before the refactoring and after so that I can verify that the functionality of the code did not change. Thanks.

**Comment by LynxAbraxas** [comment]
> some save files that are far in the game 

Sure: 
[close2GaiaControllerOnline.zip](https://github.com/civctp2/civctp2/files/4652857/close2GaiaControllerOnline.zip)

**Comment by williamd67** [comment]
When using the save-games to compare the results before and after my changes I saw a strange difference between doing an end-turn with show-enemy-moves and without.
Test-case:
1. load a previously stored game
2. press end-turn
3. wait till it is done
4. exit CTP2
5. use the automatically generated AUTOSAVE for inspection.

The save-game contains two differences when I do this with and without show-enemy-moves enabled:
1. the facing of the actors differs (which may be caused by the animation of the actors);
2. city walls are all unset (0) in the save-game of 'show-enemy-moves' disabled while they are set (1) for the save-game of 'show-enemy-moves' enabled'.

My first guess is that the render code 'fixes' the state of the city-walls. As there is in the RepaintLayerSprites a call to SetHasCityWalls. This seems a patch to me.

I have no idea if this causes any issues still it seems strange.

BTW: I expected that running 'end-turn' with and without show-enemy-moves should result in the same end-state.

**Comment by LynxAbraxas** [comment]
Just as a ref concerning city wall drawing: #244.

**Comment by williamd67** [comment]
This PR is replaced with #314.

**Pull request closed without merging**
