### PR TITLE
Try to fix issue of Docker with freetype build

### PR DESCRIPTION
**Pull request by ptitSeb**
Should improve things about Docker build (issue #20 and #21)

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Not needed for Docker build with #13 and its squashed version #23.

**Comment by MartinGuehmann** [comment]
Is this actually still needed. And I am starting whether the freetype is actually used by CTP2, the Linux branch does not have it. The manuals don't seem to mention it.

**Comment by LynxAbraxas** [comment]
This PR is not needed since #23 was merged and can be closed.

Freetype is needed for both master and linux branch under linux, and has to be built separately for the linux branch, see https://github.com/LynxAbraxas/ctp2DF/blob/linux/Dockerfile#L27-L40. The inclusion in the master branch works such that this is not necessary for the master branch, see https://github.com/LynxAbraxas/ctp2DF/blob/master/Dockerfile.

**Comment by MartinGuehmann** [comment]
I see that the Dockerfile builds it from the repository. And if I build the Linux branch directly, which I haven't done so far do I have to install it myself. So far I haven't found it in the instruction of the readme.linux.

**Pull request closed without merging**
