### PR TITLE
Activate all goods

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR activates all goods to be used during map generation allowing to replace good sprites even for saved games.

### CODE REVIEW

**Comment by MartinGuehmann** [comment]
goods.txt: uncomment[ed] all disabled entries

Now, you have to make all these entries unique, or at least to modify all the entries to give them some meaningful entries. When I added these entries, those were rather placeholders, to have a full set for each terrain. In fact it would make more sense to find unique goods for these terrains.

**Comment by LynxAbraxas** [comment]
Thanks @MartinGuehmann for chiming in.

> When I added these entries, those were rather placeholders, to have a full set for each terrain. In fact it would make more sense to find unique goods for these terrains.

That's the basic idea. I created some new good sprites (octopus, turtle) but am running into instabilities with the automation with sikuli (some click events do not pass to ctp2 but multiple one cause a segfault). There are cpp directives like `__MAKESPR__` concerning unit sprites, which made me wonder if the source could be compiled such that a CLI like `makespr` can be build. Do you know if that was tested after the source was released? A CLI would make the creation of new sprites much easier.

I've also noticed that these changes (specifically to `gl_str.txt`) screw up the game messages when a saved game is loaded that was started with an earlier version of ctp2. Do the strings of  `gl_str.txt` somehow enter into the save-game-files?

**Comment by MartinGuehmann** [comment]
> That's the basic idea. I created some new good sprites (octopus, turtle)

Yeah, I have seen with your additional commits that you are going into this direction. Since I haven't worked with Git so far, I am not so familiar with these throw away branches. As I can see this issue is a sort of its own branch you commit everything, over a while and then you request merging it. 

> but am running into instabilities with the automation with sikuli (some click events do not pass to ctp2 but multiple one cause a segfault).

I don't know what sikuli is. For testing, I put the player on screen on AI and let the game auto run for 200 rounds or later 400 round and watched were the AI failed. Looks like we need some instructions for testing. For the instabilities, of course the wast amount of code changes could introduce them. But as far as I could see only one commit contributes most to it.

>There are cpp directives like `__MAKESPR__` concerning unit sprites, which made me wonder if the source could be compiled such that a CLI like `makespr` can be build. Do you know if that was tested after the source was released? A CLI would make the creation of new sprites much easier.

We never tested this, because we have the SpriteEdit and TileEdit. Of course, these things are Windows programs and so you would like to have something that works on Linux, not even the command line SpriteTool helps you there, natively.

> I've also noticed that these changes (specifically to `gl_str.txt`) screw up the game messages when a saved game is loaded that was started with an earlier version of ctp2. Do the strings of `gl_str.txt` somehow enter into the save-game-files?

That's normal, the IDs of the strings are saved in the savegame. If you wanna continue on your savegame than open the chat window by typing the apostrophe key and enter: /reloadslic

Probably, I typed it so often, let's see what the Apolyton readme says about it:

"After installation, you can start a new game or continue a game from
a previous version. All you need to do - after loading your save game - is to
open the chat window by typing the apostrophe key (') and enter: /reloadslic
You have to do this procedure once per save game."

Yeah, the key sentence is quite similar.

**Comment by MartinGuehmann** [comment]
OK, I have seen the problem with the text fields.

Anyway, if you add strings to the string databases then add the strings to all language versions. First, having an English string in a Spanish file is better than nothing for instance. And of course it reminds somebody, that there is some work to do and he could then contribute, easily.

And second, because of the index thingy, ideally you could switch from one language to another. Ideally, we would have an interface for that, but for now you can only do it by a text file change. In that case you would like to keep the order of the strings the same so that you don't screw up the strings and have to /reloadslic.

**Comment by LynxAbraxas** [comment]
>... apostrophe key and enter: /reloadslic

Thank @MartinGuehmann for that hint. I had seen that instruction but was not aware that it would apply in this case. Anyway, on Linux this is only possible with #40.

**Comment by LynxAbraxas** [comment]
> I don't know what sikuli is. 

Sikuli (https://github.com/RaiMan/SikuliX1) allows to automate mouse and keyboard interactions. I use it for automated smoke test on GitLab (GL), see e.g. tests in https://github.com/LynxAbraxas/ctp2DF/tree/master/tests which are run by GL-CI (https://github.com/LynxAbraxas/ctp2DF/blob/f4a864acf7b8c25db6ea9a8322664675269dfd04/.gitlab-ci.yml#L84).

> For testing, I put the player on screen on AI and let the game auto run for 200 rounds or later 400 round and watched were the AI failed. 

`/detach 1` for player on screen to AI?
Is there a way to avoid the need to end truns if the AI plays? I was considering to do so in one of the Sikuli tests such that a video is created as (GitLab) artifact instead of just screen shots.

>Looks like we need some instructions for testing. For the instabilities, of course the wast amount of code changes could introduce them. But as far as I could see only one commit contributes most to it.

The instabilities I was referring to above only concern Sikuli acting on ctp2: Sometimes click events sikuli issues are not caught by ctp2. That's why I allow repetition of some GL-CI jobs, like https://github.com/LynxAbraxas/ctp2DF/blob/f4a864acf7b8c25db6ea9a8322664675269dfd04/.gitlab-ci.yml#L88.
Since the automated sprite creation (https://github.com/LynxAbraxas/ctp2DF/blob/f4a864acf7b8c25db6ea9a8322664675269dfd04/bin/buildSprites.sh) from Blender models (https://github.com/LynxAbraxas/sprites) uses Sikuli to iterate over all Blend files with the pattern ###.blend and enters the corresponding numbers in the sprite editor GUI, missed events make [this job](https://github.com/LynxAbraxas/ctp2DF/blob/f4a864acf7b8c25db6ea9a8322664675269dfd04/.gitlab-ci.yml#L213-L251) the most sensitive.

**Comment by LynxAbraxas** [comment]
> Wouldn't it make more sense to have in the long run an import from a blender file directly?

Sure ;-) but I think that is far from trivial and that would have to be contributed by someone else. I'm trying to avoid any further work on the code (the only problem that I might look into still is debugging the randomly occurring crashes apparently connected to (missing) SDL surface locking.) Simpler for sure would be to reactivate the  `__MAKESPR__` code even with additional porting to linux. The sikuli problem only concerns ctp2 interaction, the rendering of appropriate image series with blend neither needs X nor any interaction. 

I only plan on a new tuna sprite and perhaps some other animals for land, depending on what public models I can find that suite the purpose, perhaps a dodo, chicken or horse.
Do the ones I created with the built-in and modified sprite editor work for you under windows?

**Comment by MartinGuehmann** [comment]
> Do the ones I created with the built-in and modified sprite editor work for you under windows?

They do. Actually, I didn't expect anything else, since the sprites show up on Linux. But true, I cannot load my Windows save games on Linux. Conveniently, I just compile the code on the Windows partition and run it from there.

**Comment by LynxAbraxas** [comment]
It seems this branch was merged into master (https://github.com/civctp2/civctp2/commit/60dc0ab72cffc5ab762642bf5d3adfe4fa901289) when it was at https://github.com/civctp2/civctp2/pull/44/commits/00b7b26372ce20faad8d659fc89b21e5ffe83de2. As the PR is still open on GH should it be merged at its current state or should I create a new PR with the remaining commits?

**Comment by MartinGuehmann** [comment]
I merged it on my local working copy and pushed it to the server. But between merging and pushing you added these two commits. That's actual another reason, why the things should be done on GitHub. Actually, I am expecting more commits and therefore it can stay open.

However, it has conflict, I think they could be resolved by merging in the current master and choosing your version of the file in question.

**Comment by LynxAbraxas** [comment]
> Actually, I am expecting more commits and therefore it can stay open.

I'm still working on a optimized walking cycle for the camel, so yes there might be an update, therefore changed to WIP.
I will try to resolve the merge issues without rebasing, as that probably will cause problems with the part of the PR that got already merged, otherwise will open a new PR for the rebased remaining commits.

**Comment by MartinGuehmann** [comment]
I added a label for that. This way, I can see it better and when you hoover over it, you get an explantion what it is about. That's good for newbees, like myself. :D I hope everybody can add and remove these labels. It should be in the column on the right. If you wanna test it you can add one and then remove it again.

**Comment by LynxAbraxas** [comment]
> I hope everybody can add and remove these labels.

No, just those with special status on the project. I think that's the reason for the convention to put `WIP: ` in the title.

**Comment by MartinGuehmann** [comment]
> > I hope everybody can add and remove these labels.
> 
> No, just those with special status on the project. I think that's the reason for the convention to put `WIP: ` in the title.

That's not nice, and makes these labels quite useless.

**Comment by MartinGuehmann** [comment]
Well, I have a new merge conflict, even so I just have added the sdl_blitter.cpp, which shouldn't cause any problem. I guess I will install git on Linux and do what git hub suggests. But first, I have to get back on Linux Windows 10 really wants to fix my hard drives. And still wants to use 10 hours for that. For that I prefer Windows 7, much faster, but just doesn't fix it. 

> Step 1: From your project repository, check out a new branch and test the changes.
> 
> git checkout -b LynxAbraxas-activateAllGoods master
> git pull https://github.com/LynxAbraxas/civctp2.git activateAllGoods
> Step 2: Merge the changes and update on GitHub.
> 
> git checkout master
> git merge --no-ff LynxAbraxas-activateAllGoods
> git push origin master

I guess this creates a local working copy of master merges in your pull request and then pushes it back. I just would like to have it put the commits directly to master, since these branches add more complexity then necessary.

**Comment by LynxAbraxas** [comment]
> I guess I will install git on Linux and do what git hub suggests. 

You can also get git for windows with a tty+bash, you then have git-bash, git-gui and gitk.

> I guess this creates a local working copy of master merges in your pull request and then pushes it back. 

Yes, especially the `--no-ff` makes sure to create a merge commit on top, even if it could be merged by fast-forward. That is intended to distinguish merged PRs from direct commits to master.

> I just would like to have it put the commits directly to master, since these branches add more complexity then necessary.

An advantage of these branches and merge (instead of rebase) is that it preserves the commit sha, while rebasing would change it. If others already built work on that sha, they will not be happy if rebasing was used.

**Comment by MartinGuehmann** [comment]
> > I guess I will install git on Linux and do what git hub suggests.
> 
> You can also get git for windows with a tty+bash, you then have git-bash, git-gui and gitk.

OK, however I must say that apt is much nice for installing things then downloading an installer.

> > I just would like to have it put the commits directly to master, since these branches add more complexity then necessary.
> 
> An advantage of these branches and merge (instead of rebase) is that it preserves the commit sha, while rebasing would change it. If others already built work on that sha, they will not be happy if rebasing was used.

I think I used rebase and merge for the sdl_blitter.cpp. Looks like it already made me unhappy. So than it should be at least for other PRs:

> Create a merge commit
> All this commits from this branch will be added to the base branch via a merge commit.

At least that is what the GitHub GUI says.

**Comment by MartinGuehmann** [comment]
> git push origin master
> fatal: 'origin' does not appear to be a git repository
> fatal: Konnte nicht vom Remote-Repository lesen. (Could not read from remote resposity)

That's what I get with the commands, but now it allows to merge, well then merge.

**Pull request merged**
