### PR TITLE
Make the AI compare the city limit of it current government, when it …

### PR DESCRIPTION
**Pull request by MartinGuehmann**
…is looking for a better government

The AI has a list of governments it will use. If it has too many cities it will look whether it contains a government that allows more cities. If so it will switch to. However, it contained a bug instead comparing the governments from the list to the current government it would compare it to another government in the list. Of course that does not allow the AI to find a better government. But it may also crash the game if the current government's index is higher than the list is long. This is a problem that occurs in the late game with developed AIs.
..\ctp2_code\ai\CityManagement\governor.cpp

Added the database indices of the governments in the comments, that is useful for debugging such as the previous problem.
..\ctp2_data\default\gamedata\govern.txt

If a city bankrupts it does not try to sell building if the maintenance of the remaining buildings is zero, such as the capitol. This actually just fixes an assert in the debug version, and give a little speed, but probably not noticeable.
..\ctp2_code\gs\gameobj\CityData.cpp

Removed some outcommented unused code (by the way commit)
..\ctp2_code\ai\strategy\scheduler\Scheduler.h
..\ctp2_code\ai\strategy\scheduler\scheduler.cpp

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Testing this, seems to be an important PR. 
@MartinGuehmann I would suggest though to split into 3 commits (database change together with the first), possibly even to make 3 PRs of this and to tell in the commit message for the last change why the code is unused and why it was needed before (if possible).

**Comment by MartinGuehmann** [comment]
Those are now #80, #81, and #82.

**Comment by LynxAbraxas** [comment]
Would suggest to close this PR in favour of the other 3.

**Comment by MartinGuehmann** [comment]
So, the the others can go in?

**Comment by LynxAbraxas** [comment]
Yes, no objections from my side.

**Pull request closed without merging**
