### PR TITLE
Splitter civs inherit the age of their parent civ

### PR DESCRIPTION
**Pull request by MartinGuehmann**
So far when a city becomes independent and forms a new civilization it inherits all the advances of its parent civilization. Since the advances define, in which age a civilization is, the age should also be inherited. Otherwise the new civilization is the first age until it discovers a new advance.
..\ctp2_code\gs\gameobj\Civilisation.cpp

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Sounds reasonable.
When does a city becomes independent and form a new civilization? Never saw that happen in the games I played.

**Comment by MartinGuehmann** [comment]
> Sounds reasonable.
> When does a city becomes independent and form a new civilization? Never saw that happen in the games I played.

If you start a new game then you can set the maximum number of players for instance to 20 or 31, then the game adds whenever cities split off, if you have the maximum number of players or more in the game then those cities become Barbarian.

**Comment by LynxAbraxas** [comment]
Tested for some time but not encountered the formation of a new civilization, so cannot say if the disired effect happens. In any case this did not seem to introduce any unwanted effects so I'd say it is good to go in.

**Comment by MartinGuehmann** [comment]
Then this goes in.

**Pull request merged**
