### PR TITLE
Hide unexplored cities for special cursor

### PR DESCRIPTION
**Pull request by williamd67**
It was possible to find cities on unexplored tiles by using an action (cursor) of a special unit.

### CODE REVIEW

**Comment by williamd67** [comment]
I expect that this will solve #111 which describes a scenario where actions (cursors) of special units may show unexplored cities.

**Comment by LynxAbraxas** [comment]
Sounds great! I'll check.

**Comment by LynxAbraxas** [comment]
Yes, I can confirm that this PR solves #111. Many thanks @williamd67 for the fix.
@MartinGuehmann What do you think, ready for merge?

**Comment by MartinGuehmann** [comment]
> Yes, I can confirm that this PR solves #111. Many thanks @williamd67 for the fix.
> @MartinGuehmann What do you think, ready for merge?

Looks good. So we can merge.

**Pull request merged**
