### PR TITLE
Ask if player wants to break a standing trade pact

### PR DESCRIPTION
**Pull request by LynxAbraxas**
In regard to #157, based on #161 (which should be merged first), with this PR a question-message (with a general (so far unused) text from CTP1) is shown that asks if the player wants to break a standing trade pact by pirating a route belonging to the pact partner
ss_2019-07-06_18:32:58

Clicking "yes" executes the pirating which breaks the pact
ss_2019-07-06_18:33:43

A message for the partner about the fact that the pact got broken would be in the scope of #162.

### CODE REVIEW

**Comment by MartinGuehmann** [comment]
I guess that is now also complete.

**Comment by LynxAbraxas** [comment]
Yes, tested for a while and seems to work all right.

**Comment by MartinGuehmann** [comment]
> Yes, tested for a while and seems to work all right.

OK, then let's merge.

**Comment by LynxAbraxas** [comment]
Hm, just observed that the AI seems to have some trouble with this. If it has agreed to a no-piracy agreement, it keeps trying to pirate the route, it gets an invalid-action sign but keeps trying turn after turn.
@MartinGuehmann any idea how to counter act that AI behaviour?

**Comment by MartinGuehmann** [comment]
I guess this has to be handled by Goal::IsInvalidByDiplomacy(), you should be able to find all the pieces of code you need in functions that are called by Goal::IsTotallyComplete().

**Pull request merged**
