### PR TITLE
Army manager look

### PR DESCRIPTION
**Pull request by williamd67**
This pull-request updates the army-manager-dialog look to be consistent with all the other manager-dialogs.

Before:
Screenshot from 2021-06-06 11-46-03

After:
Screenshot from 2021-06-06 12-08-10

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Could not test this so far because I get merge conflicts with the other PRs.

**Comment by williamd67** [comment]
@LynxAbraxas I resolved the conflicts so that this can be tested (when you have some time).

**Comment by MartinGuehmann** [comment]
Looks good, compiles on Windows. I am just not sure about the list, now it shows the names of the armies, which is a good thing. Before, it showed the number of units in the army which was nice. I am just not sure whether this is necessary.

**Comment by LynxAbraxas** [comment]
Thanks @williamd67 for this PR. Works for me and I very much like the bigger size. Do you see a chance to also print the number of units in the army as done in the old version?
@williamd67 BTW: You can delete the branches of merged PRs (unless You intend to keep them). That way it is easier for other who fetch your repo to see which branches/PRs still need testing. That's why I missed testing this PR for some while (sorry about that).

**Comment by williamd67** [comment]
@LynxAbraxas I will have a look if I can re-introduce the number of units in an army. BTW: I deleted my branches.

**Comment by LynxAbraxas** [comment]
That's great! Thanks!
One thing I noticed that is only indirectly related to Your PR here is, that I sometimes get the army manager opened with a double click on a city where as sometimes it is the city manager. So far I could not make out when I get which.

**Comment by williamd67** [comment]
Screenshot from 2022-09-03 10-13-07

**Comment by LynxAbraxas** [comment]
Thanks @williamd67! That's great!
@MartinGuehmann I'd say ready for merging.

**Comment by MartinGuehmann** [comment]
That's good so let's merge.

**Pull request merged**
