### PR TITLE
Trench tiles for CTP2

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR solves #248:
ss_2021-02-08_21:51:47
Also combinations the map generator does not come up with work:
ss_2021-02-08_21:51:04
Still some constellations are not covered even with the fast variety of trench tiles available so far.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
This was made possible by #185, many thanks @MartinGuehmann for recovering those and to their creators of old. Do you see a chance to convince "Martin the Dane"  to contribute the sources of his tools in case the old binaries do not work any more one day? This would also be interesting to be able to solve bugs (like in the export function: 656c8e79f).

**Comment by MartinGuehmann** [comment]
> This was made possible by #185, many thanks @MartinGuehmann for recovering those and to their creators of old. Do you see a chance to convince "Martin the Dane" to contribute the sources of his tools in case the old binaries do not work any more one day? This would also be interesting to be able to solve bugs (like in the export function: [656c8e7](https://github.com/civctp2/civctp2/commit/656c8e79f029b24aa840cdd187017874557a0bf3)).

Well, I could just write to Martin, or you could write to him, his email address should be in the readme file.

Actually, I am not sure whether the binaries still run on Windows 10, for sure what I remember is that they work better with Wine. And thanks to Wine I won't expect them stop working.

**Comment by MartinGuehmann** [comment]
Oh, actually are you happy now with this PR? If yes then I can merge.

**Comment by LynxAbraxas** [comment]
> Oh, actually are you happy now with this PR? If yes then I can merge.

Yes, ready to go in.

**Comment by MartinGuehmann** [comment]
Well, then let's merge.

**Pull request merged**
