### PR TITLE
Pirate also the bonus given to a trade route destination

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR solves #192:
ss_2020-01-16_21:04:35
ss_2020-01-16_21:05:22

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
So what is left is to decide if the pirating civ should get the bonus. If so, how to determine which city should get it?
@MartinGuehmann Is it possible to determine the city that built one of the pirating units?

**Comment by MartinGuehmann** [comment]
> So what is left is to decide if the pirating civ should get the bonus. If so, how to determine which city should get it?

Which city is easy: Just the closest.

> @MartinGuehmann Is it possible to determine the city that built one of the pirating units?

This is actually a Civ2, where the city had to pay shields for its units. I doubt that this is saved in CTP2. However, if it were saved, then you should find it in the UnitData object, it should be the unit parent city ID or something like that. But there is nothing like this.

**Comment by LynxAbraxas** [comment]
> Which city is easy: Just the closest.

True, I like that idea. Probably the code that determines where to send a unit (expell, enslaving) could be used (reduced by the check if the destination can hold another army/unit).
However, after investigating this a bit, I wonder how to pass the captured bonus to the closest city. Currently I can only think of storing this in a variable of `CityData` which then gets read when calculating food, prod. and gold during turn transition, but that would need to be saved in a save-game, since there we cannot use the `m_tradeDestinationList` or similar because the city itself is in general not involved in the trade route connection.

**Comment by LynxAbraxas** [comment]
> how to pass the captured bonus to the closest city.

@MartinGuehmann Any ideas on realizing this without the need for another slot in the save-game format?

**Comment by MartinGuehmann** [comment]
> > how to pass the captured bonus to the closest city.
> 
> @MartinGuehmann Any ideas on realizing this without the need for another slot in the save-game format?

I think you have to save it, otherwise it gets messed up after a reload. And looping through all the trade routes of all players checking whether they are pirated and then figuring out what the nearest city is, is just brute force and would really get horrible with more trade routes and cities.

So m_buildInfrastructure and m_buildCapitalization are not used and are stored as BOOL in the save game, which gives you two sint32. Unfortunately these things are 32 bits so your new variables should be 32 bits, too. So now you have space for food and production, now you just need gold. Also m_terrainWasPolluted seems to be unused, and what the point of m_terrainImprovementWasBuilt and m_improvementWasBuilt is I don't know. Maybe these are not used, either.

**Comment by LynxAbraxas** [comment]
Thanks for all these pointers, I'll give it  a try with those.

**Comment by LynxAbraxas** [comment]
I'd say that passing the pirated bonus to the nearest city should be a PR on its own, created #257 to track that.
@MartinGuehmann What do you think? Ready for merge?

**Comment by MartinGuehmann** [comment]
Then let's merge.

**Pull request merged**
