### PR TITLE
Debug Alex and Nuke scenario loading on Linux

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR investigates and debugs the loading of the Alex and Nuke scenario on Linux and is based on #295.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
With 96b92420273ed3e7c6e20b230d08c8180ab853e0 and running ctp2 with
```
~/ctp2/run.sh --security-opt seccomp=unconfined -v ~/ctp2/debug/gdb.cmds:/opt/ctp2/ctp2_program/ctp/gdb.cmds -v ~/ctp2/:/ctp2/ -ti registry.gitlab.com/lynxabraxas/civctp2/dbgalex:test-debug gdb -quiet -batch -x /opt/ctp2/ctp2_program/ctp/gdb.cmds --args ./ctp2 nointromovie
```
and choosing the Alex scenario, gdb catches this SIGILL:
```
Thread 1 "ctp2" hit Catchpoint 3 (signal SIGILL), SlicModFunc::SlicModFunc (this=0x5555605b06cc, name=0x555556864ee1 "mod_CanPlayerHaveAdvance") at SlicModFunction.cpp:21
21			tag = va_arg(vl, SLIC_TAG);
#0  SlicModFunc::SlicModFunc (this=0x5555605b06cc, name=0x555556864ee1 "mod_CanPlayerHaveAdvance") at SlicModFunction.cpp:21
#1  0x00005555566159c9 in SlicEngine::AddModFuncs (this=0x55555e2e554c) at SlicEngine.cpp:3069
#2  0x0000555556604f29 in SlicEngine::PostSerialize (this=0x55555e2e554c) at SlicEngine.cpp:457
#3  0x00005555566a4f0d in gameinit_Initialize (mWidth=-1, mHeight=-1, archive=...) at gameinit.cpp:1683
#4  0x0000555555b82af5 in CivApp::InitializeGame (this=0x5555570b4bdc, archive=...) at ctp/civapp.cpp:1717
#5  0x00005555563cd57c in GameFile::Restore (this=0x7fffffffe9e7, filepath=0x55555e917104 "/opt/ctp2/Scenarios/AlexanderTheGreat/scen0000/savegame.c2g") at GameFile.cpp:848
#6  0x00005555563cb4ca in GameFile::RestoreGame (name=0x55555e917104 "/opt/ctp2/Scenarios/AlexanderTheGreat/scen0000/savegame.c2g") at GameFile.cpp:186
#7  0x0000555555b856b6 in CivApp::LoadSavedGame (this=0x5555570b4bdc, name=0x55555e917104 "/opt/ctp2/Scenarios/AlexanderTheGreat/scen0000/savegame.c2g") at ctp/civapp.cpp:2651
#8  0x0000555555b862de in LoadSaveGameAction::Execute (this=0x55555e9170fc, control=0x0, action=0, data=0) at ctp/civapp.cpp:2931
#9  0x0000555555c4b232 in aui_UI::HandleActions (this=0x555557c7932c) at ui/aui_common/aui_ui.cpp:1862
#10 0x0000555555c4b188 in aui_UI::Process (this=0x555557c7932c) at ui/aui_common/aui_ui.cpp:1847
#11 0x0000555555b84e02 in CivApp::ProcessUI (this=0x5555570b4bdc, target_milliseconds=30, used_milliseconds=@0x7fffffffeb1c: 0) at ctp/civapp.cpp:2395
#12 0x0000555555b852a8 in CivApp::Process (this=0x5555570b4bdc) at ctp/civapp.cpp:2548
#13 0x0000555555b7b2cc in CivMain (iCmdShow=2, pSzCmdLine=0x7fffffffecc8) at ctp/civ3_main.cpp:1694
#14 0x0000555555b7ae69 in main (argc=2, argv=0x7fffffffecc8) at ctp/civ3_main.cpp:1440
```
and this SIGILL when loading the Nuke scenario:
```
Thread 1 "ctp2" hit Catchpoint 3 (signal SIGILL), SlicModFunc::SlicModFunc (this=0x55555fc0500c, name=0x555556864f0f "mod_CanCityBuildBuilding") at SlicModFunction.cpp:21
21			tag = va_arg(vl, SLIC_TAG);
#0  SlicModFunc::SlicModFunc (this=0x55555fc0500c, name=0x555556864f0f "mod_CanCityBuildBuilding") at SlicModFunction.cpp:21
#1  0x0000555556615a3b in SlicEngine::AddModFuncs (this=0x55555e2e4f8c) at SlicEngine.cpp:3071
#2  0x000055555660ca24 in SlicEngine::Link (this=0x55555e2e4f8c) at SlicEngine.cpp:1012
#3  0x0000555556604899 in SlicEngine::Reload (a_File="script.slc") at SlicEngine.cpp:363
#4  0x0000555555b82c39 in CivApp::InitializeGame (this=0x5555570b4bdc, archive=...) at ctp/civapp.cpp:1737
#5  0x00005555563cd57c in GameFile::Restore (this=0x7fffffffe9e7, filepath=0x55555eab82f4 "/opt/ctp2/Scenarios/NuclearDetente/scen0000/savegame.c2g") at GameFile.cpp:848
#6  0x00005555563cb4ca in GameFile::RestoreGame (name=0x55555eab82f4 "/opt/ctp2/Scenarios/NuclearDetente/scen0000/savegame.c2g") at GameFile.cpp:186
#7  0x0000555555b856b6 in CivApp::LoadSavedGame (this=0x5555570b4bdc, name=0x55555eab82f4 "/opt/ctp2/Scenarios/NuclearDetente/scen0000/savegame.c2g") at ctp/civapp.cpp:2651
#8  0x0000555555b862de in LoadSaveGameAction::Execute (this=0x55555eab82ec, control=0x0, action=0, data=0) at ctp/civapp.cpp:2931
#9  0x0000555555c4b232 in aui_UI::HandleActions (this=0x555557c790cc) at ui/aui_common/aui_ui.cpp:1862
#10 0x0000555555c4b188 in aui_UI::Process (this=0x555557c790cc) at ui/aui_common/aui_ui.cpp:1847
#11 0x0000555555b84e02 in CivApp::ProcessUI (this=0x5555570b4bdc, target_milliseconds=30, used_milliseconds=@0x7fffffffeb1c: 0) at ctp/civapp.cpp:2395
#12 0x0000555555b852a8 in CivApp::Process (this=0x5555570b4bdc) at ctp/civapp.cpp:2548
#13 0x0000555555b7b2cc in CivMain (iCmdShow=2, pSzCmdLine=0x7fffffffecc8) at ctp/civ3_main.cpp:1694
#14 0x0000555555b7ae69 in main (argc=2, argv=0x7fffffffecc8) at ctp/civ3_main.cpp:1440
```
both leading to
https://github.com/civctp2/civctp2/blob/99e74c4dfb7a4af6ece4412296e0b2cc20cc9af0/ctp2_code/gs/slic/SlicModFunction.cpp#L21
removing/commenting
https://github.com/civctp2/civctp2/blob/99e74c4dfb7a4af6ece4412296e0b2cc20cc9af0/Scenarios/NuclearDetente/scen0000/default/gamedata/ND_mod.slc#L8-L15
for testing then allows me to load the Nuke scenario:
ss_2020-05-20_12:50:20
There is the Rubies trade route problem:
ss_2020-05-20_12:59:30
but new routes can be created all fine even by the AI:
ss_2020-05-20_13:06:51
ss_2020-05-20_13:09:22
even #256 works (but needs a unit move to update the trade route state)
ss_2020-05-20_13:10:08
However, unloading a nuke does not
ss_2020-05-20_13:13:11
which might be a general problem (even under windows) that came with some additions. @MartinGuehmann can you test this on windows?

**Comment by LynxAbraxas** [comment]
> However, unloading a nuke does not
which might be a general problem (even under windows) that came with some additions. 

Ah, all fine, it is one of the special scenario rules

**Comment by LynxAbraxas** [comment]
Before the SIGILL there are many
```
Assertion (start < m_code + m_codeSize) Failed in File:SlicSegment.cpp, Line:649

Thread 1 "ctp2" hit Catchpoint 2 (signal SIGINT), 0x00007ffff4f2e727 in raise () from /lib/x86_64-linux-gnu/libpthread.so.0
#0  0x00007ffff4f2e727 in raise () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000555555b254a4 in c3debug_Assert (s=0x5555563502c0 "start < m_code + m_codeSize", file=0x5555563501e0 "SlicSegment.cpp", line=649) at ctp/ctp2_utils/c3debug.cpp:326
#2  0x0000555556210fd6 in SlicSegment::FindNextLine (this=0x55555dc0a348, start=0x55555f2d69e4 "") at SlicSegment.cpp:649
#3  0x0000555556211103 in SlicSegment::GetSourceLines (this=0x55555dc0a348, firstLineNum=@0x55555dc0a3fc: 50, firstLineOffset=@0x7fffffff8dc0: -1, lastLineNum=@0x7fffffff8dc4: -1) at SlicSegment.cpp:743
#4  0x0000555556210d87 in SlicSegment::GetDescription (this=0x55555dc0a348, str=0x7fffffff8e30 "@@UUUU", maxsize=1024) at SlicSegment.cpp:602
#5  0x0000555555f59f30 in GameEventHook::AddCallback (this=0x55555ed33940, cb=0x55555dc0a348, pri=GEV_PRI_Pre) at GameEventHook.cpp:150
#6  0x0000555555f57617 in GameEventManager::AddCallback (this=0x5555570233b0, type=GEV_Counter, pri=GEV_PRI_Pre, cb=0x55555dc0a348) at GameEventManager.cpp:481
#7  0x00005555562107bb in SlicSegment::Serialize (this=0x55555dc0a348, archive=...) at SlicSegment.cpp:480
#8  0x000055555620fde6 in SlicSegment::SlicSegment (this=0x55555dc0a348, archive=...) at SlicSegment.cpp:262
#9  0x00005555561b4e51 in StringHashNode<SlicSegment>::Serialize (this=0x55555da9a2e0, archive=...) at StringHash.h:79
#10 0x00005555561b4fe2 in StringHashNode<SlicSegment>::StringHashNode (this=0x55555da9a2e0, archive=...) at StringHash.h:56
#11 0x00005555561b1a03 in StringHash<SlicSegment>::Serialize (this=0x55555db21910, archive=...) at StringHash.h:179
#12 0x0000555556199863 in SlicEngine::Serialize (this=0x55555d9aaa70, archive=...) at SlicEngine.cpp:379
#13 0x00005555561991a4 in SlicEngine::SlicEngine (this=0x55555d9aaa70, archive=...) at SlicEngine.cpp:265
#14 0x0000555556239e35 in gameinit_Initialize (mWidth=-1, mHeight=-1, archive=0x7fffffff97b0) at gameinit.cpp:1682
#15 0x0000555555b36ed5 in CivApp::InitializeGame (this=0x5555567a86f0, archive=0x7fffffff97b0) at ctp/civapp.cpp:1719
#16 0x0000555555f624ba in GameFile::Restore (this=0x7fffffffe9d7, filepath=0x55555e2b8b08 "/opt/ctp2/Scenarios/NuclearDetente/scen0000/savegame.c2g") at GameFile.cpp:848
#17 0x0000555555f60408 in GameFile::RestoreGame (name=0x55555e2b8b08 "/opt/ctp2/Scenarios/NuclearDetente/scen0000/savegame.c2g") at GameFile.cpp:186
#18 0x0000555555b39a9c in CivApp::LoadSavedGame (this=0x5555567a86f0, name=0x55555e2b8b08 "/opt/ctp2/Scenarios/NuclearDetente/scen0000/savegame.c2g") at ctp/civapp.cpp:2652
#19 0x0000555555b3a6c4 in LoadSaveGameAction::Execute (this=0x55555e2b8b00, control=0x0, action=0, data=0) at ctp/civapp.cpp:2932
#20 0x0000555555bfc794 in aui_UI::HandleActions (this=0x555557313d50) at ui/aui_common/aui_ui.cpp:1843
#21 0x0000555555bfc6ea in aui_UI::Process (this=0x555557313d50) at ui/aui_common/aui_ui.cpp:1828
#22 0x0000555555b391e8 in CivApp::ProcessUI (this=0x5555567a86f0, target_milliseconds=30, used_milliseconds=@0x7fffffffeb0c: 0) at ctp/civapp.cpp:2396
#23 0x0000555555b3968e in CivApp::Process (this=0x5555567a86f0) at ctp/civapp.cpp:2549
#24 0x0000555555b2f0be in CivMain (iCmdShow=2, pSzCmdLine=0x7fffffffece8) at ctp/civ3_main.cpp:1678
#25 0x0000555555b2ec61 in main (argc=2, argv=0x7fffffffece8) at ctp/civ3_main.cpp:1430
```
which makes me wonder if the SIGILL could be related to windows EOLs interpreted differently in the Linux version, causing
https://github.com/civctp2/civctp2/blob/99e74c4dfb7a4af6ece4412296e0b2cc20cc9af0/ctp2_code/gs/slic/SlicSegment.cpp#L645-L653
to return `NULL` where it should not.

**Comment by LynxAbraxas** [comment]
From this SO:
https://stackoverflow.com/questions/18410344/program-received-signal-sigill-illegal-instruction
I came to
https://peeterjoot.wordpress.com/2010/05/26/a-fun-and-curious-dig-gcc-generation-of-a-ud2a-instruction-sigill/
which is relating SIGILL to *variable argument lists* which would fit to
https://github.com/civctp2/civctp2/blob/99e74c4dfb7a4af6ece4412296e0b2cc20cc9af0/ctp2_code/gs/slic/SlicModFunction.cpp#L21
but so far I am not sure how.

**Comment by LynxAbraxas** [comment]
With b493c5abeb3763afeb892992f512c442e113709f and
```
~/ctp2/run.sh --security-opt seccomp=unconfined -v ~/ctp2/debug/gdb.cmds:/opt/ctp2/ctp2_program/ctp/gdb.cmds -v ~/ctp2/:/ctp2/ -ti registry.gitlab.com/lynxabraxas/civctp2/dbgalex:test-debug gdb -quiet -batch -x /opt/ctp2/ctp2_program/ctp/gdb.cmds --args ./ctp2 nointromovie noassertdialogs
```
getting `ud2` instruction (“guaranteed invalid instruction”):

```
Thread 1 "ctp2" hit Catchpoint 3 (signal SIGILL), SlicModFunc::SlicModFunc (this=0x55555f42d520, name=0x555556349caf "mod_CanCityBuildBuilding") at SlicModFunction.cpp:21
21			tag = va_arg(vl, SLIC_TAG);
=> 0x55555620bf0f <SlicModFunc::SlicModFunc(char const*, ...)+249>:	ud2    
Dump of assembler code for function SlicModFunc::SlicModFunc(char const*, ...):
   0x000055555620be16 <+0>:	push   %rbp
   0x000055555620be17 <+1>:	mov    %rsp,%rbp
   0x000055555620be1a <+4>:	sub    $0xf0,%rsp
   0x000055555620be21 <+11>:	mov    %rdi,-0xe8(%rbp)
   0x000055555620be28 <+18>:	mov    %rsi,-0xf0(%rbp)
   0x000055555620be2f <+25>:	mov    %rdx,-0xa0(%rbp)
   0x000055555620be36 <+32>:	mov    %rcx,-0x98(%rbp)
   0x000055555620be3d <+39>:	mov    %r8,-0x90(%rbp)
   0x000055555620be44 <+46>:	mov    %r9,-0x88(%rbp)
   0x000055555620be4b <+53>:	test   %al,%al
   0x000055555620be4d <+55>:	je     0x55555620be6f <SlicModFunc::SlicModFunc(char const*, ...)+89>
   0x000055555620be4f <+57>:	movaps %xmm0,-0x80(%rbp)
   0x000055555620be53 <+61>:	movaps %xmm1,-0x70(%rbp)
   0x000055555620be57 <+65>:	movaps %xmm2,-0x60(%rbp)
   0x000055555620be5b <+69>:	movaps %xmm3,-0x50(%rbp)
   0x000055555620be5f <+73>:	movaps %xmm4,-0x40(%rbp)
   0x000055555620be63 <+77>:	movaps %xmm5,-0x30(%rbp)
   0x000055555620be67 <+81>:	movaps %xmm6,-0x20(%rbp)
   0x000055555620be6b <+85>:	movaps %xmm7,-0x10(%rbp)
   0x000055555620be6f <+89>:	mov    %fs:0x28,%rax
   0x000055555620be78 <+98>:	mov    %rax,-0xb8(%rbp)
   0x000055555620be7f <+105>:	xor    %eax,%eax
   0x000055555620be81 <+107>:	mov    -0xe8(%rbp),%rax
   0x000055555620be88 <+114>:	movl   $0x0,0x28(%rax)
   0x000055555620be8f <+121>:	mov    0x4ab00a(%rip),%rax        # 0x5555566b6ea0 <g_slicEngine>
   0x000055555620be96 <+128>:	mov    -0xf0(%rbp),%rdx
   0x000055555620be9d <+135>:	mov    %rdx,%rsi
   0x000055555620bea0 <+138>:	mov    %rax,%rdi
   0x000055555620bea3 <+141>:	callq  0x555556199e6a <SlicEngine::GetSegment(char const*)>
   0x000055555620bea8 <+146>:	mov    %rax,%rdx
   0x000055555620beab <+149>:	mov    -0xe8(%rbp),%rax
   0x000055555620beb2 <+156>:	mov    %rdx,0x20(%rax)
   0x000055555620beb6 <+160>:	mov    -0xe8(%rbp),%rax
   0x000055555620bebd <+167>:	mov    0x20(%rax),%rax
   0x000055555620bec1 <+171>:	test   %rax,%rax
   0x000055555620bec4 <+174>:	je     0x55555620bf11 <SlicModFunc::SlicModFunc(char const*, ...)+251>
   0x000055555620bec6 <+176>:	movl   $0x10,-0xd0(%rbp)
   0x000055555620bed0 <+186>:	movl   $0x30,-0xcc(%rbp)
   0x000055555620beda <+196>:	lea    0x10(%rbp),%rax
   0x000055555620bede <+200>:	mov    %rax,-0xc8(%rbp)
   0x000055555620bee5 <+207>:	lea    -0xb0(%rbp),%rax
   0x000055555620beec <+214>:	mov    %rax,-0xc0(%rbp)
   0x000055555620bef3 <+221>:	movb   $0x0,-0xd2(%rbp)
   0x000055555620befa <+228>:	movb   $0x0,-0xd1(%rbp)
   0x000055555620bf01 <+235>:	mov    -0xe8(%rbp),%rax
   0x000055555620bf08 <+242>:	movl   $0x0,0x28(%rax)
=> 0x000055555620bf0f <+249>:	ud2    
   0x000055555620bf11 <+251>:	nop
   0x000055555620bf12 <+252>:	mov    -0xb8(%rbp),%rax
   0x000055555620bf19 <+259>:	xor    %fs:0x28,%rax
   0x000055555620bf22 <+268>:	je     0x55555620bf29 <SlicModFunc::SlicModFunc(char const*, ...)+275>
   0x000055555620bf24 <+270>:	callq  0x555555b13df0 <__stack_chk_fail@plt>
   0x000055555620bf29 <+275>:	leaveq 
   0x000055555620bf2a <+276>:	retq   
End of assembler dump.
```

**Comment by LynxAbraxas** [comment]
With https://github.com/civctp2/civctp2/pull/312/commits/3709bb851b5d5259c9d4c4ed595337399ac1c95d `m_numArgs`: 0, so the SIGILL happens on the first argument.

**Comment by LynxAbraxas** [comment]
If I understand https://peeterjoot.wordpress.com/2010/05/26/a-fun-and-curious-dig-gcc-generation-of-a-ud2a-instruction-sigill/ correctly, the SIGILL is generated where the type of the passed argument does not fit the expected type specified in `va_arg`, so translated to the problem here, that would mean that 
https://github.com/civctp2/civctp2/blob/99e74c4dfb7a4af6ece4412296e0b2cc20cc9af0/ctp2_code/gs/slic/SlicModFunction.cpp#L21
expects a `SLIC_TAG` type but would be given something differently.
@MartinGuehmann can you see any reason why that should happen with the current code calling the function
https://github.com/civctp2/civctp2/blob/53d5841a08200037090a2aa316925b505c611dc7/ctp2_code/gs/slic/SlicEngine.cpp#L3058-L3078
?

**Comment by LynxAbraxas** [comment]
Also with gcc-7 compilation works but same SIGILL, still I do not get a warning or similar containing something like `call will abort at runtime`.

**Comment by MartinGuehmann** [comment]
> Also with gcc-7 compilation works but same SIGILL, still I do not get a warning or similar containing something like `call will abort at runtime`.

Well, didn't we silenced most of the warnings, just to get it it compile. Looks like we have to look again into that issue.

**Comment by MartinGuehmann** [comment]
> https://github.com/civctp2/civctp2/blob/99e74c4dfb7a4af6ece4412296e0b2cc20cc9af0/ctp2_code/gs/slic/SlicModFunction.cpp#L21

When I hovered over with the mouse in KDevelop it gave me:

`warning: second argument to 'va_arg' is of promotable type 'SLIC_TAG'; this va_arg has undefined behavior because arguments will be promoted to 'int' [-    Wvarargs]
`

So I found this: https://stackoverflow.com/questions/28054194/char-type-in-va-arg

So the arguments you pass must at least be of size int, that means 32 bit. With Visual Studio enums are 32 bits, so it is not a problem there, however for gcc enums are 8 bit if it is possible: https://embedded.fm/blog/2016/6/28/how-big-is-an-enum

So, I changed the line to this, which also moves the declaration of `tag`:

`SLIC_TAG tag = static_cast<SLIC_TAG>(va_arg(vl, sint32));`

With that the scenarios load. I still get the SlicSegment::FindNextLine asserts and three about a trader being killed.

And there are quite some memory leaks created when you start a new game. These could be real or the memory is not freed before the leaks reporter shuts down. But this is another issue.

**Comment by LynxAbraxas** [comment]
> So, I changed the line to this, which also moves the declaration of tag:
> SLIC_TAG tag = static_cast<SLIC_TAG>(va_arg(vl, sint32));

Yes, that did the trick. Many thanks @MartinGuehmann for that hint and the debug. It made me realize that there was still a `-w` in the DF from the very first commit, where it was needed due to the overlarge log file at that time. Without `-w` gcc gives me the same hint as KDevelop.

> With that the scenarios load. I still get the SlicSegment::FindNextLine asserts and three about a trader being killed.

Yes, loading also works for me now, will see what I can do about the other asserts.

**Comment by LynxAbraxas** [comment]
I am getting
```
Assertion (m_traderUnits->Num() > 0) Failed in File:Player.cpp, Line:3246
```
only for the nuke scenario.
It seems ctp2 currently keeps an array of trade units `m_traderUnits`
https://github.com/civctp2/civctp2/blob/5126ccd304b89f94d71f45b142728542131255e4/ctp2_code/gs/gameobj/Player.cpp#L3481-L3485
as well as the number of transport points these yield `m_tradeTransportPoints` and in addition the number of used transport points (for standing trade routes) `m_usedTradeTransportPoints`
https://github.com/civctp2/civctp2/blob/5126ccd304b89f94d71f45b142728542131255e4/ctp2_code/gs/gameobj/Player.cpp#L3135-L3179

In the nuke scenario, the Vendikar seem to declare war during the inital loading of the scenario. This leads to cancellation of all trade (similar to an embargo) and the cancellation of trade routes results in the loss of a trade unit
https://github.com/civctp2/civctp2/blob/5126ccd304b89f94d71f45b142728542131255e4/ctp2_code/gs/gameobj/Player.cpp#L3188
and that removes transport points
https://github.com/civctp2/civctp2/blob/5126ccd304b89f94d71f45b142728542131255e4/ctp2_code/gs/gameobj/Player.cpp#L1269
It could be that the declaration of war happens before `m_traderUnits` is filled during the loading of the scenario. Otherwise there is an inconsitency: Either there need to be sufficient `m_traderUnits` to realize the current trade route transport or there should be no trade routes.
I wonder, if the declaration of war during loading is meant to happen. If war always lead to cancellation of all trade routes, the scenario should have been set up to have no trade routes between the Vendikar and to be already in the state "at war". So possibly some modification of the game leads to the declaration of war now.
@MartinGuehmann  can you test how the original ctp2 behaves when loading the scenario? Or how it behaves with the current ctp2 under windows?

Another possible source for the problem: It seems a scenario is bound to a save-game or map file like `Scenarios/NuclearDetente/scen0000/savegame.c2g` i.e. the state of the game is not fully constructed by mod-files like
https://github.com/civctp2/civctp2/blob/5126ccd304b89f94d71f45b142728542131255e4/Scenarios/NuclearDetente/scen0000/default/gamedata/ND_mod.slc#L2-L15
Since the save-game file matters, it might need a conversion to the current format.

**Comment by MartinGuehmann** [comment]
> In the nuke scenario, the Vendikar seem to declare war during the inital loading of the scenario. This leads to cancellation of all trade (similar to an embargo) and the cancellation of trade routes results in the loss of a trade unit

And I don't get a message about this, at least on Windows.

> and that removes transport points

It doesn't, because those are removed when the trade units are being killed. And in the scenario there are just no trade units.

> It could be that the declaration of war happens before `m_traderUnits` is filled during the loading of the scenario. Otherwise there is an inconsitency: Either there need to be sufficient `m_traderUnits` to realize the current trade route transport or there should be no trade routes.

No, war is declared afterwards `m_traderUnits` has been loaded, it is just empty for some reason. Actually, it contains one trade units, which is deleted with the first trade route. It is like somebody set the number of trade points to 50 for caravans, put one onto the map, saved the scenario, set back the value in unit.txt and then continued. At least this would explain the discrepancy. 

> I wonder, if the declaration of war during loading is meant to happen. If war always lead to cancellation of all trade routes, the scenario should have been set up to have no trade routes between the Vendikar and to be already in the state "at war". So possibly some modification of the game leads to the declaration of war now.

The Vendikari threatened the Emeniari with war, they just follow through. It seems to be deliberate to annoy the player on turn 0. Even so you can just ask the Vendikari for a cease fire on the same turn and they agree.

> @MartinGuehmann can you test how the original ctp2 behaves when loading the scenario? Or how it behaves with the current ctp2 under windows?

For the original game I need a CD, but I neither have it here nor have CD drive here. For the other thing you can also the trade related asserts on Windows but not the others.

> Since the save-game file matters, it might need a conversion to the current format.

No that has nothing to do with the save game format. If it were related then the game would just crash. It just a problem with the data itself.

However, you could also get in trouble with regular trade units for instance if you trade routes that require two trade points but you traders give you three. So you have two trade units giving you each three trade points. You create three routes, then you delete them. Then the last route should actually also be deleted with the second route, since you have no trade points anymore.

It is quite difficult to decide what to do here, since the save game wasn't created in the correct way. The problem is that the save game does not behave correctly, because you don't lose trade points when you disband trade routes.

**Comment by LynxAbraxas** [comment]
> For the other thing you can also the trade related asserts on Windows but not the others.

Well, then this is a general issue of the scenario, not in particular related to Linux, and should be an issue of its own.

> set back the value in unit.txt 

Where/how is that done? 
Could we use that mechanism to increase the number of trade units? 
Or prevent the declaration of war (which still does not seem right to me, considering that some trade routes were set up for the scenario)?

> Then the last route should actually also be deleted with the second route, since you have no trade points anymore.

That is how it should work with the current implementation. Modifying that should be a PR on its own as well.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann what do you think? Ready for merging? Do you want to merge your #295 first?

**Comment by MartinGuehmann** [comment]
> > For the other thing you can also the trade related asserts on Windows but not the others.
> 
> Well, then this is a general issue of the scenario, not in particular related to Linux, and should be an issue of its own.
> 
> > set back the value in unit.txt
> 
> Where/how is that done?

You take a text editor, edit unit.txt then start the game add a caravan that with your value now give 50 trade points, save the scenario, undo your change in unit.txt and may load the scenario again for more changes. So quite simple, but still much more complicated than klicking 50 times.

> Could we use that mechanism to increase the number of trade units?

How? You could modify unit.txt so that a caravan gives you 50 trade points. So then you wouldn't have the assert, but 50 trade points from one caravan is a bit ridiculous.

> Or prevent the declaration of war (which still does not seem right to me, considering that some trade routes were set up for the scenario)?
 
> > Then the last route should actually also be deleted with the second route, since you have no trade points anymore.
> 
> That is how it should work with the current implementation. Modifying that should be a PR on its own as well.

Well, if it works like this then we are fine.

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann what do you think? Ready for merging?

What is up with the others asserts? Those do not occur on Windows.

> Do you want to merge your #295 first?

I think it would be merged automatically, if I merge this, as long as the SHAs are identical, which might not be the case since both PRs were rebased several times. However, I don't mind about this.

**Comment by LynxAbraxas** [comment]
> What is up with the others asserts? Those do not occur on Windows.

Not sure. I only get these in addition:
```
Assertion (start < m_code + m_codeSize) Failed in File:SlicSegment.cpp, Line:649
```
Could imagine that to be a CRLF problem, but not for sure.

> I think it would be merged automatically, if I merge this, as long as the SHAs are identical, which might not be the case since both PRs were rebased several times. 

I'll do another rebase to resolve the conflicts and will try to find the source for the asserts but I will soon have to say good bye at least for the time being.

**Comment by LynxAbraxas** [comment]
> > What is up with the others asserts? Those do not occur on Windows.
> 
> Not sure. I only get these in addition:
> 
> ```
> Assertion (start < m_code + m_codeSize) Failed in File:SlicSegment.cpp, Line:649
> ```
> 
> Could imagine that to be a CRLF problem, but not for sure.
> 
> > I think it would be merged automatically, if I merge this, as long as the SHAs are identical, which might not be the case since both PRs were rebased several times.
> 
> I'll do another rebase to resolve the conflicts and will try to find the source for the asserts but I will soon have to say good bye at least for the time being.

After rebasing on master (30c7d18ec) the assertion 

 ```
 Assertion (start < m_code + m_codeSize) Failed in File:SlicSegment.cpp, Line:649
 ```
is gone, which I think is due to e8881e400d1ee97d710af4777005f407c3a5e696.

So tested starting all scenarios again, an now I only get
```
Messagebox(Slic Error): In object AGCenterOnAlexander_F, function _SelectUnit: Wrong type of argument
```
which leads to
https://github.com/civctp2/civctp2/blob/30c7d18ecdc2fa7d00e39d40f26b8d6255ff2ea7/Scenarios/AlexanderTheGreat/scen0000/default/gamedata/scenario.slc#L613-L627
despite the comment that it does not work, the map is centered on Alexander if I load the scenario. Should we just out-comment those lines?

**Comment by LynxAbraxas** [comment]
> Should we just out-comment those lines?

Instead of out-commenting, solved with 1b7ff9a9f5bf6c0af8ef55e3dd765106fd3a7818, map centered on Alexander but the unit selection changes quickly afterwards to a Hoplite:
ss_2020-06-27_20:22:28

**Comment by LynxAbraxas** [comment]
Work on 1b7ff9a9f5bf6c0af8ef55e3dd765106fd3a7818 made me wonder how/where scenario variables like `turnCount`
https://github.com/civctp2/civctp2/blob/30c7d18ecdc2fa7d00e39d40f26b8d6255ff2ea7/Scenarios/MagnificentSamurai/scen0000/default/gamedata/SS_func.slc#L18
are initialized. It seems they are expected to be initialized to `0`
https://github.com/civctp2/civctp2/blob/30c7d18ecdc2fa7d00e39d40f26b8d6255ff2ea7/Scenarios/MagnificentSamurai/scen0000/default/gamedata/scenario.slc#L68-L70
which might not be the case.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann  what do you think? Ready for merging?

**Comment by LynxAbraxas** [comment]
@MartinGuehmann any thing left to do or ready for merging?

**Comment by MartinGuehmann** [comment]
I am still not happy about the assert that went, presumably with the line endings. In fact you did not fix it, and even if it is something with the line endings I could imagine some side effect on Windows. However, I would expect that it shouldn't be to complicated.

You may still do it, or not. If you don't then I'll merge this and pick up that issue.

**Comment by LynxAbraxas** [comment]
I'm sorry, I don't get those asserts any more and I can't test windows, but since git there makes sure that the line endings are CRLF, nothing should be different. The only change I expect from git handeling the line ending is on Linux, where this CRLF are regarded as two characters. The new line handling also removed the box-character (CR) that used to be visible after scenario strings. Anyway I won't have the time to investigate this any further, so just merge as you see fit.

**Comment by MartinGuehmann** [comment]
What the line endings on Windows are still CRLF. I thought they are now LF, whatever the operating system is. My working copy is on a NTFS partition, so that it can be accessed from Windows and Linux. And this way, I don't want to care about line endings. Anyway, in .gitattributes the text files are treated as the source files. So only LF for all files independent of the operating system.

Well, here is the rule for parsing new lines:
https://github.com/civctp2/civctp2/blob/4778e5cf0a0c18f55508088d76f7efdc52332293/ctp2_code/gs/slic/slic.l#L205-L208

There are a few more new line handlings, but they are dealt in the same way. And basically, the game shouldn't act any differently on the kind of new lines.

So, let's merge this.

**Comment by LynxAbraxas** [comment]
> What the line endings on Windows are still CRLF. I thought they are now LF, whatever the operating system is. My working copy is on a NTFS partition, so that it can be accessed from Windows and Linux.

Hm, I'm not absolutely sure about that situation, but my current understanding is, that git chooses CRLF for EOL when checking out on windows and LF on linux. If it is on NTFS, git might adjust it depending on whether it accesses the files from linux or windows, I'm not sure if it does so on the fly or if it needs a run similar to `git add --renormalize`.

**Pull request merged**
