### PR TITLE
Migrate to sdl2

### PR DESCRIPTION
**Pull request by williamd67**

### CODE REVIEW

**Comment by williamd67** [comment]
Sorry I did not want to merge this into master. I wanted to merge master into Migrate to sdl2 branch so it stays up to date. If possible you may delete this pull-request.

**Comment by LynxAbraxas** [comment]
@williamd67 it's great you try to tackle this. It would be a great contribution. This PR makes me wonder though how you use git. Do you use it only through GitHub or some other higher front end tool or directly on command line?

**Comment by williamd67** [comment]
@LynxAbraxas I use git(hub) in multiple ways: 
1. github web-interface for remote; mostly create pull-request and verification
2. merging: I rather do locally with the given, by github, git command line commands;
3. git command line commands locally: pull, push, checkout, branch creation;
4. CLion git-plugin to do a single commit as it is easy to see changes in bigger context (meld) and commit from a changelist (sometimes I do git command line commit as well);
I am not used to github (I normally work with bitbucket) and that caused some issues.

May I ask what is different and if I need to improve something?

**Comment by LynxAbraxas** [comment]
> May I ask what is different and if I need to improve something?

Hm, I have to check because basically I got to know git only from command line first, i.e. by using an install from https://git-scm.com/downloads, changing files of a git clone locally (compiling and testing locally) and doing commits etc with git CLIs in a shell with e.g. `git commit`, `git rebase master` etc and checking their dependencies with e.g. `gitk` and only then pushing changes to a remote on e.g. GitHub, GitLab or Bitbucket (which I regard as web interfaces that support git and represent a git remote to my local git repo). I know that GH and GL offer support for direct editing and committing within a web-browser, but I would say they do not offer the full power of git CLIs.

**Comment by williamd67** [comment]
@LynxAbraxas Thanks for pointing out the difference (in another comment) and indeed I need to improve something. I should use rebase and not only merge as that is what I did till now. I rebased this branch and I hope it looks much better now.

**Pull request closed without merging**
