### PR TITLE
Correct goods settings

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR corrects some goods settings.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
https://github.com/civctp2/civctp2/pull/198/commits/1850756533680a40f78dc172c9b20dc4c9fe7c61 corrects this discrepancy:

ss_2019-10-12_14:36:29
ss_2019-10-12_14:36:54

The screen shots show that fish/salmon might need a correction too.

**Comment by LynxAbraxas** [comment]
> The screen shots show that fish/salmon might need a correction too.

Done with ce5a8bcff063e77e52aec4a3fe1d23198a1510c1.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann I'd say this PR is also ready for merge, what do you think?

**Comment by MartinGuehmann** [comment]
Well, then let's merge.

**Pull request merged**
