### PR TITLE
Debug Corporate Branch related things

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR corrects that franchsing is now only possible if the corporate branch is adjacent to the city (before this was possible over arbitrary distances) and a view other related things.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
While https://github.com/civctp2/civctp2/pull/203/commits/67c2e78bd7de70f7e6e684d4b27cc0a3afcf7349 resolves the problem of having red happiness-attack city icons after a reload, I still get this odd very dark gray coloring (beside Massaua):

ss_2019-10-27_00:51:17

@MartinGuehmann any idea where that might come from?

**Comment by LynxAbraxas** [comment]
As I understand the code so far, a corporate branch always succeeds on advertising (no chance involved) but unhappiness (and its icon) are not always resulting from that even though `ArmyData::CauseUnhappiness`
https://github.com/civctp2/civctp2/blob/408bbbaae58a7617d546ca6b2fd27b2d1c73eb64/ctp2_code/gs/gameobj/ArmyData.cpp#L2585-L2669
only contains a chance for the cyber ninja.
@MartinGuehmann any idea where other chance evaluation might come into play here?

**Comment by LynxAbraxas** [comment]
BTW: Why was the unit "Subneural Ad" given up in CTP2? 
Would it be an alternative to introducing Clerics/Televangelists to have a "conversion" effect also for govs other than theocracies? 
The success message indicates that this used to be the intended effect:
https://github.com/civctp2/civctp2/blob/408bbbaae58a7617d546ca6b2fd27b2d1c73eb64/ctp2_data/english/gamedata/info_str.txt#L259

**Comment by LynxAbraxas** [comment]
@MartinGuehmann any feedback to the above questions? Otherwise this PR can go in.

**Comment by MartinGuehmann** [comment]
> only contains a chance for the cyber ninja.
> @MartinGuehmann any idea where other chance evaluation might come into play here?

Well, as far as I understood it. The chance is just about reporting it. This is a bit odd, because you can add to every unit the flag for causing unhappiness.

The other thing that is not well programmed are these hard encoded unit names. The idea of CTP2 is that you can change it via the text files.

**Comment by MartinGuehmann** [comment]
> BTW: Why was the unit "Subneural Ad" given up in CTP2?

That is something you have to ask Activision. I didn't like it either that they kicked out the space layer, but for the game play it is a bit too much. I would also kick out the space ships, because putting units for 4 turns into space so that you can move them between cities doesn't make to me much sense, if I can use the units faster on maglevs.

> Would it be an alternative to introducing Clerics/Televangelists to have a "conversion" effect also for govs other than theocracies (#129)?
> The success message indicates that this used to be the intended effect:

This message mans also that not every ad campaign should succeed. Or is the message just meant as a confirmation that started the ad campaign?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann any feedback to the above questions? Otherwise this PR can go in.

Well, that depends whether you still consider it complete. Or complete enough for a unit after my replies. Anyway, you could resolve the conflict first.

**Comment by LynxAbraxas** [comment]
Tested for a while and seems fine.
The merge conflict was due to different indentations in `CityData.cpp`.
@MartinGuehmann if OK, ready to go in.

**Comment by MartinGuehmann** [comment]
> Tested for a while and seems fine.
> The merge conflict was due to different indentations in `CityData.cpp`.
> @MartinGuehmann if OK, ready to go in.

Well, since you are fine with it, we can merge.

**Comment by LynxAbraxas** [comment]
> I still get this odd very dark gray coloring (beside Massaua):

from https://github.com/civctp2/civctp2/pull/203#issuecomment-546692463

might be related to this assertion of the debug version:

```
Assertion (index < m_colors.size()) Failed in File:ColorSet.cpp, Line:277
Messagebox(Assert): Assertion (index < m_colors.size()) Failed in File:ColorSet.cpp, Line:277
```

**Comment by LynxAbraxas** [comment]
> > I still get this odd very dark gray coloring (beside Massaua):
> 
> from [#203 (comment)](https://github.com/civctp2/civctp2/pull/203#issuecomment-546692463)
> 
> might be related to this assertion of the debug version:
> 
> ```
> Assertion (index < m_colors.size()) Failed in File:ColorSet.cpp, Line:277
> Messagebox(Assert): Assertion (index < m_colors.size()) Failed in File:ColorSet.cpp, Line:277
> ```

Assertion not happening if using a save game that already saved the changes from this PR.
The color comes from:

https://github.com/civctp2/civctp2/blob/e9b85fec02c77c2ef75c997ae02bd305a78fd32c/ctp2_code/gfx/gfx_utils/ColorSet.cpp#L278

**Pull request merged**
