### PR TITLE
Add tools for CTP2 modders

### PR DESCRIPTION
**Pull request by MartinGuehmann**
A tool that converts bitmaps to a text format that CTP2 can import as a map.
ModTools/BMP2CTP2.zip

ReadZFS reads the ZFS files, shows image files and plays the sound files that are inside, and can extract them.
ModTools/readZFS.zip

Activision's sprite tool that creates sprites for CTP1 and CTP2.
ModTools/unitcreation.zip

What is still missing are SpriteEdit and TileEdit. In their readmes I have:

> The legal stuff: (oh how I hate this but it's got to be there)
> 
>    Distribution:
>    This program may NOT under any circumstances be distributed
>    on any read-only media, or as part of any software package,
>    including modifications to games without explicit written
>    permission from the programmer.

So if I include it, is it then part of a software package? Or should I just ignore it?

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
> So if I include it, is it then part of a software package? Or should I just ignore it?

Not sure, any chance of contacting the programmer?

**Comment by LynxAbraxas** [comment]
Tested `readZFS.exe` under Linux with `wine` and was able to extract RIMs/TGAs from ZFSs, 565 RIMs have the typical 555<->565 conversion color artifacts though.

**Comment by MartinGuehmann** [comment]
> > So if I include it, is it then part of a software package? Or should I just ignore it?
> 
> Not sure, any chance of contacting the programmer?

OK, I wrote to Martin the Dane, aka Martin B. Vestergaard. I rather worry whether I'll get a reply after that time. Well, let's see.

So far the web side of Martin just tells me about the wedding of Sara & Martin Reuss Vestergaard.

**Comment by MartinGuehmann** [comment]
Since Martin the Dane has consented, I added SpriteEdit and TileEdit.

**Comment by LynxAbraxas** [comment]
Thant's great! Many thanks.

**Comment by MartinGuehmann** [comment]
Well, then this can go in.

**Pull request merged**
