### PR TITLE
Make games load that have been created before the format fix, the games are saved in the same format

### PR DESCRIPTION
**Pull request by MartinGuehmann**
Make games load that have been created before the format fix, the games are saved in the same format

This pull request restores loading of save games as they have been created on Linux, before the format change, brought up in issue #55.

..\ctp2_code\ctp\c3.h
..\ctp2_code\gs\fileio\GameFile.cpp
..\ctp2_code\os\nowin32\windows.h

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Many thanks @MartinGuehmann. Tests on GL are started. Will report back on the outcome when they are finished.

It seems to me that all three commits should actually be one. If you agree, you can squash all commits and replace the old ones in this PR:

```
git branch -m SaveGameConverter SaveGameConverter_
git checkout master -b SaveGameConverter
git merge --squash SaveGameConverter_
git commit
git push -f # push to same branch name as this PR refers to and GH will consider it
```
PS: Some argue that `git merge --squash` should have been named `git rebase --squash`, as that hints the actual result better.

**Comment by MartinGuehmann** [comment]
I think they should be indeed one, Actually, I tried it with TortoiseGit, but that actually turned two commits into three. So I wait until you have tested it and have confirmed that you can load your old save games and continue the game. Probably, if we have to change more, then it should go in before it is a save game converter.

Actually, I also want to create a branch on civctp2 that contains that savegame converter. This way, if other people need it they could find it more, easily. In principle, the current master could also be merged in again and again via pull requests on git hub.

Actually, I can squash and merge, via the web interface, which is the preferred way. I can edit the pull request so that I can choose another target branch, which is quite convenient. And the only thing, I would like to do is to create the branch, ideally via the web interface. As far as I can see that is the cleanest way to handle these things via GitHub.

**Comment by LynxAbraxas** [comment]
The code compiles and all test run except `load-game`, also when I load my old games manually, the game crashes with:
```
*** Error in `./ctp2': free(): corrupted unsorted chunks: 0x00000000034abcb0 ***
======= Backtrace: =========
```
Any idea what could still be missing?

**Comment by LynxAbraxas** [comment]
> Actually, I also want to create a branch on civctp2 that contains that savegame converter.

Either a branch or just give it a tag. That way it will be listed but better avoid new-comers from accidentally basing new commits on that.

**Comment by LynxAbraxas** [comment]
> Actually, I can squash and merge, via the web interface

The web interface squash and merge is (as far as I know) different from `git merge --squash`. I'm also not sure about the web interface's capabilities concerning `git commit --amend` and `git push --force`.

**Comment by LynxAbraxas** [comment]
Crashes always when the load/progress bar is at around 70% (no variation).

**Comment by MartinGuehmann** [comment]
That is very specific, I could imagine were that is, but for that I would now need a save game. But I can only continue, tomorrow.

**Comment by LynxAbraxas** [comment]
Sorry I missed pointing you to the test save-games of ctp2DF.
Old style: https://github.com/LynxAbraxas/ctp2DF/tree/77c14c1be23c983bd12eb3061cfee4d7ed4b0cd4/.civctp2/save/games/Julius
New style: https://github.com/LynxAbraxas/ctp2DF/tree/e44f20134fa967024ea864a87aa9f48c8bd5d595/.civctp2/save/games/Julius

**Comment by LynxAbraxas** [comment]
@MartinGuehmann are you able to pull and run the docker images from my ctp2DF @ GL?

**Comment by LynxAbraxas** [comment]
Loading now works, but I can also load the newly saved/converted game again, which I was expecting not to work.

**Comment by MartinGuehmann** [comment]
> Loading now works, but I can also load the newly saved/converted game again, which I was expecting not to work.

Interesting, and the Windows games?

**Comment by LynxAbraxas** [comment]
Did some more tests, seems that ctp2 at the state of this PR loads and saves to the old format, i.e. does not save the new format.
I cannot load the save-games of https://github.com/civctp2/civctp2/pull/70/commits/43443d09f856e861433d227aee192088dd2342e1 with this ctp2 version, only with ctp2 from master (https://github.com/civctp2/civctp2/commit/9a1ab16704ccb10c23d14a679adff21501fcd910), which, I think, is as expected for the converter version, since the windows save-games already are in the new format.

I would suggest to move the windows save-games commit https://github.com/civctp2/civctp2/pull/70/commits/43443d09f856e861433d227aee192088dd2342e1 to a separate PR since they are meant for inclusion into master and this PR is meant to end up outside master (note that the current PR is set up for merging into master). If this PR should have save-games, they ought to be from the old (linux) format, i.e. from https://github.com/LynxAbraxas/ctp2DF/tree/598d22f23657c2b4385f082a47d7a745fcbc5c0b/.civctp2/save/games/Julius.

@MartinGuehmann  I'm wondering if the change at https://github.com/civctp2/civctp2/pull/70/commits/dbd26039ea5f715f6055b6b9110cab540d2b9712#diff-8112044a382ecd37162d665f1e425877L1401 is intended for the converter.

I tried to solve this but have great difficulties to see what changes in the various commits actually concern the writing of the save-game.
@MartinGuehmann do you mind reducing the commits of this PR to just the changes needed for the save-game conversion? 
E.g. moving the changes commented with:
```
    Adds some test code that is not so trivial to generate. It is however outcommented.
    ..\ctp2_code\gs\gameobj\UnitData.h
    ..\ctp2_code\gs\gameobj\Vision.h
    ..\ctp2_code\gs\gameobj\citydata.h
    
    Just a style change, no functional change, is for now also outcommented
    ..\ctp2_code\os\nowin32\windows.h
```
out into 2 separate commits, and those into another PR if they do not concern the PR topic.
Please, also combine the first three (up to https://github.com/civctp2/civctp2/pull/70/commits/dcd2f414d4156465e5ba8c1323b31d68ea03d432) into one, with the commands above.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann perhaps it would be easier to start a branch named e.g. `gameConverter` at https://github.com/civctp2/civctp2/commit/868ba9599ec06896d82589da283bd329e5fb695e, i.e. the one before https://github.com/civctp2/civctp2/commit/22dd180480445561bbbcd3efc60f08d2fe5c53e5 and only adding a commit with the code  needed for saving to the new format (and making that a PR to be included as is, i.e. not to be included in master).

**Comment by MartinGuehmann** [comment]
> I would suggest to move the windows save-games commit [43443d0](https://github.com/civctp2/civctp2/commit/43443d09f856e861433d227aee192088dd2342e1) to a separate PR since they are meant for inclusion into master and this PR is meant to end up outside master (note that the current PR is set up for merging into master). If this PR should have save-games, they ought to be from the old (linux) format, i.e. from https://github.com/LynxAbraxas/ctp2DF/tree/598d22f23657c2b4385f082a47d7a745fcbc5c0b/.civctp2/save/games/Julius.

Originally, I thought to but it onto a separate branch on civctp2. But I haven't created that branch, yet. So I thought I just create the pull request and see whether I can change the target branch afterwards, which I can. Otherwise, I would have created a new pull request.

As I understood you previous suggestions, your idea was to put it first in a state of loading the old savegames and also saving it in that format. Then have something that loads in the old format and saves in the new format, and then add load new and save in the new format. That then could be merged into the side branch.
 
> @MartinGuehmann I'm wondering if the change at [dbd2603#diff-8112044a382ecd37162d665f1e425877L1401](https://github.com/civctp2/civctp2/commit/dbd26039ea5f715f6055b6b9110cab540d2b9712#diff-8112044a382ecd37162d665f1e425877L1401) is intended for the converter.
> 

That is needed to make the game load your save games. The difference is that on Linux sizeof(GUID) was 4 bytes but on Windows it is a struct 16 bytes, which I just implemented here, including the equal operators. However, this is not c++ code, so it won't compile if you include i a c file, therefore the cplusplus guard, which I just replaced by zero and I put into the else statement the old definition of GUID on Linux in it.

Serializing means you put all the data into a series, that's how they do it in Player::Serialize:

```
		archive.LoadChunk((uint8 *)&m_owner, ((uint8 *)&m_broken_alliances_and_cease_fires)
			+ sizeof(m_broken_alliances_and_cease_fires));

```

Between m_owner and m_broken_alliances_and_cease_fires we have 70 member variables. Their types are for instance:

```
	sint32           m_patience[k_MAX_PLAYERS] ;
	sint32           m_sent_requests_this_turn[k_MAX_PLAYERS];

	double           m_materialsTax;

	sint32           m_home_lost_unit_count;
```

double needs 8 bytes sint32 needs 4 bytes, and m_patience needs 4 bytes * k_MAX_PLAYERS. Some compiles need to align the data: For instance, if you have something like:

sint32
sint8
sint32

Then, you use 9 bytes, but still need 12, because the compiler pads the space between sint8 and the next sint32 three extra bytes, empty bytes, at least gcc and the VS compiler do so, other compilers may handle it differently. And that was the problem with CityData, the gcc version was 4 bytes shorter then the VS version, of course the extra bytes were added somewhere in the middle. Actually, I redesigned the CityData class and could half its size, which of course was not just because of the data alignment, you don't need 512 bytes for storing a city name either, and 256 bytes to store the name of a build queue. Another aspect of the CityData class is that it is copied very often, I think for no reason. And allocating memory costs time, so halving its size should help quite a lot. It also made the leak reporter to report a memory leak, which makes eventual using up all the memory the game could use.

Back to the player class:

```
		archive.LoadChunk((uint8 *)&m_owner, ((uint8 *)&m_broken_alliances_and_cease_fires)
			+ sizeof(m_broken_alliances_and_cease_fires));

```

Somewhere in that chunk we have a member that is a GUID, which is either 4 bytes or 16 bytes. Everything that follows will get some other values, maybe something is supposed the size of an array, that value could get gigantic or even negative, so try something like this: new MBCHAR[-363636]; Of course that is not good. The problem here is that I have to break the chunk, originally I thought of what I have done in CityData, that would be a lot of work. However, I just need to break it into two parts, which is something that still could go into master.

I know this goes very deep to implementation details of c++ and how they differ between compilers, which are things most programmers don't have to care about. So I would suggest to google for memory alignment in c++ or memory padding in c++. 

> I tried to solve this but have great difficulties to see what changes in the various commits actually concern the writing of the save-game.
> @MartinGuehmann do you mind reducing the commits of this PR to just the changes needed for the save-game conversion?

Sure, I just have to figure out how, since it now contains extra commits and stuff that could be left out, it is a bit more complex, but I guess just add some reverts and then squash should do it. I just wonder how that works with the commit message.

> E.g. moving the changes commented with:
> 
> ```
>     Adds some test code that is not so trivial to generate. It is however outcommented.
>     ..\ctp2_code\gs\gameobj\UnitData.h
>     ..\ctp2_code\gs\gameobj\Vision.h
>     ..\ctp2_code\gs\gameobj\citydata.h
>     
>     Just a style change, no functional change, is for now also outcommented
>     ..\ctp2_code\os\nowin32\windows.h
> ```
> out into 2 separate commits, and those into another PR if they do not concern the PR topic.

In principle, the header files are not needed. They contain extra code to figure out how the compilers align the memory and to see were the data is shifted. It is stuff that could go into master, the pro is that it might be useful for future debugging, the con is that it blows up the file. In principle, it could also be temporarily in master and then removed, this way it is saved.

**Comment by LynxAbraxas** [comment]
Many thanks @MartinGuehmann for the in-depth explanations. It's a part of the code I have never fiddled with.

> So I thought I just create the pull request and see whether I can change the target branch afterwards, which I can.

That's good. Basically I just wanted to point out that the PR is set up for inclusion into master, which in the end is not intended, it's just important that you are aware of that.

> As I understood you previous suggestions, your idea was to put it first in a state of loading the old savegames and also saving it in that format. 

That's right. I wasn't sure at what stage we are. So I would suggest 

1. to move the windows save-games commit 43443d0 to a separate PR since they are meant for inclusion into master and this PR is meant to end up outside master (note that the current PR is set up for merging into master).

2. squash all remaining commits of this PR into one commit, which then should have a note in the commit message, that it basically reverts back to the state before https://github.com/civctp2/civctp2/commit/22dd180480445561bbbcd3efc60f08d2fe5c53e5 concerning the save-game format for linux

2b. optionally add a linux save-game in the old format that should load, and if saved shoud be loadable again.

> Then have something that loads in the old format and saves in the new format,

3. create a new commit that implements this, which is basically then the converter version of ctp2 for old linux save-games to the new format that is then compatible with windows save-games.

3b. the save-game from 2b. should still be loadable, but if saved the new version sould not be loadable any more (but instead with ctp2 from master), so just as a reference, the newly saved game could be added as a commit.

> and then add load new and save in the new format. 

Since that is already in master, and under your consideration to have a converter release, I would skip this step. (It would only be needed if the intention was to replace https://github.com/civctp2/civctp2/commit/22dd180480445561bbbcd3efc60f08d2fe5c53e5 in master.)

Instead,
4. create a new branch (e.g. `gameConverter`) and merge this PR into that and give it a tag  with a message (this will cause GH to regard it as a release).

What do you think of this?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann If you need help on this, I could do 1-2b on a new branch (preserving your authorship), on which you could place 3. then I could do 3b.

Sure.

**Comment by LynxAbraxas** [comment]
Works well, squashed and white space cleaned commits in #77, together with the example save game converted to the new format, which can now be opened with current master.

@MartinGuehmann if you are happy with those and happy to merge #77, I would suggest to close this PR.

**Comment by MartinGuehmann** [comment]
This is now part of #77, and not needed anymore.

**Pull request closed without merging**
