### PR TITLE
Stop the AI from establishing embassies where it cannot

### PR DESCRIPTION
**Pull request by MartinGuehmann**
Stop the AI from establishing embassies, if it is at war with the target civilization, or if the target civilization has the close embassies wonder.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Works well, many thanks @MartinGuehmann. Do you want to include some commits of #259?

**Comment by MartinGuehmann** [comment]
The only thing, that would be relevant would be the change to `ORDER_RESULT ArmyData::EstablishEmbassy`. But I did not remove it, because the point of it is to put the wonder that keeps you from establishing embassies into the message.

**Comment by LynxAbraxas** [comment]
Good point, I must have overseen that then. However I think it only determines the first wonder of that player that is not obsolete, i.e. it misses a check if that wonder is the one that prevents establishing embassies.

**Comment by MartinGuehmann** [comment]
> Good point, I must have overseen that then. However I think it only determines the first wonder of that player that is not obsolete, i.e. it misses a check if that wonder is the one that prevents establishing embassies.

Cleaned the code a bit and fixed that, and found an issue with another message. The stuff compiles on Windows, but I haven't tested it, yet. Even so the code should be straight forward about that.

**Comment by LynxAbraxas** [comment]
Works like a charm now:
ss_2020-07-05_13:28:25
ss_2020-07-05_14:11:38
and the diplomat around a barbarian city are moving off to other targets.
Many thanks @MartinGuehmann for the fixes. I'd say good to go in.

**Comment by MartinGuehmann** [comment]
Well, there is an extra space before "Gutenberg's Bible" in the message. Fixed this and some string related issues.

**Comment by LynxAbraxas** [comment]
Looks good to me.

**Comment by MartinGuehmann** [comment]
Then let's merge.

**Pull request merged**
