### PR TITLE
Directions on development of this master github repo

### PR DESCRIPTION
**Pull request by orlovskyjavaprofi**
People i have two questions:
So active project contributors push code toward stable Linux version of the game?
Any plans for Windows version?
I gone trough the docu, its kind of messy, the dependencies on old direct are problematic ones.
Still maybe is there any chance to walk me trough the codebase?
So that i would be able to help with this interesting to me project, certainly i would be to commit actively in a part time manner.
Do you have an IRC or Email list where i can subscribe ?
Are there any plans for certain features of the game ?

### CODE REVIEW

**Comment by MartinGuehmann** [comment]
Well, you fork the repro on GitHub and also clone it onto your local computer as a working copy. You use your working copy, well to work on it. If you want to add a feature or a bug fix you create a new branch, a feature branch. The feature branch is based on master. Once you are done with adding your feature or fixing your bug you push your feature branch to your fork on GitHub and then you request that your feature branch is pulled into master.

This way, people can check your code whether it contains any glaring bugs or people can also test it, before it goes in. The code should compile and run on Linux with g++ and on Windows with VS2017. Even so we only check automatically whether the code compiles on Linux Ubuntu with g++. In principle, any earlier version of VS2017 should also compile it, however this is untested. Even so we did not actively remove the support for Visual Studio 6, there might be some problems with it. Today, DirectX is included in the Windows SDK and this is the only thing you need.

Let's check the Apolyton readme:

You should not need to add these directories:
Samples\C++\DirectShow\BaseClasses

But you need the tmp directory and environment variable. How to add that, you should find on the web.

For releasing a new version: There seem to be some bugs in the current code that cripple the AI, and I don't have the time to find them.

For features, well feel free to work on whatever you like.

**Comment by LynxAbraxas** [comment]
@orlovskyjavaprofi welcome to CivCTP2 source code project!

> People i have two questions: So active project contributors push code toward stable Linux version of the game? Any plans for Windows version? 

Eventhough the auto-tests are only for linux, most recent contribs to master should work also for windows. You just need to compile the current master under windows.

> I gone trough the docu, its kind of messy, the dependencies on old direct are problematic ones.

Improving the docu could be Your first contrib to the project;-)

> Do you have an IRC or Email list where i can subscribe ? 

The Apolyton forum is not used for communication anymore, all communication is currently done here on GH either as issue or as PR.

> Are there any plans for certain features of the game ?

Best check open issues (https://github.com/civctp2/civctp2/issues) and open PRs (https://github.com/civctp2/civctp2/pulls) to see what problems were found (issues) and what work was started (is ongoing) and not yet merged into master (PRs). 

By the way: Your PR intents to merge master into trunk. However, with git master (or nowadays main) is the main branch, trunk comes from when the project was hosted over SVN. (@MartinGuehmann how about deleting old or unused branches to avoid such confusion? Or tag them if not yet merged?)

**Comment by MartinGuehmann** [comment]
> By the way: Your PR intents to merge master into trunk. However, with git master (or nowadays main) is the main branch, trunk comes from when the project was hosted over SVN. (@MartinGuehmann how about deleting old or unused branches to avoid such confusion? Or tag them if not yet merged?)

I created tags for all the branches at least those that weren't tagged already. And deleted them, even so they might still contained stuff that might be worth adding, but I guess we will never do anyway.

I just haven't deleted trunk yet, because I can't as long as this pull request is open. However, I assume that @orlovskyjavaprofi just didn't know that he could have opened an issue, instead of opening a pull request, so I guess he just filled the required fields with something.

**Comment by LynxAbraxas** [comment]
> I created tags for all the branches at least those that weren't tagged already. And deleted them, even so they might still contained stuff that might be worth adding, but I guess we will never do anyway.

Then #85 could be closed, I guess?

**Comment by MartinGuehmann** [comment]
Well, then let's close this pull request, so that I can delete trunk.

@orlovskyjavaprofi you can still reply to conversation, but when the pull request is closed it will be harder for us to see. However, you can still open an issue.

**Pull request closed without merging**
