### PR TITLE
Debug breaking withdraw troops agreement and its question-message

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR resolves a bug that prevented the (CTP1) question-message for entering lands of a civ with a standing withdraw-troops (leave-our-lands) agreement, solving a part of #157.

This PR relates to #172.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
With f84d351 the question message works when unloading troops

ss_2019-07-28_23:29:37

and with #172 I also get

ss_2019-07-28_23:29:55

**Comment by LynxAbraxas** [comment]
With 988a082 also works when entering the territory on land or water (without unloading).
@MartinGuehmann Is the placement in `ExecuteMoveOrder` in 988a082 appropriate?
I tried to find a corresponding place to where it was in CTP1
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/ArmyData.cpp#L6916-L6919

**Comment by MartinGuehmann** [comment]
> With [988a082](https://github.com/civctp2/civctp2/commit/988a082745cd5822466d1af1990f35d6e6fec8f6) also works when entering the territory on land or water (without unloading).
> @MartinGuehmann Is the placement in `ExecuteMoveOrder` in [988a082](https://github.com/civctp2/civctp2/commit/988a082745cd5822466d1af1990f35d6e6fec8f6) appropriate?
> I tried to find a corresponding place to where it was in CTP1
> https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/ArmyData.cpp#L6916-L6919

That looks like the right place. So if everything works as supposed then it can go.

Probably, this is another issue. The AI does not enter your territory with a withdraw troops agreement, unless it is something concerning transports.

**Comment by LynxAbraxas** [comment]
> That looks like the right place. So if everything works as supposed then it can go.

Then it can go in. I'd regard the violation by the AI in #172.

**Pull request merged**
