### PR TITLE
Fix a crash in the piracy at risk code introduced by #133

### PR DESCRIPTION
**Pull request by MartinGuehmann**
Fix a crash in the piracy at risk code introduced by #133.
..\ctp2_code\ai\diplomacy\diplomat.cpp

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Cool! Under what circumstances did you hit that crash?
How did it get in #133, what was the reason to replace `piracy_iter`?

**Comment by MartinGuehmann** [comment]
> Cool! Under what circumstances did you hit that crash?

Well, I merged master into #336 and just let the AIs play against each other and eventually the game crashed. So I would expect if you just test long enough you will hit hit.

> How did it get in #133, what was the reason to replace `piracy_iter`?

Originally, it iterated through the piracy history list, which only contained trade routes that where actually pirated, but that was not saved, and saving it would have me required to change the save game format, at least I thought so. And so, I moved this information to the trade route itself. Conceptionally, that is better, because that data belongs to the trade route. However, in principle it uses more memory, because it is now in the trade route, but on the other hand, I reused existing but unused variables, so that the memory need is the same. And I think memory consumption of the trade route is not that important because you don't have so many TradeRouteData objects in the game, it is much more important for the Goal class.

The difference is that I now iterate over all trade routes and thus the pirating player could now be -1 so that you try to deference g_player[-1], which then crashes.

**Comment by LynxAbraxas** [comment]
> saving it would have me required to change the save game format, at least I thought so. And so, I moved this information to the trade route itself

That's a very clever idea. Many thanks for getting into this so thoroughly. I wouldn't have been able to come up with that solution.
The new dynamics this brings to the trade routes makes the game much more enjoyable.

**Comment by LynxAbraxas** [comment]
Tested for a while and all seems to work as expeced. So I'd say this PR is good to go.
Thanks @MartinGuehmann for catching this.

**Comment by MartinGuehmann** [comment]
Then we can put in this as, well.

**Pull request merged**
