### PR TITLE
Listing a standing embargo in the diplomacy manager

### PR DESCRIPTION
**Pull request by LynxAbraxas**
So far the embargo icon was only shown when at war but not when only an embargo was enacted.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Enacted embargos to other civs now shown:
ss_2019-11-28_19:30:37

**Comment by LynxAbraxas** [comment]
Tested for a while and seems to work as expeced.
@MartinGuehmann ready for merge?

**Comment by LynxAbraxas** [comment]
For the reference: https://github.com/civctp2/civctp2/issues/201#issuecomment-559583598

**Comment by LynxAbraxas** [comment]
@MartinGuehmann ready for merge?

**Comment by MartinGuehmann** [comment]
> Tested for a while and seems to work as expeced.
> @MartinGuehmann ready for merge?

If it works then let's merge.

**Pull request merged**
