### PR TITLE
Merge ptitSeb branch

### PR DESCRIPTION
**Pull request by ptitSeb**

### CODE REVIEW

**Comment by DEVoytas** [comment]
Hi @ptitSeb 

Thank for your PR, but it looks like it is "Merge branch 'master' into ptitSeb" and what I guess we actually want, is the other way around: merge `ptitSeb` branch (i.e. your changes) into `master`.

I prepared two PRs that achieve that:
- rebase your changes on top of master: https://github.com/civctp2/civctp2/pull/9
- merge your changes into master: https://github.com/civctp2/civctp2/pull/8

Both of them will result in the exactly same code on the master branch:
https://github.com/DEVoytas/civctp2/compare/ptitSeb-merged..ptitSeb-rebased : "ptitSeb-merged and ptitSeb-rebased are identical."

In conflict resolution for REDME.md, I removed info about README file not being 100% accurate, because that is not going to be the case, when PR gets merged into master, and I also updated screenshot link, to point to the current repo  instead of pointing to https://github.com/ptitSeb/ctp2

Diffs for README file:
- against current @ptitSeb version: https://github.com/civctp2/civctp2/pull/9/commits/deada6bacc21c440cf014b43ddb9ddd7d065ecb4
- [against current master](https://github.com/civctp2/civctp2/compare/master...DEVoytas:ptitSeb-merged#diff-2) (please search for "README.md" if link does not get you there directly)

@ptitSeb could you please decide which PR you would prefer: merge or rebase?

**Comment by ptitSeb** [comment]
2018-10-15_14h40_13

But it's stated it's into civctp2:master from ptitseb:ptitseb so It looks like ptitSeb branch (from my fork of civctp2) -> master branch (from main repo)?

**Comment by DEVoytas** [comment]
Hmm, you are right, but on the other hand the message in the last commit is:

> Merge branch 'master' into ptitSeb 

What I think might have happened, is that there may be two merges:
1. one made by you locally: you merged master into ptitSeb
1. then, when you create PR from ptitSeb branch (now containing changes from master, i.e one commit with README I added) to master, it will be second merge, from: ptitSeb to master made by github.

**Comment by civctp2** [comment]
Abandoning (as agreed with @ptitSeb ) in favour of https://github.com/civctp2/civctp2/pull/9 (already merged)

**Pull request closed without merging**
