### PR TITLE
Ask if player wants to break no-piracy agreement

### PR DESCRIPTION
**Pull request by LynxAbraxas**
In contrast to #154, this PR solves #152 such that the player is asked if a no-piracy agreement should be broken (#157). 
This PR makes use of the CTP1 question-message but uses CTP2 code for breaking the agreement (https://github.com/civctp2/civctp2/commit/5f4529c3da7587642c7d9184bcd0c55269e17cf8).
In addition, this PR solves the bug, that the agreement was interpretet the wrong way round (https://github.com/civctp2/civctp2/commit/98e52512c3e1bbb4fa91ad27965a566aea55b02b), i.e. not as an offer but as a request.

So it is no possible in the example below, where the Incans agreed upon a no-piracy request by the Persians, that the Persians pirate an Incan route
ss_2019-07-06_14:14:15

since there is no agreement involved:
ss_2019-07-06_14:13:22
and this changes nothing in the agreements between the two.

Becoming the Incans, who have agreed upon no-piracy with the Persians
ss_2019-07-06_14:28:43

and pirating a Persian route, pops up the question message
ss_2019-07-06_14:30:23

clicking "yes" then executes pirating and leads to the CTP2 trust-loss message and the agreement is cancelled
ss_2019-07-06_14:35:28

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Reloading the same game, offering the Incans to stop piracy
ss_2019-07-06_15:22:36

then pirating an Incan route also leads to the question message
ss_2019-07-06_15:23:59

and upon clicking "yes" pirating is executed, the agreement cancelled and the trust-loss message shown
ss_2019-07-06_15:24:50


From this (in regard to https://github.com/civctp2/civctp2/issues/157#issuecomment-508920786) I would conclude that `PROPOSAL_OFFER_STOP_PIRACY` is recorded as a `PROPOSAL_REQUEST_STOP_PIRACY` with the receiver and sender swapped. However, I could not find the code for this any where. @MartinGuehmann any idea where this might be done?

**Comment by MartinGuehmann** [comment]
> From this (in regard to [#157 (comment)](https://github.com/civctp2/civctp2/issues/157#issuecomment-508920786)) I would conclude that `PROPOSAL_OFFER_STOP_PIRACY` is recorded as a `PROPOSAL_REQUEST_STOP_PIRACY` with the receiver and sender swapped. However, I could not find the code for this any where. @MartinGuehmann any idea where this might be done?

Well, would grep for it:

```
$ grep -rnI '.' -e 'PROPOSAL_REQUEST_STOP_PIRACY' --include *.cpp --include *.hpp --include *.c --include *.h --include *.y --include *.l ./
./ctp2_code/ai/diplomacy/counterresponseevent.cpp:549:           (receiver_response.counter.first_type != PROPOSAL_REQUEST_STOP_PIRACY) ||
./ctp2_code/ai/diplomacy/counterresponseevent.cpp:594:  else if (receiver_response.counter.first_type == PROPOSAL_REQUEST_STOP_PIRACY)
./ctp2_code/ai/diplomacy/diplomat.cpp:166:      case PROPOSAL_REQUEST_STOP_PIRACY:
./ctp2_code/ai/diplomacy/diplomat.cpp:1022:     case PROPOSAL_REQUEST_STOP_PIRACY:
./ctp2_code/ai/diplomacy/diplomat.cpp:1576:     case PROPOSAL_REQUEST_STOP_PIRACY:
./ctp2_code/ai/diplomacy/diplomat.cpp:4355:                     HasAgreement(m_playerId, foreignerId, PROPOSAL_REQUEST_STOP_PIRACY))
./ctp2_code/ai/diplomacy/diplomat.cpp:4358:                             GetAgreement(m_playerId, foreignerId, PROPOSAL_REQUEST_STOP_PIRACY);
./ctp2_code/ai/diplomacy/diplomattypes.h:104:   PROPOSAL_REQUEST_STOP_PIRACY,
./ctp2_code/ai/diplomacy/regardevent.cpp:261:   route_diplomat.LogViolationEvent(army_owner, PROPOSAL_REQUEST_STOP_PIRACY);
./ctp2_code/ai/diplomacy/nproposalevent.cpp:1223:               sender_diplomat.GetNewProposalPriority(receiver, PROPOSAL_REQUEST_STOP_PIRACY);
./ctp2_code/ai/diplomacy/nproposalevent.cpp:1236:               new_proposal.detail.first_type = PROPOSAL_REQUEST_STOP_PIRACY;
./ctp2_code/ai/diplomacy/proposalanalysis.cpp:341:      case PROPOSAL_REQUEST_STOP_PIRACY:
./ctp2_code/ai/diplomacy/proposalanalysis.cpp:686:              case PROPOSAL_REQUEST_STOP_PIRACY:
./ctp2_code/ai/diplomacy/proposalresponseevent.cpp:522: if (sender_proposal.detail.first_type != PROPOSAL_REQUEST_STOP_PIRACY)
./ctp2_code/ai/diplomacy/proposalresponseevent.cpp:549:         receiver_diplomat.GetAcceptPriority(sender, PROPOSAL_REQUEST_STOP_PIRACY);
```

I guess at that places you may find it.

**Comment by LynxAbraxas** [comment]
I did that kind of grep-ing but was not able to find the place, even when going through the code in detail that grep reported.
Anyway, it seems to be done from what the testing showed, so this can go in any way. I'd just like to know the code.

**Comment by MartinGuehmann** [comment]
> I did that kind of grep-ing but was not able to find the place, even when going through the code in detail that grep reported.
> Anyway, it seems to be done from what the testing showed, so this can go in any way. I'd just like to know the code.

Looks like, I didn't it carefully at the first. So then let's put it in.

**Pull request merged**
