### PR TITLE
Sprite building with GL-CI

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR contains adjustments and sikuli instructions to automate the building of new sprites based on blender files. If accepted this should not be merged into master but a separate branch.
Using camel.blend from https://github.com/LynxAbraxas/sprites as an example to avoid git submod dependency (resulting SPR already included since #93).

### CODE REVIEW

**Comment by MartinGuehmann** [comment]
Added the WIP label from my side, so that I know that I have to create the branch first.

**Comment by MartinGuehmann** [comment]
> This PR contains adjustments and sikuli instructions to automate the building of new sprites based on blender files. If accepted this should not be merged into master but a separate branch.

Why shouldn't it be merged into master? As I can see it adds some tests, which costs minutes in GitLab, but is it so much that I have to maintain another branch for it?

**Comment by LynxAbraxas** [comment]
> Why shouldn't it be merged into master?

It contains 6 stages instead of 3 (see e.g. https://gitlab.com/LynxAbraxas/ctp2DF/pipelines/46846226), most of which only make sense to be run when there is a new blender file for a sprite and the actual job that does the creation tends to be sensitive to the load of the servers of the GL-CI runners, so you would introduce unnecessary risk to failures in master, which were the reasons I split that off from master (https://github.com/LynxAbraxas/ctp2DF/commit/3903e5eae66022523ee0b053af781ec39a376f25, which https://github.com/civctp2/civctp2/pull/108/commits/51e5a7338e2e7d92c93e0083821dfb68dc0aaed9 reverts for this branch).

I would recommend a separate branch that should be used for PRs that contribute new/improved sprites from blender files. When such PRs are merged, the resulting artifacts from the job "buildSprites" then contain the new SPR that can be included into the main repos (as e.g. in https://github.com/civctp2/civctp2/commit/13f180d1e17038f4068495903473a52fe0ba69e5).

**Comment by MartinGuehmann** [comment]
> I would recommend a separate branch that should be used for PRs that contribute new/improved sprites from blender files. When such PRs are merged, the resulting artifacts from the job "buildSprites" then contain the new SPR that can be included into the main repos (as e.g. in [13f180d](https://github.com/civctp2/civctp2/commit/13f180d1e17038f4068495903473a52fe0ba69e5)).

That clears this up. Essentially, the new branch needs to be synchronized to master, whenever a new sprite is added from a blender file. As far as I can see you suggest that the new sprites are created automatically by this pull request. Can the new sprite then also be automatically transferred to master?

**Comment by LynxAbraxas** [comment]
> Can the new sprite then also be automatically transferred to master?

That would be possible and I had considered to do that once but decided not to because the effort would be hight and the actual cases when it would be used low (so far). Also I think that doing that step manually is good in order to test that the newly created SPR is functional, because it can happen with the automation with sikuli that at some point an effent is not caught by ctp2 and sometimes that lead to an SPR that was corrupt and then causes the game to crash but only when that sprite would be part of the map (see e.g. the issues 1 and 2 at https://gitlab.com/LynxAbraxas/ctp2DF/issues).

If you prefer not to have another branch that is not meant for inclusion into master, another option would be to just close this PR and leave it as is until needed. This PR would keep track of that contribution if it becomes of interest at some point. Apart from the instructions how to interact with the GUI, this PR contains the a shell script that defines how a blender file can be render into a TIF series and how those need to be adjusted such that the cpt2 sprite-loader accepts them. It also contains an AWK script that generates the necessary text file that the sprite-loader expects with the image series, see e.g. https://github.com/civctp2/civctp2/pull/108/commits/7eb794762a5d730169a24e01f7d75526107f1f0a. All together they automate what `makespr` (http://www.ctp2.info/htdocs/modguides/sprites/makespr03.shtml) would but directly with ctp2 and therefore is also available under Linux, i.e. another way for the automation would be to launch  `makespr` with wine (if that works, is  `makespr` still available?) in the GL-CI.

**Comment by MartinGuehmann** [comment]
> > Can the new sprite then also be automatically transferred to master?
> 
> That would be possible and I had considered to do that once but decided not to because the effort would be hight and the actual cases when it would be used low (so far). Also I think that doing that step manually is good in order to test that the newly created SPR is functional, because it can happen with the automation with sikuli that at some point an effent is not caught by ctp2 and sometimes that lead to an SPR that was corrupt and then causes the game to crash but only when that sprite would be part of the map (see e.g. the issues 1 and 2 at https://gitlab.com/LynxAbraxas/ctp2DF/issues).

So then we keep it like that, that would be indeed too much. I don't expect that we would mass produce hundreds of more sprites.

> If you prefer not to have another branch that is not meant for inclusion into master, another option would be to just close this PR and leave it as is until needed. This PR would keep track of that contribution if it becomes of interest at some point. Apart from the instructions how to interact with the GUI, this PR contains the a shell script that defines how a blender file can be render into a TIF series and how those need to be adjusted such that the cpt2 sprite-loader accepts them. It also contains an AWK script that generates the necessary text file that the sprite-loader expects with the image series, see e.g. [7eb7947](https://github.com/civctp2/civctp2/commit/7eb794762a5d730169a24e01f7d75526107f1f0a). All together they automate what `makespr` (http://www.ctp2.info/htdocs/modguides/sprites/makespr03.shtml) would but directly with ctp2 and therefore is also available under Linux, i.e. another way for the automation would be to launch `makespr` with wine (if that works, is `makespr` still available?) in the GL-CI.

So I guess it is now a fancy version of makespr. And the script just clicks the buttons to make the sprite. In principle, I would prefer to include it as a branch, which also needs then a release, and a description of the purpose with a manual how to use it, at least a basic one.

I think that makespr is still on the server of Apolyton. I just don't think it is available via the download section since that went, when they upgraded. The author of the download section addon died 8 or 9 years ago or something, so that's why no upgrade for that and then you still have the hassle to migrate the stuff to something else. In principle, I still should have it on one of my hard drives. Unfortunately, the Win98 hard drive died, and the WinXP hard drive was dying. I tried to install on Linux a data rescue program, but I could only install it afterwards I had unplugged that drive and since then I haven't plugged it back.

On the Win98 drive I had some old browsers, Opera 6 and 7, Netscape 4.7, Mozilla 1.7.5, and Internet Explorer whatever version. Some of them didn't like to run on Win7, and those who did, didn't display a webpage. Anyway, since I used makespr on Win98, I would expect that it is actually DOS compatible, so you have some chances that it runs in a DOSbox. :D

**Comment by LynxAbraxas** [comment]
> So I guess it is now a fancy version of makespr. And the script just clicks the buttons to make the sprite.

Yes, not necessarily fancy, just the simplest way I could think of to get that functionality, I would prefer a CLI for this. Do you see any chance to get the `makespr` code? If so it would be great to have it as another repo here on https://github.com/civctp2/.

If having another branch around is not to your liking, feel free to close this PR. The conrib (as far as I know but better check the GH docs before) should stay available with this PR (as a kind of hidden branch, something special to GH) and in case interest arises, you can just re-open it.

**Comment by LynxAbraxas** [comment]
Just as a reference concerning the old `makespr` CLI: https://github.com/civctp2/civctp2/pull/146#issuecomment-502402248

**Pull request closed without merging**
