### PR TITLE
Debug AI route creation

### LINKED ISSUE #155: AI logic for trade route creation/removal seems bad
When giving the human-player to the AI for one turn, the AI gives up trade routes and establishes new ones but in total with a far lower profit.
13 trade routes with a total profit of 941 before letting the AI play for one turn (`/attach 1`):

ss_2019-06-23_18:28:02

afterwards 5 routes with a total of only 340:

ss_2019-06-23_18:02:41

### PR DESCRIPTION
**Pull request by LynxAbraxas**
PR to resolve #155.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
While @Fromafar was trying to improve the code for the AI trade route creation (part of db031c906573), this apparently was neither tested nor enabled. It is enabled in 90bdad4a9, but testing (with ca1a3a2) showed, that even the original code was missing reverting the sorted list (362e91c6b) such that the AI started to initiate routes with the lowest values (formerly gold, now valuePerCaravan),  most often using up its caravans before reaching the end of the list. So in the end the AI basically did the worst job possible on creating new routes...

**Comment by LynxAbraxas** [comment]
So far the code is missing the use of `valuePerCaravan` for deciding if a standing route should be cancelled (still uses just gold value), so currently it likely cancels routes it then initiates again, loosing a caravan for that per route.

**Comment by MartinGuehmann** [comment]
Is it actually documented somewhere that you loose a caravan, if you cancel a trade route? I can remember something like this. But actually what is the point of loosing caravans?

**Comment by LynxAbraxas** [comment]
> Is it actually documented somewhere that you loose a caravan, if you cancel a trade route? 

I think I read something like that in the activision manual.

> But actually what is the point of loosing caravans?

I think it is a concept that should force one to consider cancelling standing trade routes. However, so far the AI is not "taught" to do so.

**Comment by LynxAbraxas** [comment]
What I wonder is why the route cost printed with ca1a3a2a74 (see terminal)
ss_2020-01-25_18:33:27
is up to 4 caravans lower than later listed in the trade manager, which is the actual cost (at least for a human player).
The routes for 120 and 62 gold probably were not killed because they still were offering the best price for that good.

**Comment by LynxAbraxas** [comment]
While investigating the above issue, I came across:
https://github.com/civctp2/civctp2/blob/8ed4659c7075e856b9ba72e02e21facf0329ce26/ctp2_code/gs/gameobj/Player.cpp#L3024-L3036
@MartinGuehmann Any idea what this code is for in `CreateTradeRoute`?

**Comment by MartinGuehmann** [comment]
> While investigating the above issue, I came across:
> https://github.com/civctp2/civctp2/blob/8ed4659c7075e856b9ba72e02e21facf0329ce26/ctp2_code/gs/gameobj/Player.cpp#L3024-L3036
> 
> 
> @MartinGuehmann Any idea what this code is for in `CreateTradeRoute`?
> Is it just for killing a route to get that good for creating a new route?

That's how it looks like, but of course you would like to see the methods that call this code to see whether it is really so.

**Comment by LynxAbraxas** [comment]
> What I wonder is why the route cost printed with ca1a3a2 (see terminal)
is up to 4 caravans lower than later listed in the trade manager, which is the actual cost (at least for a human player).

Solved with 17fe9f30bc.

**Comment by LynxAbraxas** [comment]
c6fa890099 was a slight struggle, but worth the effort:
Before giving the human player to the AI (941 gold from trade):
ss_2020-01-25_23:46:13
without this PR after one turn played by the AI (`/attach 1`, 340 gold):

with 17fe9f3 (605 gold):
ss_2020-01-25_23:50:50
with c6fa890 (1053 gold):
ss_2020-01-26_19:39:37
and also a lot of import now:
ss_2020-01-26_19:40:18

So now the AI can come up with a better trade setting than the human player (under the current game limitation that trade gold is not subtracted from the receiver of the bonus, see https://github.com/civctp2/civctp2/issues/234#issuecomment-578500077).

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Is there an elegant way to get the total trade gold from each player via the logs of the debug version?
`gslog.txt` has entries with `Net Trade: 4100` but that seems to come from `GetNetCityGold`.

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann Is there an elegant way to get the total trade gold from each player via the logs of the debug version?
> `gslog.txt` has entries with `Net Trade: 4100` but that seems to come from `GetNetCityGold`.

I think this should be renamed to "Net Gold". In the original code Activision used Gold and Trade as synonyms, which is quite annoying, could you change it so that gslog.txt says "Net Gold"?

What you want is I guess m_goldFromTradeRoutes, which is calculated in CalculateGoldFromResources(). That is also a bit misleading, could you also rename it to CalculateGoldFromTrade().

I don't think that m_goldFromTradeRoutes is reported by the debug version, but you could add it.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann any ideas on this: https://github.com/civctp2/civctp2/issues/234#issuecomment-578456044?

**Comment by LynxAbraxas** [comment]
> > @MartinGuehmann Is there an elegant way to get the total trade gold from each player via the logs of the debug version?
> > `gslog.txt` has entries with `Net Trade: 4100` but that seems to come from `GetNetCityGold`.
> 
> I think this should be renamed to "Net Gold". In the original code Activision used Gold and Trade as synonyms, which is quite annoying, could you change it so that gslog.txt says "Net Gold"?
> 
> What you want is I guess m_goldFromTradeRoutes, which is calculated in CalculateGoldFromResources(). That is also a bit misleading, could you also rename it to CalculateGoldFromTrade().
> 
> I don't think that m_goldFromTradeRoutes is reported by the debug version, but you could add it.

OK, rebased on current master and inserted 11d857a67aa18c8899012f75067d7b554fd1db0c at the beginning for comparing the change of the following commits.

**Comment by LynxAbraxas** [comment]
With 47d63edecc87a3b4aaf0894088260f1e62cb8832 the total trade profit achieved is now even 1086 gold:
ss_2020-01-27_22:03:26
ss_2020-01-27_22:03:44

I'm not sure why I once had the trade profit in the trade manager and the empire manager out of sync but with 6d2d525bbc9a89bef4c53a21199811a967974b90 that should not be the case any more:
ss_2020-01-27_22:04:23

**Comment by LynxAbraxas** [comment]
I was considering to deprecate `GetGoldInReturn()` for CTP2
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/TradeRouteData.h#L180
in order to avoid future misinterpretation like https://github.com/civctp2/civctp2/issues/234#issuecomment-578500077 but decided not to because it could come in handy for providing extra gold (that actually gets subtracted from the receiver of the bonus) for the value of the bonus to the receiver. However that should be its own PR because that would be a new feature and this here is meant for debugging.

@MartinGuehmann Any idea what the orginal reason behind  `GetGoldInReturn()` was in addition to `GetValue()`?

**Comment by LynxAbraxas** [comment]
With the debug-version of 11d857a67aa18c8899012f75067d7b554fd1db0c `grep 'Total Trade Profit' logs/gslog.txt` yields:
```
  Total Trade Profit: 734
  Total Trade Profit: 26
  Total Trade Profit: 154
  Total Trade Profit: 236
  Total Trade Profit: 164
  Total Trade Profit: 414
  Total Trade Profit: 80
  Total Trade Profit: 131
  Total Trade Profit: 107
  Total Trade Profit: 278
  Total Trade Profit: 35
  Total Trade Profit: 487
  Total Trade Profit: 0
  Total Trade Profit: 340
```
and for the debug version of 6d2d525bbc9a89bef4c53a21199811a967974b90:
```
  Total Trade Profit: 1126
  Total Trade Profit: 53
  Total Trade Profit: 378
  Total Trade Profit: 551
  Total Trade Profit: 146
  Total Trade Profit: 217
  Total Trade Profit: 492
  Total Trade Profit: 647
  Total Trade Profit: 137
  Total Trade Profit: 181
  Total Trade Profit: 119
  Total Trade Profit: 274
  Total Trade Profit: 0
  Total Trade Profit: 1086
```
and the difference table with `paste <(grep 'Total Trade Profit' logs1/logs/gslog.txt) <(grep 'Total Trade Profit' logs2/logs/gslog.txt) | awk '{print $8, $4, $8-$4}'  | column -t -R1,2,3` is:
```
1126  734   392
  53   26    27
 378  154   224
 551  236   315
 146  164   -18
 217  414  -197
 492   80   412
 647  131   516
 137  107    30
 181  278   -97
 119   35    84
 274  487  -213
   0    0     0
1086  340   746
```
So overall an improvement for most civs. Oddly the order in the lists does not correspond to the order of the civs, so I can't say for sure which listings correspond to the 2 dead civs.

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann Any idea what the orginal reason behind `GetGoldInReturn()` was in addition to `GetValue()`?

Just look at the code. GetGoldInReturn seems to return the amount of gold you can make with this route by judging from its name. GetValue calculates something that measures how far that city is away from that good which would be a proxy for how much this city needs the good. If you wanna know that more exactly then you have to look onto it more closely. I just looked superficially onto it.

**Comment by MartinGuehmann** [comment]
> Oddly the order in the lists does not correspond to the order of the civs, so I can't say for sure which listings correspond to the 2 dead civs.

The dead civs should not show up in that list. And you may have some new civs which would be inserted after the turn of the player during which they have been created.

**Comment by LynxAbraxas** [comment]
Hm, I started the game with 15 civs, and there are 15 in the list but 2 are dead and using the cheat mode I can say that no new ones got created. Actually, I never observed that a new civ got inserted so far. Could it be that that is not working under Linux?

**Comment by LynxAbraxas** [comment]
I also could not find that setting that allows new civs to be inserted. Do you know how it should be called?

**Comment by MartinGuehmann** [comment]
> Hm, I started the game with 15 civs, and there are 15 in the list but 2 are dead and using the cheat mode I can say that no new ones got created. Actually, I never observed that a new civ got inserted so far. Could it be that that is not working under Linux?

No that are your settings. You have it on the new game screen. Select number of players (or civilizations) 
NumberOfPlayers

The first one sets the number of players you start the game with. The second is the number of players to that the game would fill up. And the last is the player you play, which influences the color of your player.

The corresponding settings in userprofile.txt are:
NumPlayers=11
PlayerNumber=1
MaxPlayers=32

Obviously, we do not count the Barbarians as civilization, so that we have one more player than shown on the screen.

I think MaxPlayers is not saved in the savegame, so if you change it by editing it in userprofile.txt directly or via the settings when you are starting a new game should affect your existing games.

**Comment by LynxAbraxas** [comment]
For a current test-game the AI route creation also improved.
With 11d857a67aa18c8899012f75067d7b554fd1db0c:
ss_2020-01-29_17:44:25
with 47d63edecc87a3b4aaf0894088260f1e62cb8832 many more routes (see also the radar map):
ss_2020-01-29_17:50:53
and the difference table:
```
  0    0    0
  0    0    0
316    0  316
  6    6    0
 80   47   33
  0    0    0
147   45  102
  0    0    0
  5    5    0
  8    8    0
  0    0    0
  0    0    0
130   33   97
 74    6   68
  0    0    0
241  241    0
```
So all civs with trade routes now make much better trade profit.

**Comment by LynxAbraxas** [comment]
> I think MaxPlayers is not saved in the savegame, so if you change it by editing it in userprofile.txt directly or via the settings when you are starting a new game should affect your existing games.

I see, many thanks @MartinGuehmann for explaining that. In my settings I found `MaxPlayers=1`.
Should a changed value also be taken into account when just loading a saved game, i.e. not starting a new game or dos the setting effect any other variables that then are saved in the game-file?

**Comment by LynxAbraxas** [comment]
> > @MartinGuehmann Any idea what the orginal reason behind `GetGoldInReturn()` was in addition to `GetValue()`?
> 
> Just look at the code. GetGoldInReturn seems to return the amount of gold you can make with this route by judging from its name. GetValue calculates something that measures how far that city is away from that good which would be a proxy for how much this city needs the good. If you wanna know that more exactly then you have to look onto it more closely. I just looked superficially onto it.

Well, I did look at it quite closely and think that `GetGoldInReturn()` comes from CPT1 trade where you had bids and offers, i.e. set the price for a good to sale manually and also decide which goods on the marked you would want, then only if also the seller agreed a trade route was created. There in CTP1 I could imagine that `GetValue()` was used to determine the value of a good for AI civs and `GetGoldInReturn()` for the cost human players could set manually.
Since now the only active trade route creation seems to be
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/PlayerEvent.cpp#L556-L558
`GetGoldInReturn()` is set to 0 for any trade route, which makes sense because in CTP2 even human players have the price for their goods set automatically, i.e. cannot set the cost manually any more. Neither is there the step of accepting bids and offers. Only the human player can cancel routes in the trade manager. However, this is currently of little meaning, because the gold for the seller is not taken from the receiver:
 https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/CityData.cpp#L4510-L4538
nor does the seller loose the bonus of the good sold (#215).

**Comment by MartinGuehmann** [comment]
> > I think MaxPlayers is not saved in the savegame, so if you change it by editing it in userprofile.txt directly or via the settings when you are starting a new game should affect your existing games.
> 
> I see, many thanks @MartinGuehmann for explaining that. In my settings I found `MaxPlayers=1`.
> Should a changed value also be taken into account when just loading a saved game, i.e. not starting a new game or dos the setting effect any other variables that then are saved in the game-file?

Well, that's actually another issue. When you load a save game the value found in userprofile.txt is used. I don't think that this is really a cheat if you change this, so that setting could be actually exposed via advanced settings or something like this.

Unless you still want to discuss more stuff here, I guess we are ready now for merge.

**Comment by LynxAbraxas** [comment]
Created #254 to track ideas for further improvements and added some comments 0670b547b7e5acba63bd6c92785dba4edb8d0eea.
Tested this PR for a while and all seems to work as expected.
@MartinGuehmann ready for merge?

**Comment by LynxAbraxas** [comment]
Also tested effect of f951d2fc8ca0b31a6778cd3f207ab3e952052a78.
Without f951d2fc8ca0b31a6778cd3f207ab3e952052a78 trade routes with the Ethopians (trade pact exists) only give 98 and 80 gold:
ss_2020-01-29_20:00:02
but with f951d2fc8ca0b31a6778cd3f207ab3e952052a78 102 and 84 gold (5% extra):
ss_2020-01-29_19:52:30

**Comment by LynxAbraxas** [comment]
Freeing slaves when conquering a city:
ss_2020-01-28_23:14:55
choosing yes (more food needed):
ss_2020-01-28_23:22:26
choosing no (less food needed):
ss_2020-01-28_23:19:12

**Comment by MartinGuehmann** [comment]
> Created #254 to track ideas for further improvements and added some comments [0670b54](https://github.com/civctp2/civctp2/commit/0670b547b7e5acba63bd6c92785dba4edb8d0eea).
> Tested this PR for a while and all seems to work as expected.
> @MartinGuehmann ready for merge?

Well, then we can merge.

**Pull request merged**
