### PR TITLE
WIP: message for the pirate victim

### PR DESCRIPTION
**Pull request by LynxAbraxas**
Follow up on #76 based on @MartinGuehmann comment https://github.com/civctp2/civctp2/pull/76#issuecomment-482749127, the message for the victim of piracy should not be based on the success of the attacker but instead on the fact that the trade gold is not added in case of piracy (especially by multiple civs on the same route).

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
@MartinGuehmann any idea what could be wrong with the slic code of https://github.com/civctp2/civctp2/pull/125/commits/10c2c75fb574a6e69ae960dfb010ce8f0f8b8cab or https://github.com/civctp2/civctp2/pull/125/commits/d72a35b6c39010f93c8a88154da957e3fccd7657? I do get the value of the route printed to stderr with https://github.com/civctp2/civctp2/pull/125/commits/9be3eb23e1556a01341d426ce62c9d26aa720ee8 but I do not get the message even if I am the victim (using the test game from https://github.com/civctp2/civctp2/issues/75#issuecomment-483026718).

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann any idea what could be wrong with the slic code of [10c2c75](https://github.com/civctp2/civctp2/commit/10c2c75fb574a6e69ae960dfb010ce8f0f8b8cab) or [d72a35b](https://github.com/civctp2/civctp2/commit/d72a35b6c39010f93c8a88154da957e3fccd7657)? I do get the value of the route printed to stderr with [9be3eb2](https://github.com/civctp2/civctp2/commit/9be3eb23e1556a01341d426ce62c9d26aa720ee8) but I do not get the message even if I am the victim (using the test game from [#75 (comment)](https://github.com/civctp2/civctp2/issues/75#issuecomment-483026718)).

Not really, but you haven't put all the values you pass to the slic object to stderr. Maybe then you see something unexpected.

**Comment by LynxAbraxas** [comment]
Seems the problem here also relates to #75, `IsBeingPirated` 
https://github.com/civctp2/civctp2/blob/master/ctp2_code/gs/gameobj/CityData.cpp#L4440
always returns `false` in case of the human player even if the route is pirated.

Let's wait with removing https://github.com/civctp2/civctp2/pull/125/commits/9be3eb23e1556a01341d426ce62c9d26aa720ee8 and merging this PR until that issue is solved.

**Comment by LynxAbraxas** [comment]
Odd, now that #75 is resovled (with #127) I get the message 4 times each turn even though in the test game there is only one trade route pirated. @MartinGuehmann any idea if 
https://github.com/civctp2/civctp2/blob/0668dd199c2519ff8ab7d2871e7c7a89e21c8e52/ctp2_code/gs/gameobj/CityData.cpp#L4433
is exectuted multiple times per turn?
I expect that `m_tradeSourceList` is per city not global.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Any idea what else could case the multiple massages?
If I open the CauseAndEffectTab I get many more instantly, even with https://github.com/civctp2/civctp2/pull/125/commits/409a514694a696df289fdc9c2570c0b84c2ae12c.

**Comment by LynxAbraxas** [comment]
In relation to the screen shots of #146:

ss_2019-06-15_22:57:53

Even though #76 is merged, I did not get a message that one of my trade routes got pirated, even though the trade manager lists that the trade route from Boston is being pirated.
@MartinGuehmann as #146 also concerns the CauseAndEffectTab, any idea why the approach for a message of this PR does not work as expected?

**Comment by LynxAbraxas** [comment]
There is at least also the call to the cities' `PreResourceCalculation` called from here
https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_code/gs/gameobj/Player.cpp#L9237
which results in a call to 
https://github.com/civctp2/civctp2/blob/0668dd199c2519ff8ab7d2871e7c7a89e21c8e52/ctp2_code/gs/gameobj/CityData.cpp#L4433
Even without having resolved #117, the message for the victim introduced with #76 should appear at least once each turn a trade route is pirated. It worked all right in the test game for #75.

**Comment by LynxAbraxas** [comment]
The behavior described in https://github.com/civctp2/civctp2/pull/125#issuecomment-502399923 is correct in the current state: The trade manager basically shows a pirating indication for the last army that did a pirating action on the route. If it is the only civ pirating that route, it will get the booty in the next turn (sub-turn of that civ) which then leads to the expected message to the victim introduced with #76:

ss_2019-06-27_00:20:01

Additionally, the screen-shot shows in the trade-manager that the Irish "plan" to pirate the route to their own city "Waterford" in the next turn.
This "planned" pirating can still be averted by asking that civ (Irish) to agree upon a no-piracy agreement (before the end of the turn). The breaking of such an agreement is currently WIP in #175.

**Comment by LynxAbraxas** [comment]
As it currently seems to stand, the gold of a trade route is not added to the total income if it is pirated, to be precise if a pirating army is set, 
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/CityData.cpp#L4442
which is the case even if multiple civs pirate the route at the same time. However, then neither of the pirates gets the booty 
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/ArmyData.cpp#L1675
and therefore there is also no message to the victim 
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/ArmyData.cpp#L1698-L1705
(despite the gold being lost). 
Moving the message to the victim such that it is independent of a pirate getting the booty (as in this PR) turns out to be problematic, because the function that takes pirating into account 
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/CityData.cpp#L4435-L4463
is called multiple times and even on specific user interaction.

So simplest way seems to be to realize #117, which would ensure that one pirate gets the booty in any case and that would ensure that the victim gets the message as implemented with #76.

**Comment by LynxAbraxas** [comment]
Just for the record:

https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/CityData.cpp#L4442
leads to
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/TradeRouteData.cpp#L611-L614
which leads to
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/Army.cpp#L45-L48
leading to
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/ArmyPool.h#L15
and finally to
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/gs/gameobj/ObjPool.h#L143-L150

**Comment by LynxAbraxas** [comment]
Closing due to these considerations: https://github.com/civctp2/civctp2/pull/125#issuecomment-513903329

**Pull request closed without merging**
