### PR TITLE
Debug version with GL-CI

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR offers changes to compile a debug version with GL-CI. 
This PR could either be merged into a separate branch from master or adjusted such that the debug build and test jobs are added to the normal jobs. This however would about double the use of GL-CI minutes of shared runners (but not much the overall test time because the jobs can run in parallel independently). 
If a debug build and tests are not needed for every commit to master, a separate branch might be more apropriate. However, then merging in master for testing will be neede to trigger the GL-CI pipeline.
The current artifacts contain the `logs/`https://github.com/civctp2/civctp2/commit/254704d1dbbbc655697df1331bad0a6d2ee7713b but not `CTP_LEAKS_99999.TXT`, `CTP_LEAKS_ALT_99999.TXT` (good for detecting memory leaks: https://github.com/civctp2/civctp2/pull/97#issuecomment-465246916).

### CODE REVIEW

**Comment by MartinGuehmann** [comment]
> This PR could either be merged into a separate branch from master or adjusted such that the debug build and test jobs are added to the normal jobs. This however would about double the use of GL-CI minutes of shared runners (but not much the overall test time because the jobs can run in parallel independently).

So that is the last thing to consider: Doubling the time of GL-CI minutes. As far as I can see, it is triggered when something new arrives in master and actually it is also bundled, so if I merge in a bunch of pull requests within a few minutes then it is one test. Right now I think it doesn't matter anyway, since we don't have so much and in case of doubt I could still merge them closely together. 

> If a debug build and tests are not needed for every commit to master, a separate branch might be more apropriate. However, then merging in master for testing will be neede to trigger the GL-CI pipeline.

A separate branch would mean that I still have to synchronize it with master from time to time. So that is some additional work.

So for now, I tend to just merge this pull request with master.

**Comment by LynxAbraxas** [comment]
This is still WIP and not yet ready for merge.

**Comment by LynxAbraxas** [comment]
closed unintentionally

**Comment by LynxAbraxas** [comment]
OK, this PR is back on track and GL-CI is configured now to build a plain and a debug version and test both. The logs from the debug version are available through the job artifacts.

**Comment by LynxAbraxas** [comment]
It seems the changes of #182 broke the compilation of the debug version under Linux:
https://github.com/civctp2/civctp2/pull/182#issuecomment-562869203

**Comment by LynxAbraxas** [comment]
Hm, https://github.com/civctp2/civctp2/pull/107/commits/a998120a2e6e8eb2b1a9eafbff539802fffc3bb8 does still not solve the problem for the debug version (https://gitlab.com/LynxAbraxas/civctp2/pipelines/101413376) because here
https://github.com/civctp2/civctp2/blob/55b706d1eed95c20ca71b2b2e54952d7812d4d68/ctp2_code/ui/aui_common/aui_bitmapfont.cpp#L235
`g_ui->GetBitmapFontResource()->FindFile` is not yet working (probably because some initialization is missing there as well at this stage) an so `fullPath` is not populated:
```
Assertion (error == 0) Failed in File:ui/aui_common/aui_bitmapfont.cpp, Line:243
Messagebox(Assert): Assertion (error == 0) Failed in File:ui/aui_common/aui_bitmapfont.cpp, Line:243
Font arialbd.ttf () failled
Assertion (error == 0) Failed in File:ui/aui_common/aui_bitmapfont.cpp, Line:247
Messagebox(Assert): Assertion (error == 0) Failed in File:ui/aui_common/aui_bitmapfont.cpp, Line:247
Assertion (font) Failed in File:ui/aui_utils/primitives.h, Line:77
Messagebox(Assert): Assertion (font) Failed in File:ui/aui_utils/primitives.h, Line:77

Thread 1 "ctp2" received signal SIGSEGV, Segmentation fault.
0x00005555557e7b10 in aui_BitmapFont::HasCached (this=0x0)
    at ui/aui_common/aui_bitmapfont.h:117
#0  0x00005555557e7b10 in aui_BitmapFont::HasCached (this=0x0)
    at ui/aui_common/aui_bitmapfont.h:117
#1  0x00005555557e5414 in aui_BitmapFont::SetPointSize (this=0x0, pointSize=9)
    at ui/aui_common/aui_bitmapfont.cpp:328
#2  0x00005555558582e5 in getBitmapFont () at ui/aui_utils/primitives.h:78
#3  0x0000555555852474 in primitives_DrawText (pDirectSurface=0x55555b83dccc, 
    x=325, y=18, pString=0x555556b933c0 <g_splash_buf> " 510381.73 secs  ", 
    color=16317688, bg=true) at ui/aui_utils/primitives.cpp:1152
#4  0x0000555555991165 in Splash::AddTextNL (this=0x55555743027c, 
    text=0x555556b933c0 <g_splash_buf> " 510381.73 secs  ")
    at ui/interface/splash.cpp:68
#5  0x0000555555774dd0 in ui_Initialize () at ctp/civ3_main.cpp:431
#6  0x000055555577d6d8 in CivApp::InitializeApp (this=0x555556cac61c, 
    hInstance=0x0, iCmdShow=2) at ctp/civapp.cpp:1285
#7  0x000055555577709d in CivMain (iCmdShow=2, pSzCmdLine=0x7fffffffecd8)
    at ctp/civ3_main.cpp:1682
#8  0x0000555555776c6d in main (argc=2, argv=0x7fffffffecd8)
    at ctp/civ3_main.cpp:1441

```

@MartinGuehmann any ideas where to go form here? 
Do we need a much more primitve way for font drawing avoiding use of  `aui_BitmapFont` completely for all `primitives_Draw*Text*`?

**Comment by LynxAbraxas** [comment]
Finally, with https://github.com/civctp2/civctp2/pull/107/commits/0266de2fddb1847a107bf8f945ace91b0c24ad46 the debug version passes again all GL-CI tests (https://gitlab.com/LynxAbraxas/civctp2/pipelines/101427336) and there is some text beside the start screen under Linux:

ss_2019-12-07_22:28:29

@MartinGuehmann is https://github.com/civctp2/civctp2/pull/107/commits/0266de2fddb1847a107bf8f945ace91b0c24ad46 acceptable?

**Comment by LynxAbraxas** [comment]
Also https://github.com/civctp2/civctp2/pull/107/commits/3ecfb20adce9cfce3ff3d04b6d052095cea75ac2 passes all GL-CI tests (https://gitlab.com/LynxAbraxas/civctp2/pipelines/101430189).
@MartinGuehmann is this PR ready for merging in your opinion?

**Comment by LynxAbraxas** [comment]
> This PR ... adjusted such that the debug build and test jobs are added to the normal jobs. 

The PR is now in such a state.

**Comment by LynxAbraxas** [comment]
There some more logs that are not saved under `logs/` but directly in the dir of the ctp2 exec like `ctp2linux.map` and `dipcombo.txt`. To write those there the debug version must be run as root (90923d81eabdcf51fa290dc64af95d1d43883d3f). Is there any reason not to write those to `logs/` as well?

**Comment by LynxAbraxas** [comment]
While https://github.com/civctp2/civctp2/pull/107/commits/aaa69cd2aa91c958d2ed3b74cc4ddb8c61263f30 preserves the map-file (https://gitlab.com/LynxAbraxas/civctp2/-/jobs/372823679/artifacts/browse/logs/), this does not seem to be strictly necessary because
https://github.com/civctp2/civctp2/blob/e9b85fec02c77c2ef75c997ae02bd305a78fd32c/ctp2_code/ctp/debugtools/debugcallstack.cpp#L245-L317
has alread read and closed it.
@MartinGuehmann should https://github.com/civctp2/civctp2/pull/107/commits/aaa69cd2aa91c958d2ed3b74cc4ddb8c61263f30 be reverted?

**Comment by LynxAbraxas** [comment]
@MartinGuehmann What do you think? Ready for  merge?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann What do you think? Ready for merge?

Possible, but at least I should answer your question. And depending on the answers you may want to change something.

ctp2linux.map is in the executable folder, because that is where Visual Studio places the Windows map files. Just a thing of consistency. However, there is no need  to place it there or even save it. For dipcombo.txt ask Activision why it is there. I guess they put the civ3logXXX.log files into their own folder, when they started filling these files up  and so created tones of them. And dipcombo.txt is just left in its original place. There are also some other log files in the executable folder, including leak logs.

Just keep in mind CTP1 and thus CTP2 were designed for Win95, where stuff such as settings or save games were put into the executable folder, that's just the way to do it on a single user operating system.

For the rest I am right now a bit busy, so I cannot reply to it now.

**Comment by LynxAbraxas** [comment]
Thanks for the input, @MartinGuehmann . In relation to https://github.com/civctp2/civctp2/commit/2e0bdab46543030a6faf1900c58638578d9d9eec#diff-33dec90df1e3531b0d3d95257a65fbc0: Should I change the map file to be in `logs/` only for linux or should I revert all changes concerning the map-file in regard to https://github.com/civctp2/civctp2/pull/107#issuecomment-562970026?
I'd like to avoid postponing this PR (originating from end of 2018) again because due to the former postponing we already had the Linux debug-version broken again.

**Comment by MartinGuehmann** [comment]
> Thanks for the input, @MartinGuehmann . In relation to [2e0bdab#diff-33dec90df1e3531b0d3d95257a65fbc0](https://github.com/civctp2/civctp2/commit/2e0bdab46543030a6faf1900c58638578d9d9eec#diff-33dec90df1e3531b0d3d95257a65fbc0): Should I change the map file to be in `logs/` only for linux or should I revert all changes concerning the map-file in regard to [#107 (comment)](https://github.com/civctp2/civctp2/pull/107#issuecomment-562970026)?

Logically, the map files should all at one place. However, then you have to modify the Visual Studio project files, too. And check that everything works. Of course, you can move the Linux map file to its own folder like the logs folder but there I think it is a bit misplaced. Ideally, the map file is created by the compiler, but I just find a way to add the symbols to the executable and then extract them. In principle you could run nm from the command line ones the ctp2 executable has been created. Probably, should also be possible to call it from the makefile, unfortunately I am not familiar with that enough to just implement it. And so I didn't even tought about when I replicated this functionality of the Windows debug version.

The alternative is to write the map file to a temporary location and delete it when it is not needed anymore.

> I'd like to avoid postponing this PR (originating from end of 2018) again because due to the former postponing we already had the Linux debug-version broken again.

Then I should merge this before anything else, even the anything else is actually, ready.

**Comment by LynxAbraxas** [comment]
> In principle you could run nm from the command line ones the ctp2 executable has been created. Probably, should also be possible to call it from the makefile, unfortunately I am not familiar with that enough to just implement it. 

Yes, that I could implement in the `Dockerfile`, however for compiles outside docker it would be better placed in a `Makefile`. I had a look through the Makefiles and their primitives for autoconf and automake but could not find the install target. Any idea where that is defined or generated? @DEVoytas do you have some knowledge about this?

**Comment by LynxAbraxas** [comment]
Seems like I got it sorted out, at least https://github.com/civctp2/civctp2/pull/107/commits/83c5052e5375b6276035f6829dd38ab0f1599985 passes all tests (https://gitlab.com/LynxAbraxas/civctp2/pipelines/102405422).
@MartinGuehmann What do you think? Should I squash
2842fac..83c505?

**Comment by MartinGuehmann** [comment]
> Seems like I got it sorted out, at least [83c5052](https://github.com/civctp2/civctp2/commit/83c5052e5375b6276035f6829dd38ab0f1599985) passes all tests (https://gitlab.com/LynxAbraxas/civctp2/pipelines/102405422).
> @MartinGuehmann What do you think? Should I squash
> [2842fac](https://github.com/civctp2/civctp2/commit/2842fac5c5147915a29577333d1406e0650f05e5)..83c505?

Yes, I think you should squash the last three commits, since logically you move the map file creation from the executable to the built.

And if you are happy then, we can merge.

**Comment by LynxAbraxas** [comment]
OK, squashed and nm not installed for final DI. I'd say ready for merge. @MartinGuehmann what do you think?

**Comment by LynxAbraxas** [comment]
NB:
> I had a look through the Makefiles and their primitives for autoconf and automake but could not find the install target. 

That is because they are default tragets that get generated by `automake`. They can be extended with `*-local` or `*-hook`: https://www.gnu.org/software/automake/manual/html_node/Extending.html

**Comment by MartinGuehmann** [comment]
Then we can merge.

**Pull request merged**
