### PR TITLE
changes for FFmpeg-5 API (Dockerfile for building on Debian-12 (bookworm) and Ubuntu-23.10 (mantic))

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR addresses the issues of #412 and #352 which arise due to the API changes from FFmpeg-4 (ubuntu:latest, currently 22.04, jammy) to FFmpeg-5 (debian:latest, currently 12.2, bookworm) possibly also for FFmpeg-6 (ubuntu:rolling, currently 23.10 mantic). It also serves as a demo on how to base the GL-CI test on debian instead of ubuntu.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
This PR is marked WIP, because the changes for ubuntu:rolling (currently 23.10 mantic) compile (https://gitlab.com/LynxAbraxas/civctp2/-/pipelines/1077760343) but starting the game from the DI does neither work for the smoke tests (e.g.: https://gitlab.com/LynxAbraxas/civctp2/-/jobs/5569243554) nor locally due to new security measures of Xorg/Xvfb.

The commits upto [e0cff5d](https://github.com/civctp2/civctp2/pull/413/commits/e0cff5d3c6482ae83230dcf2756fcdcaeb3dce70) solve the issues of https://github.com/civctp2/civctp2/issues/412 and https://github.com/civctp2/civctp2/issues/352.

So far the base image for testing the build is ubuntu:latest, which does not point to the newest release of ubuntu (ubuntu:rolling), debian:latest being somewhere in between.
It would not be appropriate to use the static DI-tag ubuntu:23.04 (lunar) which would currently closer correspond to debian:latest.
So when ubuntu:latest becomes ubuntu:23.10, we'd need a solution for the problems with the smoke tests (concerning illegal access, the sound in Xvfb) or decide to build the GL-CI test on debian:latest (which at least used to be more "conservative" concerning packge versions and their dependencies).

**Comment by LynxAbraxas** [comment]
@williamd67: Do you remember which exact versions of `ffplay.c` you used as a base for 80965a59f2e43bcf8f7da5d30c185ceff53d4f97? It would be very helpful to know which commit of `ffplay.c` was used (and stripped) then (and which version FFmpeg was the default at that time in ubuntu) to decide which changes from the current [`ffplay.c`](https://github.com/FFmpeg/FFmpeg/blob/fbc7adba6742c4d33ae525a72881f456281b4c46/fftools/ffplay.c) should be ported to [`aui_sdlmovie.cpp`](https://github.com/civctp2/civctp2/blob/67532c1338ad8c0f8e943a6e04633782543fa06a/ctp2_code/ui/aui_sdl/aui_sdlmovie.cpp). In the comment I just found this:
https://github.com/civctp2/civctp2/blob/67532c1338ad8c0f8e943a6e04633782543fa06a/ctp2_code/ui/aui_sdl/aui_sdlmovie.cpp#L1-L5

**Comment by LynxAbraxas** [comment]
> This PR is marked WIP, because the changes for ubuntu:rolling (currently 23.10 mantic) compile (https://gitlab.com/LynxAbraxas/civctp2/-/pipelines/1077760343) but starting the game from the DI does neither work for the smoke tests (e.g.: https://gitlab.com/LynxAbraxas/civctp2/-/jobs/5569243554) nor locally due to new security measures of Xorg/Xvfb.

Turns out that this were not new security measures  but a SIGILL (illegal instruction) caused by a ud2 assembler instruction which is meant to fail (https://peeterjoot.wordpress.com/2010/05/26/a-fun-and-curious-dig-gcc-generation-of-a-ud2a-instruction-sigill/).
However, this time not due to a problem reported in d9b6fdc2 (though a similar one still existed upto 1867d37) but at:
https://github.com/civctp2/civctp2/blob/2037e527d6d79d840134e93e32f42a02852c4e1d/ctp2_code/ui/aui_sdl/aui_sdlui.cpp#L332

Since the build.log does not show any warnings for this file, it could be that the libsdl2 packages of ubuntu:mantic/nobel have this ud2 assembler instruction built into them. So either this is a bug there or newer libsdl2 ought to be used differently than currently implemented in the ctp2 code.
This should be tracked as its own issue (#417), because since May. 2024 ubuntu:latest points to ubuntu:nobel/22.04 and the monthly CI/CD test fail since then (https://gitlab.com/civctp2/civctp2/-/pipelines) due to the updated FFmpeg-5 API (which this PR is meant to address).
Therefore decided to stick to debian:latest/bookworm/12.7 here as base for the DIs and for testing with CI/CD.

**Comment by LynxAbraxas** [comment]
PR ready for merging since current state compiles fine and passes all CI/CD tests (https://gitlab.com/LynxAbraxas/civctp2/-/pipelines/1447371428)

**Comment by MartinGuehmann** [comment]
Checked it, compiles on my Kubuntu and also on Windows with Visual Studio 2017.

What an experience if you don't use Windows all day. It had to install three updates, of course one after the other, and after each Windows has to read start, which takes a while. Of course, after that some of the Windows spy stuff is switched on again. Windows explorer uses ribbons instead of a proper menu bar. The task bar suddenly got a search bar and whether app, of course without asking me whether I want that crap. And finally, the installer of Visual Studio forgot that Visual Studio was already installed, which caused some trouble using it. So I had to reinstall it. That is really unprofessional.

Anyway, this can go in.

**Pull request merged**
