### PR TITLE
Fix bitmap font assert on Linux

### PR DESCRIPTION
**Pull request by MartinGuehmann**
This silences an assert that shows up while loading a save game or opening the save dialog during a game. However, the problem seems to be deeper, in respect that the font handling in textfields hasn't been implemented completely.

### CODE REVIEW

**Comment by MartinGuehmann** [comment]
Looks like, I accidentally based it on my branch EnableDebugForLinux. Either I can figure out how to fix it or wait until pull request #79 is in.

**Comment by LynxAbraxas** [comment]
> Looks like, I accidentally based it on my branch EnableDebugForLinux. Either I can figure out how to fix it or wait until pull request #79 is in.

@MartinGuehmann  Had a look at your git-graph: https://github.com/MartinGuehmann/civctp2/network, I would suggest that you keep it in sync with https://github.com/civctp2/civctp2 as much as possible, e.g. after each merge of a PR do:

```
git checkout master
git pull upstream master # expecting you have a remote added named upstream pointing to https://github.com/civctp2/civctp2 you can also do git fetch followed by git merge or git reset if updating your local master would not be fast-forward.
git push origin master # expecting origin pointing to https://github.com/MartinGuehmann/civctp2/ you can also use --all --tag
```

Your current master on https://github.com/MartinGuehmann/civctp2/ is behind that of https://github.com/civctp2/civctp2 which could have lead to this. It's good to look at the current local graph with e.g. gitk, gitg or similar tools.

If this PR dependents on #79 logically, this should wait until #79 is in. If it only branches from `EnableDebugForLinux` unintentionally, you can rebase it on the newly syncted master with e.g. 

```
git checkout EnableDebugForLinux
git rebase master
```

That's the cool thing about git, you can juggle the commits around nearly unlimited, which is one reason there are no consecutive revision numbers as e.g. in svn. However, the general recommendation is that you should do the juggling only as long as the commits have not been pushed, i.e. published to others. Concerning ctp2 contributions, I would loosen this recommendation a bit an say that juggling commits is still OK for WIP-PRs (allowing force-push), but not any more for anything that is commited to master.

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann Had a look at your git-graph: https://github.com/MartinGuehmann/civctp2/network, I would suggest that you keep it in sync with https://github.com/civctp2/civctp2 as much as possible, e.g. after each merge of a PR do:
> 
> ```
> git checkout master
> git pull upstream master # expecting you have a remote added named upstream pointing to https://github.com/civctp2/civctp2 you can also do git fetch followed by git merge or git reset if updating your local master would not be fast-forward.
> git push origin master # expecting origin pointing to https://github.com/MartinGuehmann/civctp2/ you can also use --all --tag
> ```

Basically, that is what I did with my local master, I just used TortoiseGit for that. In the network you can see that my branches EnhanceeasterEggs, SaveGameCompatibiltySlicArray branches and your branch newCamelSprite branch off. FixBitmapFontAssert should have branched here, too. 

> Your current master on https://github.com/MartinGuehmann/civctp2/ is behind that of https://github.com/civctp2/civctp2 which could have lead to this. It's good to look at the current local graph with e.g. gitk, gitg or similar tools.

My current local master is at: Merge pull request #62 ... as it is civctp2 master. No, it happened, because I did not switch my local copy to master, and then I noticed when I had uploaded.

> If this PR dependents on #79 logically, this should wait until #79 is in. If it only branches from `EnableDebugForLinux` unintentionally, you can rebase it on the newly syncted master with e.g.
> 
> ```
> git checkout EnableDebugForLinux
> git rebase master
> ```

I don't think that it depends on EnableDebugForLinux. However, as far as I can it just silences the assert, and has no effect on the game itself. Of course, the effect could be so subtle that I don't see it.

This pull request fixes something that was revealed by the debug version. You get just a few of these asserts so that it does not keep you from using the debug version. That is unlike with the other assert, I fixed by figuring out that it did not even indicate an issue on Linux.

> That's the cool thing about git, you can juggle the commits around nearly unlimited, which is one reason there are no consecutive revision numbers as e.g. in svn. However, the general recommendation is that you should do the juggling only as long as the commits have not been pushed, i.e. published to others. Concerning ctp2 contributions, I would loosen this recommendation a bit an say that juggling commits is still OK for WIP-PRs (allowing force-push), but not any more for anything that is commited to master.

Actually, this is how you are doing, and that what I have done for pull request #90. That was originally, based on master, but this way it wouldn't convert the save games. So there it was necessary. But here, I don't feel it so important that it must be changed.

**Comment by LynxAbraxas** [comment]
> My current local master is at: Merge pull request #62 ... as it is civctp2 master. No, it happened, because I did not switch my local copy to master, and then I noticed when I had uploaded.

Hm, https://github.com/MartinGuehmann/civctp2/tree/master says: "This branch is 42 commits behind civctp2:master. " and master points to https://github.com/MartinGuehmann/civctp2/commit/4e54fce4631973a92117317bcb157cfae0507b2a

**Comment by LynxAbraxas** [comment]
I have the impression that your local git repos is not in sync with that of GH, not sure how TortoiseGit does things. What does `git push orgin --all -n` tell you? I would recommend to remove all branches of PRs that got merged already locally and remotely, see e.g. here: https://github.com/MartinGuehmann/civctp2/branches/active
`Merge-From-Linux-Branch` which was for #62.

**Comment by MartinGuehmann** [comment]
> I have the impression that your local git repos is not in sync with that of GH, not sure how TortoiseGit does things. What does `git push orgin --all -n` tell you?

Would `git push orgin --all -n` push my everything in my local working copy to the origin. That means the git repro I cloned my local working copy from? That would be civctp2/civctp2/master.

Anyway, I pushed the master of my local working copy to my remote clone. Now my remote master is even with that of civctp2. And for instance, EnhanceEasterEggs is two commits behind and four commits ahead. That is how it should be. Two commits from your camel sprite one for the pull request and one from the merge. And the four ahead are those that I wanna have merged. 

There are some branches that are ahead, but those are ether not merged, yet. Or have been abandoned. I just don't get why undo-segfault-change is one commit ahead. It got merged didn't it? I think that I reused the branch, as an experiment but also that should have been merged.

I would recommend to remove all branches of PRs that got merged already locally and remotely, see e.g. here: https://github.com/MartinGuehmann/civctp2/branches/active
> `Merge-From-Linux-Branch` which was for #62.

Yes, that is something I wanna do, I just haven't done it. After some time you have so many that it gets really confusing. But before, I wanna know why undo-segfault-change is one ahead.

**Comment by LynxAbraxas** [comment]
Looks good now.

> Would git push orgin --all -n push my everything in my local working copy to the origin. That means the git repro I cloned my local working copy from? That would be civctp2/civctp2/master.

In standard setup in the local (on your PC) clone of civctp2 you would have the remote `origin` pointing to your fork on GH, i.e. https://github.com/MartinGuehmann/civctp2/ and `upstream` to  https://github.com/civctp2/civctp2/. You can have other remotes like e.g. `GL` pointing to https://gitlab.com/civctp2/civctp2. Check with `git remote -v`. You can fetch each remote separately (e.g. `git fetch upstream`) but you can only push to those you have write-access to. `git push origin --all` would push all your local branches to origin, with -n it will only tell you what it would do. To see what your local branches are use e.g. `git branch -v`, you can add -a to see branches of the remotes. You can see them all also with `gitk --all`

> I just don't get why undo-segfault-change is one commit ahead. It got merged didn't it? I think that I reused the branch, as an experiment but also that should have been merged.

Your https://github.com/MartinGuehmann/civctp2/commit/2e51cb42b681b8ba68231dcf14659fa86a78a94a
is already merged into master:
 https://github.com/civctp2/civctp2/commit/9a1ab16704ccb10c23d14a679adff21501fcd910
and was probably cherry-picked or similar and included with a different PR at times of disorder;-) So I would say can can savely just delete that branch with e.g. 

```
git push origin :undo-segfault-change # assuming origin points to  https://github.com/MartinGuehmann/civctp2/
git branch -D undo-segfault-change
```

**Comment by MartinGuehmann** [comment]
I think, I got rid of all these branches, I deleted undo-segfault-change from the pull request and another branch concerning the government selection crash, which was dropped in favor of three PR.

**Comment by LynxAbraxas** [comment]
Looks nice and clean now. I noticed though that the linux branch still contains two commits that should not be part of it. @MartinGuehmann please have a look at https://github.com/civctp2/civctp2/pull/37#issuecomment-460081218

**Comment by MartinGuehmann** [comment]
I cared about the Linux branch and then this can go in.

**Comment by LynxAbraxas** [comment]
Can confirm that it solves https://github.com/civctp2/civctp2/pull/79#issuecomment-464270990, if rebased onto current master. So, I would recommend rebasing before merging this PR, e.g.

```
git checkout FixBitmapFontAssert
git rebase master
git push origin -f
```
and then accept this PR.

**Comment by MartinGuehmann** [comment]
> Can confirm that it solves [#79 (comment)](https://github.com/civctp2/civctp2/pull/79#issuecomment-464270990), if rebased onto current master. So, I would recommend rebasing before merging this PR, e.g.
> 
> ```
> git checkout FixBitmapFontAssert
> git rebase master
> git push origin -f
> ```
> and then accept this PR.

I just accepted it, before without rebasing, in principle I can revert it, and and rebase it. What do you thinl of the current tree? Would it have advantages?

**Comment by LynxAbraxas** [comment]
Well, avoiding rebasing always has the advantage that you do not rewrite history, you only add. The current merge commit for this PR has the exact same content as a rebase would have, so all fine. Thanks again for the efforts!

**Pull request merged**
