### PR TITLE
Debug breaking no-piracy treaty

### LINKED ISSUE #152: Breaking no-piracy treaty not possible
It seems that currently it is not possible to break a no-piracy treaty, not even by declaring war. @MartinGuehmann could it be that this was broken by the remedy to #75: #127?

I get the message that ask me if I want to break the treaty with the Incans, but clicking yes has no effect:

ss_2019-06-20_23:50:11

The order to pirate comes here in case of a no-piracy treaty
https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_code/gs/gameobj/ArmyData.cpp#L5911-L5927
which then leads to here
https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_data/default/gamedata/script.slc#L1465
where I wonder if the remedy in #127 now prevents that order to be executed. However, since the order is not bound to a change in position, this should not be the case.
Any idea what could be the problem?

### PR DESCRIPTION
**Pull request by LynxAbraxas**
PR to resolve #152.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
> I just worry what context->GetPlayer(1) returns if no player is in the context. Is it -1 or 32 or whatever? "if(!g_player[context->GetPlayer(1)])" is not defined if context->GetPlayer(1)] returns -1. It shouldn't crash, because you don't dereference a pointer.

@MartinGuehmann  It seems that I do not get into the for-loop
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/slic/slicfunc.cpp#L4543
so I guess `g_player[pirate]->m_agreed->Num()` is not as high as it should be, but why?

**Comment by MartinGuehmann** [comment]
Do you don't get to the for-loop or don't you get into the for-loop? The function could exit before. So what are the values for pirate and victim? And the value for g_player[pirate]->m_agreed->Num()?

**Comment by LynxAbraxas** [comment]
With https://github.com/civctp2/civctp2/pull/154/commits/869001ac60ee343195bbb51174c6c43f20f2ba7f I get `slicfunc.cpp L4542: 1, 12, 0`
and no more, so `pirate` and `victim` seem to be fine but there seems to be no agreement stored with `g_player[pirate]->m_agreed->Num() == 0`

**Comment by LynxAbraxas** [comment]
Checked if `victim` owns the agreement https://github.com/civctp2/civctp2/pull/154/commits/d03baac1b20d5a4448e79e15bb7ea06f125a8c47 but also then `g_player[pirate]->m_agreed->Num() == 0`.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Could this be the problem:
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/Agreement.cpp#L26-L30
Isn't 
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/Agreement.cpp#L28
creating a new instance that would have no references to remove?
Why not call `RemoveAllReferences` directly?

**Comment by LynxAbraxas** [comment]
Seems I've been interpreting the pirate flag icon in the diplomacy window wrongly. There it means the Incans agreed to not pirate my rountes:

ss_2019-06-23_14:41:54

Whereas if I agree to not pirate, that icon appears in the Intelligence window, as e.g. here for the Sumer:

ss_2019-06-23_14:41:18

However, if I pirate a Sumer trade route, I do not get asked by
https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_data/default/gamedata/script.slc#L1456-L1468
before pirating, i.e. pirating is executed without any question and afterwards I only get the message for
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_data/default/gamedata/script.slc#L2914-L2917

**Comment by LynxAbraxas** [comment]
Odd, if I use the cheat-mode to become the Incans and establish an embassy in a Persian city the diplomacy manager and the intelligence window look as such:

ss_2019-06-23_15:04:24

The Incans have only the cease-fire treaty from the Persians but the Persians have a no-piracy and leave-land treaty from the Incans.

If I restart the same base game, offer the Incans a no-piracy treaty as Persian I get:

ss_2019-06-23_16:39:18

I.e. each has a no-piracy treaty with the other and if the Persians then try to pirate, the message asking for breaking the no-piracy treaty appears (as expected) but hitting yes has no effect (neither with https://github.com/civctp2/civctp2/pull/154/commits/d03baac1b20d5a4448e79e15bb7ea06f125a8c47 nor as originally https://github.com/civctp2/civctp2/pull/154/commits/c253aa0ad78c4229184e962cf1c32bba7c5c4a58)

Becoming the Incans again, establishing an embassy again the listing are like:
ss_2019-06-23_16:43:11

Then pirating a Persian route makes the game crash.

**Comment by LynxAbraxas** [comment]
https://github.com/civctp2/civctp2/pull/154/commits/3e6c42ba622fd4fecc19f5fb4277e532350dac1a does seem to solve the issue, that the Incans have to respect the no-piracy treaty with the Persians (not the other way round), i.e. with https://github.com/civctp2/civctp2/pull/154/commits/3e6c42ba622fd4fecc19f5fb4277e532350dac1a the Persians can pirate an Incan route.

Still the problem that a no-piracy treaty cannot be broken remains.
It seems that even for treaties established in the very same game (without saving and loading) do not lead to `g_player[pirate]->m_agreed->Num() > 0` from what ever side nor with other civs (tested Aborigine -> Incans).

**Comment by LynxAbraxas** [comment]
@MartinGuehmann any idea where the agreement matrix used in `ArmyData.cpp`
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L5911-L5914
for asking to break the treaty could get out of sync with the agreement list of each player used in `slicfunc.cpp`
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/slic/slicfunc.cpp#L4543
for breaking a standing treaty then?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann any idea where the agreement matrix used in `ArmyData.cpp`
> https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L5911-L5914
> 
> 
> for asking to break the treaty could get out of sync with the agreement list of each player used in `slicfunc.cpp`
> https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/slic/slicfunc.cpp#L4543
> 
> 
> for breaking a standing treaty then?

Well, I would say m_agreed is a leftover of CTP1, so you stumbled on a bug of Activision's release version. If you wanna know the stuff is used, you could use Visual Studio on Windows, or grep on Linux from the CTP2 base directory:

```
grep -rnI '.' -e 'AgreementMatrix::s_agreements' --include *.cpp --include *.hpp --include *.c --include *.h --include *.y --include *.l ./
grep -rnI '.' -e 'm_agreed' --include *.cpp --include *.hpp --include *.c --include *.h --include *.y --include *.l ./
```

The m_agreed gives me:

```
./ctp2_code/gs/gameobj/Player.cpp:347:  m_agreed = new DynamicArray<Agreement>;
./ctp2_code/gs/gameobj/Player.cpp:633:  m_agreed = new DynamicArray<Agreement>;
./ctp2_code/gs/gameobj/Player.cpp:684:  delete m_agreed;
./ctp2_code/gs/gameobj/Player.cpp:831:  m_agreed->Serialize(archive) ;
./ctp2_code/gs/gameobj/Player.cpp:4141: sint32 const    agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4144:         if ((m_agreed->Get(i).GetAgreement() == agreement))
./ctp2_code/gs/gameobj/Player.cpp:4145:                 if ((m_agreed->Get(i).GetRecipient() == otherParty) || (m_agreed->Get(i).GetOwner() == otherParty))
./ctp2_code/gs/gameobj/Player.cpp:4146:                         return m_agreed->Get(i);
./ctp2_code/gs/gameobj/Player.cpp:4154: sint32 const    agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4157:         if ((m_agreed->Get(i).GetAgreement() == agreement))
./ctp2_code/gs/gameobj/Player.cpp:4158:                 return m_agreed->Get(i);
./ctp2_code/gs/gameobj/Player.cpp:4166: sint32 const    agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4169:         if ((m_agreed->Get(i).GetRecipient() == otherParty) || (m_agreed->Get(i).GetOwner() == otherParty))
./ctp2_code/gs/gameobj/Player.cpp:4170:                 return m_agreed->Get(i);
./ctp2_code/gs/gameobj/Player.cpp:4179:// m_agreed is not used, its functionality is found in the Aggreement matrix
./ctp2_code/gs/gameobj/Player.cpp:4192: agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4195:         agree = m_agreed->Get(i) ;
./ctp2_code/gs/gameobj/Player.cpp:4337: agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4340:         Agreement       a = m_agreed->Get(i) ;
./ctp2_code/gs/gameobj/Player.cpp:4343:                 if ((m_agreed->Get(i).GetRecipient() == otherParty) || (m_agreed->Get(i).GetOwner() == otherParty))
./ctp2_code/gs/gameobj/Player.cpp:4498: sint32 i, n = m_agreed->Num();
./ctp2_code/gs/gameobj/Player.cpp:4499: DynamicArray<Agreement>   agreed(*m_agreed);
./ctp2_code/gs/gameobj/Player.cpp:4542: m_agreed->Del(a);
./ctp2_code/gs/gameobj/Player.cpp:4547: for(sint32 i = m_agreed->Num() - 1; i >= 0; i--) {
./ctp2_code/gs/gameobj/Player.cpp:4548:         Agreement kill = m_agreed->Access(i);
./ctp2_code/gs/gameobj/Player.cpp:4555: m_agreed->Insert(a) ;
./ctp2_code/gs/gameobj/Player.cpp:4940: sint32 n = m_agreed->Num();
./ctp2_code/gs/gameobj/Player.cpp:4942:         m_agreed->Access(i).Dump(i);
./ctp2_code/gs/gameobj/Player.cpp:6968: if(m_agreed) {
./ctp2_code/gs/gameobj/Player.cpp:6969:         while(m_agreed->Num() > 0) {
./ctp2_code/gs/gameobj/Player.cpp:6970:                 m_agreed->Access(0).Kill();
./ctp2_code/gs/gameobj/player.h:323:    DynamicArray<Agreement>          *m_agreed;                   // Serialized
./ctp2_code/gs/gameobj/player.h:533:    DynamicArray<Agreement> *GetAgreements(void) const { return (m_agreed) ; }
./ctp2_code/gs/slic/slicfunc.cpp:4498:  for(i = g_player[unitOwner]->m_agreed->Num() - 1; i >= 0; i--) {
./ctp2_code/gs/slic/slicfunc.cpp:4499:          Agreement ag = g_player[unitOwner]->m_agreed->Access(i);
./ctp2_code/gs/slic/slicfunc.cpp:4543:  for(i = g_player[pirate]->m_agreed->Num() - 1; i >= 0; i--) {
./ctp2_code/gs/slic/slicfunc.cpp:4544:          Agreement ag = g_player[pirate]->m_agreed->Access(i);
./ctp2_code/net/general/net_agreement.cpp:91:           g_player[m_data->m_owner]->m_agreed->Insert(ag);
./ctp2_code/net/general/net_agreement.cpp:92:           g_player[m_data->m_recipient]->m_agreed->Insert(ag);
./ctp2_code/gs/gameobj/Player.cpp:347:  m_agreed = new DynamicArray<Agreement>;
./ctp2_code/gs/gameobj/Player.cpp:633:  m_agreed = new DynamicArray<Agreement>;
./ctp2_code/gs/gameobj/Player.cpp:684:  delete m_agreed;
./ctp2_code/gs/gameobj/Player.cpp:831:  m_agreed->Serialize(archive) ;
./ctp2_code/gs/gameobj/Player.cpp:4141: sint32 const    agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4144:         if ((m_agreed->Get(i).GetAgreement() == agreement))
./ctp2_code/gs/gameobj/Player.cpp:4145:                 if ((m_agreed->Get(i).GetRecipient() == otherParty) || (m_agreed->Get(i).GetOwner() == otherParty))
./ctp2_code/gs/gameobj/Player.cpp:4146:                         return m_agreed->Get(i);
./ctp2_code/gs/gameobj/Player.cpp:4154: sint32 const    agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4157:         if ((m_agreed->Get(i).GetAgreement() == agreement))
./ctp2_code/gs/gameobj/Player.cpp:4158:                 return m_agreed->Get(i);
./ctp2_code/gs/gameobj/Player.cpp:4166: sint32 const    agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4169:         if ((m_agreed->Get(i).GetRecipient() == otherParty) || (m_agreed->Get(i).GetOwner() == otherParty))
./ctp2_code/gs/gameobj/Player.cpp:4170:                 return m_agreed->Get(i);
./ctp2_code/gs/gameobj/Player.cpp:4179:// m_agreed is not used, its functionality is found in the Aggreement matrix
./ctp2_code/gs/gameobj/Player.cpp:4192: agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4195:         agree = m_agreed->Get(i) ;
./ctp2_code/gs/gameobj/Player.cpp:4337: agreedNum = m_agreed->Num() ;
./ctp2_code/gs/gameobj/Player.cpp:4340:         Agreement       a = m_agreed->Get(i) ;
./ctp2_code/gs/gameobj/Player.cpp:4343:                 if ((m_agreed->Get(i).GetRecipient() == otherParty) || (m_agreed->Get(i).GetOwner() == otherParty))
./ctp2_code/gs/gameobj/Player.cpp:4498: sint32 i, n = m_agreed->Num();
./ctp2_code/gs/gameobj/Player.cpp:4499: DynamicArray<Agreement>   agreed(*m_agreed);
./ctp2_code/gs/gameobj/Player.cpp:4542: m_agreed->Del(a);
./ctp2_code/gs/gameobj/Player.cpp:4547: for(sint32 i = m_agreed->Num() - 1; i >= 0; i--) {
./ctp2_code/gs/gameobj/Player.cpp:4548:         Agreement kill = m_agreed->Access(i);
./ctp2_code/gs/gameobj/Player.cpp:4555: m_agreed->Insert(a) ;
./ctp2_code/gs/gameobj/Player.cpp:4940: sint32 n = m_agreed->Num();
./ctp2_code/gs/gameobj/Player.cpp:4942:         m_agreed->Access(i).Dump(i);
./ctp2_code/gs/gameobj/Player.cpp:6968: if(m_agreed) {
./ctp2_code/gs/gameobj/Player.cpp:6969:         while(m_agreed->Num() > 0) {
./ctp2_code/gs/gameobj/Player.cpp:6970:                 m_agreed->Access(0).Kill();
./ctp2_code/gs/gameobj/player.h:323:    DynamicArray<Agreement>          *m_agreed;                   // Serialized
./ctp2_code/gs/gameobj/player.h:533:    DynamicArray<Agreement> *GetAgreements(void) const { return (m_agreed) ; }
./ctp2_code/gs/slic/slicfunc.cpp:4498:  for(i = g_player[unitOwner]->m_agreed->Num() - 1; i >= 0; i--) {
./ctp2_code/gs/slic/slicfunc.cpp:4499:          Agreement ag = g_player[unitOwner]->m_agreed->Access(i);
./ctp2_code/gs/slic/slicfunc.cpp:4543:  for(i = g_player[pirate]->m_agreed->Num() - 1; i >= 0; i--) {
./ctp2_code/gs/slic/slicfunc.cpp:4544:          Agreement ag = g_player[pirate]->m_agreed->Access(i);
./ctp2_code/net/general/net_agreement.cpp:91:           g_player[m_data->m_owner]->m_agreed->Insert(ag);
./ctp2_code/net/general/net_agreement.cpp:92:           g_player[m_data->m_recipient]->m_agreed->Insert(ag);
```
I just don't get why the output is doubled.

By the way, synchronizing two lists just sound wrong, you just should store information at one place so that you don't have to synchronize it. :D

So the solution is to use the agreement matrix in the slic function.

**Comment by LynxAbraxas** [comment]
> Well, I would say m_agreed is a leftover of CTP1, so you stumbled on a bug of Activision's release version.

Thanks for pointing that out.

> So the solution is to use the agreement matrix in the slic function.

I'll try that. What about all the other places where `m_agreed` is used?

> I just don't get why the output is doubled.

What do you mean with doubled?

**Comment by LynxAbraxas** [comment]
@MartinGuehmann do you know anything of the background for this comment:
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/Player.cpp#L4179

**Comment by MartinGuehmann** [comment]
> I'll try that. What about all the other places where `m_agreed` is used?

Of course you can check all the context within the files, but from the output, I can only see that agreements are added in the net file. That is only used to synchronizes the game state over the network in network games. There is no other place where an agreement is added.

From the grep output, I would say, the remaining code initializes the agreement array, we have some access code, some code to delete the agreements. And some stuff that saves and loads the agreements. The last stuff causes some trouble to remove, since we don't want to change the savegame format.

In principle, this is unused code that just confuses people and makes them work harder then they should and maybe also make the executable bigger and the game slower. Even, so I think the last things are small issues.

> > I just don't get why the output is doubled.
> 
> What do you mean with doubled?

Look at the output, after "./ctp2_code/net/general/net_agreement.cpp:92:" everything is reported again.

> @MartinGuehmann do you know anything of the background for this comment:
> https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/Player.cpp#L4179

Well, I just looked at the grep output, and from that I would agree with the comment. I assume Fromafar looked at the code and added that comment. But I already suspected this, before I grepped m_agreed. Since so far I haven't seen any other method then the agreement matrix to access the agreements.

Actually, this agreement matrix is also a waste of space, it does not hold pointers on the agreements, but the agreements themselves as objects. So that means instead of Null pointers, which are 4 bytes or 8 bytes depending on your compiler, you have empty objects, which a probably hundreds of bytes. Let's say you have 32 players in the game then you have 32*32*num_of_agreements in that matrix. So not very nice.

**Comment by LynxAbraxas** [comment]
OK with https://github.com/civctp2/civctp2/pull/154/commits/a8553243f9465ac229ec3a1b2d1dc014c422f196 getting further. Apparently the message `004NoPiracyBrokenByYou` was never part of the code but is called in case of `AGREEMENT_TYPE_NO_PIRACY` by
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/AgreementData.cpp#L1099-L1206
`find -type f -exec grep -Hn RecipientIsViolating {} \;` yields:
```
./ctp2_code/gs/slic/slicfunc.cpp:4512:			ag.AccessData()->RecipientIsViolating(unitOwner, TRUE);
./ctp2_code/gs/slic/slicfunc.cpp:4562:	    ag.AccessData()->RecipientIsViolating(pirate, TRUE);
./ctp2_code/gs/gameobj/AgreementData.cpp:1099:void AgreementData::RecipientIsViolating(PLAYER_INDEX curPlayer, BOOL force)
./ctp2_code/gs/gameobj/AgreementData.cpp:1284:					RecipientIsViolating(m_owner);
./ctp2_code/gs/gameobj/AgreementData.cpp:1310:						RecipientIsViolating(m_owner);
./ctp2_code/gs/gameobj/AgreementData.cpp:1321:					RecipientIsViolating(m_owner);
./ctp2_code/gs/gameobj/AgreementData.cpp:1371:					RecipientIsViolating(m_owner);
./ctp2_code/gs/gameobj/AgreementData.cpp:1421:					RecipientIsViolating(m_recipient);
./ctp2_code/gs/gameobj/AgreementData.cpp:1447:						RecipientIsViolating(m_recipient);
./ctp2_code/gs/gameobj/AgreementData.cpp:1458:					RecipientIsViolating(m_recipient);
./ctp2_code/gs/gameobj/AgreementData.cpp:1486:					RecipientIsViolating(m_recipient);
./ctp2_code/gs/gameobj/AgreementData.cpp:1509:					RecipientIsViolating(m_recipient);
./ctp2_code/gs/gameobj/ArmyData.cpp:9961:					ag.AccessData()->RecipientIsViolating(cell->GetOwner(), true);
./ctp2_code/gs/gameobj/AgreementData.h:137:	void RecipientIsViolating(PLAYER_INDEX curPlayer, BOOL forceBreak = FALSE);
./ctp2_code/net/general/net_action.cpp:1845:					ag.AccessData()->RecipientIsViolating(ag.GetOwner(), TRUE);
./ctp2_code/net/general/net_info.cpp:1615:				ag.AccessData()->RecipientIsViolating((PLAYER_INDEX)m_data2, TRUE);
```
of which I think no other case ever got called. `DoLeaveOurLandsCheck` is commented to be a left over from CTP1
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L9918-L9967

@MartinGuehmann any idea on how the AI should be informed here
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/AgreementData.cpp#L1167-L1173
or is there another place where this happens with CTP2?

**Comment by MartinGuehmann** [comment]
> of which I think no other case ever got called. `DoLeaveOurLandsCheck` is commented to be a left over from CTP1

Well, that's what the comment says, and it only says "probably". So, I still would check if there is anything that it calls.
 https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L9918-L9967
> 
> @MartinGuehmann any idea on how the AI should be informed here
> https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/AgreementData.cpp#L1167-L1173
> 
> 
> or is there another place where this happens with CTP2?

Maybe it is something like:
> ag.AccessData()->RecipientIsViolating(cell->GetOwner(), true);

Well, you still would have to check what RecipientIsViolating does.

**Comment by LynxAbraxas** [comment]
> Well, you still would have to check what RecipientIsViolating does.

Currently, it sends a message to each party telling about the violation and removes the agreement from `g_theAgreementPool`.

**Comment by LynxAbraxas** [comment]
I have the impression that `AgreementData.cpp` ought to be removed. Getting the agreement as in `diplomat.cpp`, the returned object is not compatible with the former type and therefore `ag.AccessData()` is not defined.
@MartinGuehmann any idea on what level to best solve this problem? How, where is agreement violation handled in ohter cases?

**Comment by LynxAbraxas** [comment]
Seems like the more important treaties are handled here:
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/agreementmatrix.cpp#L335-L368
Any objection in moving 
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/AgreementData.cpp#L1099-L1206
there?

**Comment by LynxAbraxas** [comment]
I guess these are the CTP2 types:
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/diplomattypes.h#L93-L151
while these are the CTP1 types:
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/DiplomaticTypes.h#L7-L40
So, ideally each agreement from 
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/diplomattypes.h#L93-L151
should be handled here
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/agreementmatrix.cpp#L335-L368
and then used instead of
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/AgreementData.cpp#L1099-L1206

**Comment by LynxAbraxas** [comment]
It seems that violating a no-piracy treaty should end up here for CTP2:
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/diplomat.cpp#L1022-L1032
apparently it does not but instead gets routed to the CTP1 code.

**Comment by MartinGuehmann** [comment]
> I have the impression that `AgreementData.cpp` ought to be removed. Getting the agreement as in `diplomat.cpp` ([938727f](https://github.com/civctp2/civctp2/commit/938727f5e5b72e904cf17eb47d85ab8dbcde2957)), the returned object is not compatible with the former type and therefore `ag.AccessData()` is not defined.
> @MartinGuehmann any idea on what level to best solve this problem?

As far as I can see, AgreementPool, AgreementData, and Agreement, are left overs, in principle their header and source files can also go, we just have to check the saving, weather it would have some influences about the save game format. But if there are no AgreementData objects in the game then it should be fine.

> How, where is agreement violation handled in ohter cases?

I guess that's up to you to figure out, but I guess that the AgreementMatrix has some methods to handle this, or some code that interacts with the AgreementMatrix does it.

**Comment by LynxAbraxas** [comment]
I think I found the source of the problem. This
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/regardevent.cpp#L246-L264
get set with the pirating army
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/regardevent.cpp#L1186-L1188
and thereby leads to
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/diplomat.cpp#L1022-L1032

So all this
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L5903-L5929
seems to be a left-over from CTP1 (which was probably never noticed because pirating wasn't working properly before #127) and disabling that code https://github.com/civctp2/civctp2/pull/154/commits/32fddcc4327436c7d2f4a0333ff3ce01dc43e685 then leads to the proper CTP2 behaviour:

Here, the Persians have a `PROPOSAL_REQUEST_STOP_PIRACY` accepted by the Incans
ss_2019-06-26_09:40:56
as Persian offering them to stop piracy
ss_2019-06-26_09:41:27
leads to  `PROPOSAL_OFFER_STOP_PIRACY` for the Incans
ss_2019-06-26_09:41:48
Then deciding to pirate this sweet spot of 10 trade routes including Incan routes
ss_2019-06-26_09:42:28
leads to the CTP2 message
ss_2019-06-26_09:46:46
Also the stop-piracy agreements are gone for __both__ sides.
I have not tested yet if high-level pacts 
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/diplomat.cpp#L1029-L1031
are canceled by this.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann do you think it is save to remove all this
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L5903-L5929
I am wondering what the if-statement
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L5903-L5906
was neeeded for.
Do we need to somehow care for doing this
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/slic/slicfunc.cpp#L4549-L4552
for CTP2?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann do you think it is save to remove all this
> https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L5903-L5929
> 

I thought that this was the message that asked you, whether you really want to pirate that route, because you have a no pirate agreement. So therefore, you would like to keep it.

> 
> I am wondering what the if-statement
> https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/ArmyData.cpp#L5903-L5906
> 
> 
> was neeeded for.

That is to make sure that you only send the message to human players. I think in other cases the system just removes these messages for robots, but in this case the message has a question a human should answers. An AI player can just continue, without being bothered by the question.

> Do we need to somehow care for doing this
> https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/slic/slicfunc.cpp#L4549-L4552
> 
> 
> for CTP2?

That must also be handles, because it is network code and synchronizes the state of the game over the net. Right now we cannot really test things that go over the network. But at least should have code that transfers the data that should be transferred. Even so it is not super well tested.

Well, I must admit that this might be a bit dangerous. Right now I don't know what the state of multiplayer is.

**Comment by LynxAbraxas** [comment]
> I thought that this was the message that asked you, whether you really want to pirate that route, because you have a no pirate agreement. So therefore, you would like to keep it.

Yes, and I would generally like this kind of question because remebering all this is hard, especially over a few days of a break in playing, but this message is leading to the CTP1 code that then leads to a dead end.

Ideally such a question message should also be sent to a player if a unit/army move would violate a withdraw troops agreement. However, all question messages that I stumbled upon during this debug were CTP1. It seems the CTP2 way is to expect that a player rembers this (or was not implemented due to lack of time/programmers). We could implement this for CTP2 with the CTP1 messages, i.e. moving
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/gs/gameobj/AgreementData.cpp#L1099-L1206
to e.g.
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/agreementmatrix.cpp#L335-L368
which so far only handles `PROPOSAL_TREATY*` but not `PROPOSAL_REQUEST*` or `PROPOSAL_OFFER*` of
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/diplomattypes.h#L93-L151

**Comment by LynxAbraxas** [comment]
The cancelling of pacts
https://github.com/civctp2/civctp2/blob/fd65451326ffd76e46e0c2ed5015fb7876d5af0e/ctp2_code/ai/diplomacy/diplomat.cpp#L1029-L1031
also works. 
With stop-piracy and a trade-pact
ss_2019-06-26_22:56:06
pirating an Incan route
ss_2019-06-26_22:56:24
cancels all agreements up to cease-fire, even with a special message concerning the pact
ss_2019-06-26_22:57:09

**Comment by LynxAbraxas** [comment]
Tested this for a while and seems to work just as expected, so good to go in. I opened #157 to track the ideas for implementing CTP2 question messages in case an agreement would be violated by the intended action.

**Comment by MartinGuehmann** [comment]
> Tested this for a while and seems to work just as expected, so good to go in. I opened #157 to track the ideas for implementing CTP2 question messages in case an agreement would be violated by the intended action.

OK, then we are done and this can go in.

**Pull request merged**
