### PR TITLE
Unit control-panel improvements

### PR DESCRIPTION
**Pull request by williamd67**
This pull-request changes the unit control-panel in such way that next-button always goes to the next unmoved unit. The other displays can be showed by clicking on symbols, such as stack, army- and/or cargo-symbol. It also uses all the space of the background images.

### CODE REVIEW

**Comment by williamd67** [comment]
Before
Screenshot from 2021-05-11 20-08-02
After
Screenshot from 2021-05-11 20-10-50

**Comment by williamd67** [comment]
Before:
Screenshot from 2021-05-19 18-10-05
Screenshot from 2021-05-19 18-10-25

After:
Screenshot from 2021-05-19 17-51-26
Screenshot from 2021-05-19 17-51-37
Screenshot from 2021-05-19 17-51-50
Screenshot from 2021-05-19 17-53-41

**Comment by williamd67** [comment]
Navigation in army and transport works now as follows.
In army-selection panel:
Screenshot from 2021-05-22 13-25-26
click on an unit. This opens the unit-selection panel, where the army-icon is shown:
Screenshot from 2021-05-22 13-25-39
In case it is a transport, the unit can be clicked to open the transport-selection-panel:
Screenshot from 2021-05-22 13-26-10
To go back to the unit-selection-panel of the chosen transport, the transport icon can be clicked. This results in the unit-selection-panel to be re-opened:
Screenshot from 2021-05-22 13-30-10
and to go back to the army-selection-panel, the army-icon can be clicked. This results in the army-selection-panel to be re-opened:
Screenshot from 2021-05-22 13-25-26

**Comment by williamd67** [comment]
Number of units that are on the same cell is shown on the unit-control-panel (stack-size):
Screenshot from 2021-05-22 18-10-20
Screenshot from 2021-05-22 18-10-37

**Comment by williamd67** [comment]
Fuel gauge as it was drawn in original picture:
Screenshot from 2021-05-22 23-36-58
Screenshot from 2021-05-22 23-37-55
Screenshot from 2021-05-22 23-35-25
The red state (alarm) will be blinking for extra attention.

Let me know what you think about this.

**Comment by williamd67** [comment]
I have no open issues any more.

**Comment by LynxAbraxas** [comment]
Finally came about to test this. Compiles fine and changes appear to work as described. Though the new fuel gauge looks cool, I'm not sure if I preferred the former style.
Many thanks @williamd67 for these tunings.
Can be merged in my opinion. @MartinGuehmann what do you think?

**Comment by MartinGuehmann** [comment]
Then let's merge.

**Pull request merged**
