### PR TITLE
WIP: Corrections to goals

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR is meant for some corrections/improvements to the goal code.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
I have the impression that the additions of 00752a6233c710add9d98111d569ba224367d9ae do check if the player has a wonder that forbids to install embassies but the code that then checks if the wonder is obsolete only checks if that player has a wonder that is obsolete not if that particular wonder is obsolete. The code is from
https://github.com/civctp2/civctp2/blob/71571fc29255a13215a289e00668ad055e776f46/ctp2_code/gs/gameobj/ArmyData.cpp#L3566-L3577
which seems to suffer the same problem. It seems there is no code that would return the current wonder that forbids the creation of embassies (probably because that could be multiple wonders).

**Comment by LynxAbraxas** [comment]
Concerning #256, I wonder what the AI uses for determining if a unit/army should go for pirating just the seen cell info or the global map info (as available to the human player int this particular case). Appropriate and fair for general orders would be the unseen cell info but that does not exist so far for trade routes.
`Goal::IsTargetImmune` only checks of the target city has trade routes
https://github.com/civctp2/civctp2/blob/71571fc29255a13215a289e00668ad055e776f46/ctp2_code/ai/strategy/goals/Goal.cpp#L2920-L2927
I wonder though where the target city comes from in that case where basically every position on the route is equally suitable (without #117) for pirating.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Do you have any answers concerning the cell info used for pirating goals?

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Any idea where and how one could place a check for the intercept-trade-goal (pirate-goal) such that the AI does not pirate routes it is the receiver of (i.e. gets the bonus, see https://github.com/civctp2/civctp2/issues/192#issuecomment-570716436)?
Should that go here
https://github.com/civctp2/civctp2/blob/71571fc29255a13215a289e00668ad055e776f46/ctp2_code/ai/strategy/goals/Goal.cpp#L3087-L3105
or here
https://github.com/civctp2/civctp2/blob/71571fc29255a13215a289e00668ad055e776f46/ctp2_code/ai/strategy/goals/Goal.cpp#L1050-L1091

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann Any idea where and how one could place a check for the intercept-trade-goal (pirate-goal) such that the AI does not pirate routes it is the receiver of (i.e. gets the bonus, see [#192 (comment)](https://github.com/civctp2/civctp2/issues/192#issuecomment-570716436))?
> Should that go here
> https://github.com/civctp2/civctp2/blob/71571fc29255a13215a289e00668ad055e776f46/ctp2_code/ai/strategy/goals/Goal.cpp#L3087-L3105
> 
> 
> or here
> https://github.com/civctp2/civctp2/blob/71571fc29255a13215a289e00668ad055e776f46/ctp2_code/ai/strategy/goals/Goal.cpp#L1050-L1091

That is a tricky question, for sure it is not the second one, because that just selects the target position, but does not select whether the AI should go for that trade route. The problem is that you have here two target owners. And thus both must be checked. I tend to the first one, but I cannot exclude that there are better places.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann  any idea why https://github.com/civctp2/civctp2/commit/00752a6233c710add9d98111d569ba224367d9ae might not lead to the disired effect that diplomats of other civs do not go for installing an embassy in one of my cities? I have the "forbidden city" wonder and no wonder that is obsolete (and the action of installing an embassy also always fails for the other civs, but the AI keeps trying).

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann any idea why [00752a6](https://github.com/civctp2/civctp2/commit/00752a6233c710add9d98111d569ba224367d9ae) might not lead to the disired effect that diplomats of other civs do not go for installing an embassy in one of my cities? I have the "forbidden city" wonder and no wonder that is obsolete (and the action of installing an embassy also always fails for the other civs, but the AI keeps trying).

Well, the code seems to the AI from trying to establish embassies, if you have the forbidden wonder and no wonder that is obsolete. Obviously, that isn't what you want, but for testing it should be fine.

You could now return true if you just have the forbidden wonder, at least you could check whether the problem is here.

By the way, you should use Player::HasWonder that makes the code easier to read.

**Comment by LynxAbraxas** [comment]
> Well, the code seems to the AI from trying to establish embassies, if you have the forbidden wonder and no wonder that is obsolete. Obviously, that isn't what you want, but for testing it should be fine.

Sorry, I don't get here what you mean. 
The intention of the code of https://github.com/civctp2/civctp2/commit/00752a6233c710add9d98111d569ba224367d9ae is that the AI does not try to install embassies in cities of a civ that has a wonder that forbids to do so (like the "forbidden city" wonder).

**Comment by MartinGuehmann** [comment]
> > Well, the code seems to the AI from trying to establish embassies, if you have the forbidden wonder and no wonder that is obsolete. Obviously, that isn't what you want, but for testing it should be fine.
> 
> Sorry, I don't get here what you mean.
> The intention of the code of [00752a6](https://github.com/civctp2/civctp2/commit/00752a6233c710add9d98111d569ba224367d9ae) is that the AI does not try to install embassies in cities of a civ that has a wonder that forbids to do so (like the "forbidden city" wonder).

It just doesn't do that: It checks whether the target owner has a wonder that closes embassies. If yes, it checks whether the target owner has a wonder that is not obsolete. If yes, the target is immune.

Actually, I have just checked wonderutil_GetCloseEmbassies, it already checks whether the wonder is obsolete. Maybe it is worth checking where else wonderutil_IsObsolete is used without reason.

**Comment by LynxAbraxas** [comment]
There is definitely something wrong with the goals for Diplomats:
ss_2020-03-06_14:55:34
I suspect they try to install embassies even when at war.

**Comment by LynxAbraxas** [comment]
Concerning https://github.com/civctp2/civctp2/pull/259#issuecomment-581060775
> Concerning #256, I wonder what the AI uses for determining if a unit/army should go for pirating just the seen cell info or the global map info (as available to the human player int this particular case). Appropriate and fair for general orders would be the unseen cell info but that does not exist so far for trade routes.

To determine the pirating position of a goal, it seems the AI uses the `GetTradeSourceList` of the target city
https://github.com/civctp2/civctp2/blob/71571fc29255a13215a289e00668ad055e776f46/ctp2_code/ai/strategy/goals/Goal.cpp#L1059
which consists of the actual active routes, i.e. the AI does not use the (un)seen cell info (like a human must). So actually the AI cheats (has an unfair advantage here), but it is so bad at pirating any way or does so very rarely, that it might be quite appropriate to leave this as is for now. 
It would be easy to skip each route in case `!route.SeenBy(m_owner)` but that would not add the evaluation of seen routes that are now inactive (as a human would with #256)
It would also be possible to improve the evaluation of the best pirating position here by introducing a check if there are tiles along the routes of the target city that contain multiple (known) trade routes.

However, a proper redesign of the evaluation would be to check all routes of the map, skip those that do not belong to the owner of the target city, check if there are tiles with multiple routes (possibly of other civs), trade off amount of routes of a tile versus shortest distance. 
Even nicer would be if the AI could be taught to move along a route to a tile with multiple routes, perserving its last movement point for pirating in that turn, and continue to move in the next turn until the tile with multiple routes is reached. This would correspond to how a clever human would do this.

**Comment by LynxAbraxas** [comment]
The correction concerning establishing embassies is solved in #330.
I won't find the time to improove the pirating goals in the near future, so closed to serve as a reference. Please feel free to pick it up.

**Pull request closed without merging**
