### PR TITLE
save and load pirating army:

### PR DESCRIPTION
**Pull request by LynxAbraxas**
idea from @MartinGuehmann in #131

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Amazing, just works! Many thanks @MartinGuehmann!

Any idea what `m_path_selection_state` is/was meant for?

**Comment by MartinGuehmann** [comment]
> Amazing, just works! Many thanks @MartinGuehmann!
> 
> Any idea what `m_path_selection_state` is/was meant for?

To indicate the state of a selected path of a trade route. The code has some has a getter and setter for it but only the setter is used. So the information is set but never used. And I would say that we don't have any use for that, either.

**Comment by LynxAbraxas** [comment]
It now becomes noticable, that apparently the count of how many times a trade route was pirated is not saved/loaded either. I.e. by saving and loading the AI keeps up the trade route whereas without saving+loading it cancels the route after it has been pirated 3 times. So far I was not able to find the setting for this 3 times count. 
@MartinGuehmann any idea where that might come form?

**Comment by MartinGuehmann** [comment]
That is hold in Diplomat::m_piracyHistory, but it is not saved, anyway that is information that could also be stored in TradeRouteData. As far as I can see the current approach just wastes memory.

So what we need in TradeRouteData is a member that is not really be used and thus can be reused and that is saved. At least we have to save the year and that is a sint32. We could use the spot of  m_recip for the turn actually it is not used and can thus be removed. The number of accumulated events can be a sint16 or a sint8. For that we could split the spot of m_crossesWater it is a BOOL so occupies 32 bits and is also saved as 32 bit integer.

**Comment by LynxAbraxas** [comment]
Not able to fully follow you here. Could you create a commit on top that does what you suggest?

**Comment by MartinGuehmann** [comment]
> Not able to fully follow you here. Could you create a commit on top that does what you suggest?

That's a bit more complicated, so I guess I merge this first.

**Comment by MartinGuehmann** [comment]
> Not able to fully follow you here. Could you create a commit on top that does what you suggest?

This is now #133. Please test, whether everything works as intended.

**Pull request merged**
