### PR TITLE
Science-advance: Draw listbox within border

### PR DESCRIPTION
**Pull request by williamd67**
Before
Screenshot from 2021-05-09 12-00-33
After
Screenshot from 2021-05-09 12-01-17

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Finally came about to test this. Compiles fine and changes appear to work as described.
Du to the shadow effect, the left side of the orange highlight box might look better if it were still 1 or 2 pixel further to the left.

**Comment by williamd67** [comment]
The shadow effect is being fixed in PR #370 (see screenshot in that PR).

**Comment by LynxAbraxas** [comment]
@williamd67 are the changes of this PR now included in #370? If so, can this PR be closed?

**Comment by williamd67** [comment]
@LynxAbraxas, yes indeed this change is part of #370 and by that this PR can be closed.

**Pull request closed without merging**
