### PR TITLE
Show the prerequisites for the current research goal in the tech tree of the Great Library

### PR DESCRIPTION
**Pull request by MartinGuehmann**
Show the prerequisites for the current research goal in the tech tree of the Great Library: This way it is easier to see what needs to be researched for the current research goal.

This PR should still add a label to the tech tree giving the current research and how many prerequisites it has has and how many of those are known.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Sounds great, will give it a test and report back.

**Comment by LynxAbraxas** [comment]
Not sure if I saw the effect of this PR. @MartinGuehmann do you have a screen shot showing where this change should be visible?

**Comment by MartinGuehmann** [comment]
> Not sure if I saw the effect of this PR. @MartinGuehmann do you have a screen shot showing where this change should be visible?

Well it is in the great library and the research chooser. All what you have to do is to set a goal for instance set the goal to Theocracy. And then you will see how many techs you need and how many of those you already know.

In the Great Library you have to go to the tech tree. Go to Theocracy, go to the tree and set the goal to Theocracy and the advances you need in the tech tree get an asterix.

**Comment by LynxAbraxas** [comment]
Got it. That's great! Even works for "set goal" of a unit, e.g. sea ingeneer, just need to click on the advance ("nano assembly") that is listed to give that to get to the advance and then I can click on the tech-tree (which does not work for the unit entry):

ss_2019-06-01_23:10:10

Then I can follow the advance that have an asterix and are not yet known (red frame):

ss_2019-06-01_23:11:06

Which brings me to my currently researched advance (yellow frame):

ss_2019-06-01_23:11:52

So works as expected. Good to go.
PS: It would be nice to have a way to list all advances that are still needed to be researched to get the the goal, but I guess that would be quite complicated as there is no window for showing that info already in the game.

**Comment by MartinGuehmann** [comment]
> Got it. That's great! Even works for "set goal" of a unit, e.g. sea ingeneer, just need to click on the advance ("nano assembly") that is listed to give that to get to the advance and then I can click on the tech-tree (which does not work for the unit entry):

I know, probably also something to change. But that is another PR.

> So works as expected. Good to go.

Well, then let's merge.

> PS: It would be nice to have a way to list all advances that are still needed to be researched to get the the goal, but I guess that would be quite complicated as there is no window for showing that info already in the game.

The only complicated thing is finding a place for it. The candidates are the science chooser and the science window. The rest is a list box and some text elements.

**Comment by LynxAbraxas** [comment]
Just noticed that a commit between https://github.com/civctp2/civctp2/commit/247c8dc9c9be287194605ea5ba1f555884f3e0d7 and the merging of this PR https://github.com/civctp2/civctp2/commit/68fa8412045eef0c63e0bee5933987a00d5cba3b now causes the game to crash when opening the great-library. I'm not sure why that did not happen when I tested this PR as the screenshots show that it had worked then.
@MartinGuehmann should I open a new issue for this or do you already see where the problem could lie?

**Comment by MartinGuehmann** [comment]
> Just noticed that a commit between [247c8dc](https://github.com/civctp2/civctp2/commit/247c8dc9c9be287194605ea5ba1f555884f3e0d7) and the merging of this PR [68fa841](https://github.com/civctp2/civctp2/commit/68fa8412045eef0c63e0bee5933987a00d5cba3b) now causes the game to crash when opening the great-library. I'm not sure why that did not happen when I tested this PR as the screenshots show that it had worked then.
> @MartinGuehmann should I open a new issue for this or do you already see where the problem could lie?

I think, I will test it first. For sure that would be an issue we have to fix, quickly.

**Comment by MartinGuehmann** [comment]
Well, I compiled it on Windows and I got some LDL errors. I then also restored helptile.ldl in the German folder since I thought it had something to do with it. Anyway, I still got some ldl errors, so that I wonder whether originally read the errors correctly or just thought of helptile.ldl.

I think we have also to solve this with the duplicated ldl files in a better way. They should be in the default folder. There is a main files called civ3.ldl, if the game is supposed to look for a ctp2.ldl then we could relocate it.

Here are the errors:

```
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\trademanager.ldl:1: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\intelligence.ldl:2: syntax error
   c3errors.cpp@165 : Error: LDL Error, C:\Activision\CivCTP2\ctp2_data\german\uidata\layouts\intelligence.ldl:2: syntax error
   c3errors.cpp@165 : Error: LDL Error, Duplicate block CTP2_STANDARD_FONT

```

For sure we did not modify intelligence.ldl, so that is really odd. When I open the trade manager I get the following assert:

```
slicengine.cpp@2081: SLIC: control ControlPanelWindow.ControlPanel.ShortcutPad.TradeButton used
    c3debug.cpp@302 : Assertion (dataBlock) Failed in File:c:\activision\civctp2\ctp2_code\ui\aui_common\aui_ldl.cpp, Line:559
    c3debug.cpp@303 : Stack Trace: '  0x01497b8c  [char * __cdecl c3debug_StackTrace(void) + 0x3c]
  0x0148f902  [void __cdecl c3debug_Assert(char const *,char const *,int) + 0x72]
  0x01117ae9  [public: static class aui_Region * __cdecl aui_Ldl::BuildHierarchyFromRoot(char const *) + 0xe9]
  0x0136b30f  [public: __thiscall TradeManager::TradeManager(enum AUI_ERRCODE *) + 0x5f]
  0x0136e213  [public: static enum AUI_ERRCODE __cdecl TradeManager::Initialize(void) + 0x83]
  0x0136d33c  [public: static enum AUI_ERRCODE __cdecl TradeManager::Display(void) + 0x2c]
  0x0134a71d  [public: virtual void __thiscall ShortcutPad::ShortcutCallback<enum AUI_ERRCODE>::operator()(void) + 0x2d]
  0x0134a9fa  [private: static void __cdecl ShortcutPad::ShortcutButtonActionCallback(class aui_Control *,unsigned int,unsigned int,void *) + 0x5a]
  0x010f9b88  [protected: virtual void __thiscall aui_Button::MouseLDropInside(struct aui_MouseEvent *) + 0x168]
  0x011cab59  [public: virtual void __thiscall ctp2_Button::MouseLDropInside(struct aui_MouseEvent *) + 0x39]
  0x0114d34a  [public: void __thiscall aui_Region::MouseDispatch(struct aui_MouseEvent *,int) + 0x29ba]
  0x01146438  [public: enum AUI_ERRCODE __thiscall aui_Region::HandleMouseEvent(struct aui_MouseEvent *,int) + 0x1b8]
  0x0114638b  [public: enum AUI_ERRCODE __thiscall aui_Region::HandleMouseEvent(struct aui_MouseEvent *,int) + 0x10b]
  0x0116f6ea  [public: enum AUI_ERRCODE __thiscall aui_UI::HandleMouseEvents(int,struct aui_MouseEvent *) + 0x14a]
  0x01172396  [public: virtual enum AUI_ERRCODE __thiscall aui_UI::Process(void) + 0x56]
  0x01472e0a  [private: int __thiscall CivApp::ProcessUI(unsigned int,unsigned int &) + 0x27a]
  0x014722cf  [public: int __thiscall CivApp::Process(void) + 0x10f]
  0x0145f15b  [int __stdcall CivMain(struct HINSTANCE__ *,struct HINSTANCE__ *,char *,int) + 0x41b]
  0x01463fce  [WinMain@16 + 0xae]
  0x014b2f0e  [int __cdecl invoke_main(void) + 0x1e]
  0x014b2da7  [int __cdecl __scrt_common_main_seh(void) + 0x157]
  0x014b2c3d  [int __cdecl __scrt_common_main(void) + 0xd]
  0x014b2f88  [WinMainCRTStartup + 0x8]
  0x76858494  [$R002030 + 0x7507e104]
  0x778041c8  [$R002030 + 0x76029e38]
  0x77804198  [$R002030 + 0x76029e08]
```

dataBlock is NULL, which follows from the LDL error. But I don't know why the LDL error happened. After the assert, I went into debug mode and when I saw that dataBlock was NULL, I stopped debugging. But I would expect that the game would crash then.

**Comment by LynxAbraxas** [comment]
Testing this further, I have the impression that the problem occurs when saving a game where a research goal is set.

**Comment by LynxAbraxas** [comment]
Yes, the crash occurs when opening the great-library in a game that was previously saved with a research goal set (that's why I did not observe the problem when testing this PR).
The crash can be avoided by first opening the research window and then clicking on a link that opens the great-library:

ss_2019-07-01_20:41:43
It does not crash then and even opening the great-library directly after this action does not lead to a crash.

I once got a `double free or corruption (!prev)` on the command line but not always in the case of a crash.

**Comment by MartinGuehmann** [comment]
So looks like the LDL errors are another problem.

At least, with new information, I have a some idea where to look.

**Comment by MartinGuehmann** [comment]
I found the problem, now I just have to upload it.

**Comment by LynxAbraxas** [comment]
That's great! Looking forward to testing that (synced your fork of civctp2 but found no new branch/commit so far). 
BTW: Your fork of civctp2 still has branches for already merged PRs: https://github.com/MartinGuehmann/civctp2/branches It's best to delete the merged ones to avoid confusion and accidental use.

**Pull request merged**
