### PR TITLE
Message for the victim of a successful reformation

### PR DESCRIPTION
**Pull request by LynxAbraxas**
Tell the victim of a reformation (conversion owner) about a successful reformation, similar to the owner of a franchise about its close up.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Using `so->AddGold(static_cast<City>(cell->GetCity()).GetProductionLostToFranchise());` instead of the changes to `Unit.*` and `UnitData.*` yields:
```
ArmyData.cpp:2409:26: error: 'City' does not name a type
  so->AddGold(static_cast<City>(cell->GetCity()).GetProductionLostToFranchise());
```
@MartinGuehmann would it be possible to achieve this with a cast?

**Comment by MartinGuehmann** [comment]
> Using `so->AddGold(static_cast<City>(cell->GetCity()).GetProductionLostToFranchise());` instead of the changes to `Unit.*` and `UnitData.*` yields:
> 
> ```
> ArmyData.cpp:2409:26: error: 'City' does not name a type
>   so->AddGold(static_cast<City>(cell->GetCity()).GetProductionLostToFranchise());
> ```
> 
> @MartinGuehmann would it be possible to achieve this with a cast?

No, you can't do this. There is is no class "City", cities are basically units with additional CityData.

**Comment by LynxAbraxas** [comment]
Basically works:

ss_2019-09-30_23:12:20

ss_2019-09-28_22:09:32

but issue #51 seems to apply to the case of suing a franchise.

**Comment by LynxAbraxas** [comment]
https://github.com/civctp2/civctp2/pull/191/commits/4ec3485db04b6f0f6372ac0d837787a225e30fcf does not seem to solve #51.

Comparing similar functions like `ReformCity`, I wonder if this line
https://github.com/civctp2/civctp2/blob/4ec3485db04b6f0f6372ac0d837787a225e30fcf/ctp2_code/gs/gameobj/ArmyData.cpp#L2405
should be changed to use `c.m_id` like
https://github.com/civctp2/civctp2/blob/4ec3485db04b6f0f6372ac0d837787a225e30fcf/ctp2_code/gs/gameobj/ArmyData.cpp#L4307

**Comment by MartinGuehmann** [comment]
> [4ec3485](https://github.com/civctp2/civctp2/commit/4ec3485db04b6f0f6372ac0d837787a225e30fcf) does not seem to solve #51.
> 
> Comparing similar functions like `ReformCity`, I wonder if this line
> https://github.com/civctp2/civctp2/blob/4ec3485db04b6f0f6372ac0d837787a225e30fcf/ctp2_code/gs/gameobj/ArmyData.cpp#L2405
> 
> 
> should be changed to use `c.m_id` like
> https://github.com/civctp2/civctp2/blob/4ec3485db04b6f0f6372ac0d837787a225e30fcf/ctp2_code/gs/gameobj/ArmyData.cpp#L4307

Well, the class ID, from which Unit is derived, defines the needed cast operators:

```
	operator int() const  { return m_id; };
	operator unsigned int() const  { return m_id; };
	operator unsigned long() const  { return m_id; };
```

Actually, I would prefer them as defined as sint32 etc. operators. Actually, it shouldn't make a difference, whether you use  `c.m_id`. However, considering the definitions of the cast operators, this would be cleaner.

**Comment by LynxAbraxas** [comment]
I see, thanks @MartinGuehmann for that explanation. 
It seems the issure reported above was an unfortunate coincidence. I was testing `TURNS_TO_SUE_FRANCHISE 1`. Due to a `reloadslic` the former messages were gone and just in that turn the franchises in the neighboring cities were removed (with a delay as well). So everything works as expected. I found that this nonobvious behavior deserves some extra info in the messages, so I added the info on the number of turns it takes to remove the franchise.

**Comment by MartinGuehmann** [comment]
And the message should really say: "to close up shop in 1 turn**s**"?

**Comment by LynxAbraxas** [comment]
> And the message should really say: "to close up shop in 1 turns"?

Since it can be more than 1 turn or 0, I decided to go for the plural in any case because it would be quite cumbersome to differentiate that with an extra message. Or is there a simple way to add to the `SlicObject` a string that can be used in the message text?

**Comment by LynxAbraxas** [comment]
With https://github.com/civctp2/civctp2/pull/191/commits/4aa49b95d450b2cbd8526d1ff99353213626f746 the sue messages of units are now correct:

ss_2019-10-05_16:24:34

**Comment by LynxAbraxas** [comment]
This PR is read to go in from my side unless there are any concerns.

**Comment by MartinGuehmann** [comment]
> > And the message should really say: "to close up shop in 1 turns"?
> 
> Since it can be more than 1 turn or 0, I decided to go for the plural in any case because it would be quite cumbersome to differentiate that with an extra message. Or is there a simple way to add to the `SlicObject` a string that can be used in the message text?

Maybe there is, but if you just write "turn(s)" / "Runde(n)" you should be fine.

For the other languages I would just leave the original text and add the English piece. Maybe with a note: Please translate. So that this won't get lost.

**Comment by LynxAbraxas** [comment]
OK, done.

**Comment by MartinGuehmann** [comment]
Well, if you could still add a German translation for:

`REFORM_CITY_VICTIM			"Fremde Inquisitoren haben die Stadt {city[0].name} reformiert und ihre Bürger stehen nicht mehr unter unserem Einfluss. Sie zahlten jede Runde {gold[0].value} Gold."`

**Comment by LynxAbraxas** [comment]
OK, done too.

**Comment by MartinGuehmann** [comment]
Well, then let's merge.

**Comment by LynxAbraxas** [comment]
Message to the victim of a successful franchise also works:
ss_2019-10-25_00:18:32
ss_2019-10-25_23:51:55

**Pull request merged**
