### PR TITLE
Debug "nation conquered" message even if nation still exists

### PR DESCRIPTION
**Pull request by LynxAbraxas**
This PR is meant to solve #388.

### CODE REVIEW

**Comment by LynxAbraxas** [comment]
Commit d722e83 solves #388 (no nation conquered message any more) in case of a not incited but successful slave uprising (i.e. too many slaves in regard to citizen):
ss_2022-09-01_23:42:01
ss_2022-09-01_23:51:46
ss_2022-09-01_23:44:34
ss_2022-09-01_23:44:44

**Comment by LynxAbraxas** [comment]
However, it does not yet work for the case where an successful slave uprising was incited by an Abolitionist:
ss_2022-09-02_00:09:50
ss_2022-09-02_00:12:54

**Comment by LynxAbraxas** [comment]
Using the debug-version I get 3 assertions in the case of incited uprising:
```
Assertion (NO_CONTACT_DECLARE_WAR) Failed in File:ai/diplomacy/diplomat.cpp, Line:1759
Messagebox(Assert): Assertion (NO_CONTACT_DECLARE_WAR) Failed in File:ai/diplomacy/diplomat.cpp, Line:1759

Assertion (false) Failed in File:Unit.cpp, Line:218
Messagebox(Assert): Assertion (false) Failed in File:Unit.cpp, Line:218

Assertion (r) Failed in File:Unit.cpp, Line:220
Messagebox(Assert): Assertion (r) Failed in File:Unit.cpp, Line:220
```

and the game crashes during processing end-of-turn.

**Comment by LynxAbraxas** [comment]
With [2f86a39](https://github.com/civctp2/civctp2/pull/390/commits/2f86a39e789cfef10ab4c5096d77ff68931a079e) the assertions in `Unit.cpp` are gone. However the main problem remains. I have the impression that the processes behind
https://github.com/civctp2/civctp2/blob/5c67aa3eabfb0829335a942a32d20d576ea641d7/ctp2_code/gs/gameobj/CityData.cpp#L6316
do not properly handle the special situation that there are 2 army on the same position, the slave army and the original city army.
@MartinGuehmann do you have any ideas where this might go wrong? I guess it could be from picking the army from the current/city pos, which proabaly yields the newly created slave army instead of the city army and then in the end leads to the message, where it seems that the successful army and the defeated one are exchanged.

**Comment by LynxAbraxas** [comment]
The debug logs show:
```
   ArmyData.cpp@6344: Army 0xd000087a Executing order ORDER_INCITE_UPRISING @ (29,77), turn=219
   ArmyData.cpp@3446: Cost to incite uprising: 4905
   slicfunc.cpp@538 : Slic_Text: Foreign abolitionists have managed to infiltrate our city of {city[0].name}, inciting a slave uprising.
   Advances.cpp@438 : Advance: Player 18 was given Toolmaking as an initial advance
   Advances.cpp@438 : Advance: Player 18 was given Agriculture as an initial advance
    ObjPool.cpp@92  : ObjPool: Inserting object id 0xa0000017
   UnitData.cpp@311 : Creating unit: id: 0x100007cf, type: 2, owner: 18
    ObjPool.cpp@92  : ObjPool: Inserting object id 0x100007cf
     Player.cpp@896 : Player::CreateUnitNoPosition(t=2) : newunit=100007cf
   UnitData.cpp@311 : Creating unit: id: 0x100007d0, type: 2, owner: 18
    ObjPool.cpp@92  : ObjPool: Inserting object id 0x100007d0
     Player.cpp@896 : Player::CreateUnitNoPosition(t=2) : newunit=100007d0
   UnitData.cpp@311 : Creating unit: id: 0x100007d1, type: 2, owner: 18
    ObjPool.cpp@92  : ObjPool: Inserting object id 0x100007d1
     Player.cpp@896 : Player::CreateUnitNoPosition(t=2) : newunit=100007d1
   UnitData.cpp@311 : Creating unit: id: 0x100007d2, type: 2, owner: 18
    ObjPool.cpp@92  : ObjPool: Inserting object id 0x100007d2
     Player.cpp@896 : Player::CreateUnitNoPosition(t=2) : newunit=100007d2
    ObjPool.cpp@92  : ObjPool: Inserting object id 0xd0000890
   diplomat.cpp@5588: Player 18 initialized strategy to STRATEGY_DIPLOMATIC_DEFAULT.
    c3debug.cpp@304 : Assertion (NO_CONTACT_DECLARE_WAR) Failed in File:ai/diplomacy/diplomat.cpp, Line:1751
    c3debug.cpp@305 : Stack Trace: '  0xf3910227  [DebugCallStack_Save + 0x28]
  0xf3910683  [c3debug_StackTrace() + 0x51]
  0xf390db8b  [c3debug_Assert(char const*, char const*, int) + 0x94]
  0xf3c4bf90  [Diplomat::DeclareWar(int) + 0xee]
  0xf3c4a3a3  [Diplomat::LogViolationEvent(int, PROPOSAL_TYPE) + 0x9a9]
  0xf3da12bc  [ArmyData::Fight(CellUnitList&) + 0x8ea]
  0xf3d87e66  [Army::Fight(CellUnitList&) + 0x32]
  0xf3dc712f  [CityData::FinishUprising(Army&, UPRISING_CAUSE) + 0x1a9]
  0xf3e7ce59  [FinishUprisingEvent::GEVHookCallback(GAME_EVENT, GameEventArgList*) + 0xcf]
  0xf3d6cb34  [GameEventHook::Activate(GameEventArgList*, int, int&) const + 0x130]
  0xf3d698ee  [GameEventManager::ActivateHook(GAME_EVENT, GameEventArgList*, int, int&) + 0xa8]
  0xf3d6c54d  [GameEvent::Process() + 0x5f]
  0xf3d695c4  [GameEventManager::ProcessHead() + 0xac]
  0xf3d6948d  [GameEventManager::Process() + 0x49]
  0xf3922c36  [CivApp::Process() + 0x160]
  0xf3917f18  [CivMain(int, char**) + 0x2fe]
  0xf3917aa2  [main + 0x33]
  0xe25b6d90  [_abi_tag + 0x29ad0]
  0xe25b6e40  [_abi_tag + 0x29b80]
  0xf38fdad5  [start + 0x25]
'
 CTP2Combat.cpp@131 : MOVEH: Attacker@1,3 -> 0,3
 CTP2Combat.cpp@131 : MOVEV: Attacker@1,2 -> 1,3
 CTP2Combat.cpp@131 : Attacker: d0000890, Defender: (28,79)
 CTP2Combat.cpp@131 : attacker[0]: 100007cf @ 10.000000HP
 CTP2Combat.cpp@131 : attacker[1]: 100007d0 @ 10.000000HP
 CTP2Combat.cpp@131 : attacker[2]: 100007d1 @ 10.000000HP
 CTP2Combat.cpp@131 : attacker[3]: 100007d2 @ 10.000000HP
 CTP2Combat.cpp@131 : defender[0]: 1000001e @ 10.000000HP, army=d000001e
 CTP2Combat.cpp@131 : ROUND 0: (Rand calls: 22101)
 CTP2Combat.cpp@131 : RANGED: Attacker@( 1, 3) -Attacking-  Defender@( 0, 3) -  HitChance: 0.40
```
....
```
 CTP2Combat.cpp@131 : ROUND 23: (Rand calls: 22172)
 CTP2Combat.cpp@131 : RANGED: Attacker@( 1, 3) -Attacking-  Defender@( 0, 3) -  HitChance: 0.40
 CTP2Combat.cpp@131 : RANGED: Attacker@( 1, 3) -HIT-  Defender@( 0, 3) for 1.00 CTP2Combat.cpp@131 : , killing Defender.
   ArmyData.cpp@6344: Army 0xd0000890 Executing order ORDER_VICTORY_MOVE @ (28,79), turn=219
regardevent.cpp@95  : //        Kill Unit regard event
       Unit.cpp@161 : Unit::RemoveAllReferences: id: 0x1000001e cause: 2
    WrlUnit.cpp@71  : World::RemoveUnitReference: id: 0x1000001e
     Player.cpp@1230: Player::RemoveUnitReference(1000001e, 2)
    ObjPool.cpp@105 : ObjPool: Deleting object id 0xd000001e
    ObjPool.cpp@105 : ObjPool: Deleting object id 0x1000001e
regardevent.cpp@95  : //        Kill Unit regard event
       Unit.cpp@161 : Unit::RemoveAllReferences: id: 0x100007cf cause: 2
   slicfunc.cpp@538 : Slic_Text: You have failed to heed the call to power. Your empire lies in ruin and your people answer to a new, more powerful leader. Your only hope is that history will be kind to you and your legacy. For now, the reign of {player[0].leader_name} is at an end.
   slicfunc.cpp@538 : Slic_Text: The {player[1].civ_name_plural} have conquered the nation of {player[0].country_name}.
    ObjPool.cpp@92  : ObjPool: Inserting object id 0xc000017d
    ObjPool.cpp@105 : ObjPool: Deleting object id 0x100007cf
   CityData.cpp@6357: The uprising succeeded
   UnitData.cpp@1890: ResetCityOwner: 10000030, new: 18, old: 2, conq: 0, cause: 3
     Player.cpp@5602: Player 18 built wonder 13
       Unit.cpp@161 : Unit::RemoveAllReferences: id: 0x1000037d cause: 47
     Player.cpp@1230: Player::RemoveUnitReference(1000037d, 47)
    ObjPool.cpp@105 : ObjPool: Deleting object id 0x1000037d
 SlicEngine.cpp@2082: SLIC: control ControlPanelWindow.ControlPanel.TurnButton used
EndTurnButton.c@38  : Button end turn, 1
GameEventManage@974 : GameEventManager::EndTurnRequest, but there are 40 pending actions (or it was already requested), not doing it yet.
```
and then crashes while evaluation player 2 at:
```
      ctpai.cpp@1582: // ASSIGN POPULATIONS -- Turn 220
      ctpai.cpp@1583: //                                                 Player 2
      ctpai.cpp@1585: //  elapsed time = 5 ms
   director.cpp@3060: Director::AddBeginScheduler(2)
```

**Comment by LynxAbraxas** [comment]
> and then crashes while evaluation player 2 at:
> 
> ```
>       ctpai.cpp@1582: // ASSIGN POPULATIONS -- Turn 220
>       ctpai.cpp@1583: //                                                 Player 2
>       ctpai.cpp@1585: //  elapsed time = 5 ms
>    director.cpp@3060: Director::AddBeginScheduler(2)
> ```

This is solved by 02cb247, however does not solve the actual problem of the message and the run of 
https://github.com/civctp2/civctp2/blob/5c67aa3eabfb0829335a942a32d20d576ea641d7/ctp2_code/gs/gameobj/Player.cpp#L6901
which causes the message
https://github.com/civctp2/civctp2/blob/5c67aa3eabfb0829335a942a32d20d576ea641d7/ctp2_code/gs/gameobj/Player.cpp#L6923-L6932
and even stops the AI to manage that newly created nation
https://github.com/civctp2/civctp2/blob/5c67aa3eabfb0829335a942a32d20d576ea641d7/ctp2_code/gs/gameobj/Player.cpp#L6939-L6948

The main problem seems to arise from the TempSlaveUnit
https://github.com/civctp2/civctp2/blob/5c67aa3eabfb0829335a942a32d20d576ea641d7/ctp2_code/gs/gameobj/CityData.cpp#L6258-L6270
which so far was not inserted into `m_all_units` which is then used to determine if a player without a city is dead
https://github.com/civctp2/civctp2/blob/5c67aa3eabfb0829335a942a32d20d576ea641d7/ctp2_code/gs/gameobj/Player.cpp#L6888-L6897
This is now done with 002c27d.

**Comment by LynxAbraxas** [comment]
All bugs solved and no assertion any more with  c68e921, ef49f99 seems to have not the desired effect tough.
@MartinGuehmann what do you think? Ready for merging?

**Comment by LynxAbraxas** [comment]
My observation here https://github.com/civctp2/civctp2/pull/200#issuecomment-552110349 might be related to the fact, that the AI was not operating civs from slave uprisings without this PR.

**Comment by LynxAbraxas** [comment]
With e24e143, the slave uprising fight is done with the vandals/barbars which avoids the "nation conquered"-message in case the uprising army is defeated. It not only avoids the message but also the bonus points for defeating a nation which is quite inappropriate in case just a few cheapest-units make up the slave army, in the extreme just one archer. If the uprising army succeeds, the game checks if a new civ can arise from that and gives the city and the remaining units of the army to that nation.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann what do you think? Ready for merging?

**Comment by MartinGuehmann** [comment]
That looks good.

**Pull request merged**
